huggingface/peft

README.md, setup.py
Here's a quick review of `peft` along with a few typo fixes/proposals.
Really cool library! I enjoyed playing with it a lot. The code is neat, clear, and concise. See below for a few feedback comments and improvement proposals:
- I've updated the version to use the `0` suffix. This means that when doing release candidates (`.rc0`, `.rc1`, ...) you can update the dev suffix as well to reflect where the current development version lies. You won't need it right now but might as well have that as a good practice early on.
- It's currently very coupled with transformers. Will this remain this way, or will this be the case only for the first versions?
- Both `transformers` and `loralib` are hard dependencies. I understand for `transformers` if the answer to the above is that it's to be deeply …
=> Review & fix typos

examples/lora_dreambooth/train_dreambooth.py
It's often useful to monitor sample images generated throughout the training process. This PR enables this by passing `--validation_prompt="a photo of sks dog in a bucket"`, with a report destination, e.g. `--report_to="wandb"`. Much copied and a little modified from @patrickvonplaten 's work in his [train_dreambooth_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py) example.
=> allow validation images for lora training

src/peft/tuners/lora.py
=> for lora, raise error when no target modules in base model

src/peft/peft_model.py
=> make `save_pretrained` work in a way training could be resumed

setup.py, src/peft/__init__.py
=> release v0.2.0.dev0

src/peft/peft_model.py, src/peft/tuners/prompt_tuning.py
closes: https://github.com/huggingface/peft/issues/62
=> convert prompt tuning vocab to fp32

src/peft/peft_model.py, src/peft/tuners/lora.py, src/peft/utils/other.py
1. making `prepare_model_for_training` flexible. For example, Whisper model doesn't have `lm_head` but has `proj_out`
=> making `prepare_model_for_training` flexible

README.md
=> add `EleutherAI/gpt-neox-20b` to support matrix

src/peft/peft_model.py, src/peft/tuners/lora.py
1. fix merging lora weights for inference
=> fix merging lora weights for inference

src/peft/tuners/lora.py
This PR fixes autocast issues with bnb models, users should now be able to run inference & training without autocast
I need to test it though on the notebooks
cc @pacman100
=> [`core`] Fix autocast issue

src/peft/peft_model.py
=> issue#126: torch.load device issue.

examples/causal_language_modeling/peft_lora_clm_accelerate_ds_zero3_offload.py, examples/causal_language_modeling/peft_prefix_tuning_clm.ipynb, examples/causal_language_modeling/peft_prompt_tuning_clm.ipynb, examples/conditional_generation/peft_lora_seq2seq.ipynb, examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py, examples/conditional_generation/peft_lora_seq2seq_accelerate_fsdp.py, examples/conditional_generation/peft_prefix_tuning_seq2seq.ipynb, examples/lora_dreambooth/train_dreambooth.py, pyproject.toml, src/peft/peft_model.py, src/peft/tuners/p_tuning.py, src/peft/utils/config.py, tests/test_peft_model.py
=> minor fixes to the examples

README.md
Re: https://github.com/huggingface/peft/issues/123
=> Add Prefix Tuning citation

src/peft/peft_model.py, src/peft/tuners/lora.py, src/peft/utils/config.py
1. Fixes #153 
2. adding 8bitMegredLinear lora
=> lora fixes and adding 8bitMegredLinear lora

src/peft/tuners/lora.py
=> fixing merged_linear lora issues

README.md, src/peft/mapping.py
Adding support for [ChatGLM](https://github.com/THUDM/ChatGLM-6B), here is the example:
https://github.com/mymusise/ChatGLM-Tuning/blob/master/finetune.ipynb
=> ChatGLM support

examples/lora_dreambooth/train_dreambooth.py
This PR just fixes the currently failing test on `main`
cc @pacman100
=> Fix failing test on `main`

README.md
provider name in capitalization
=> Have fix typo in README

docs/source/_toctree.yml, docs/source/package_reference/config.mdx, docs/source/package_reference/peft_model.mdx, docs/source/package_reference/tuners.mdx, src/peft/peft_model.py, src/peft/tuners/lora.py, src/peft/tuners/p_tuning.py, src/peft/tuners/prefix_tuning.py, src/peft/tuners/prompt_tuning.py, src/peft/utils/config.py
This PR adds API references for configurations, PEFT models, and tuners. Let me know if there is anything else we should add!
cc @pacman100
=> [docs] Add API references

scripts/stale.py
We shouldn't stale issues with the label "PRs welcome to address this"
cc @pacman100
=> [`Automation`] Update stale.py

README.md
=> docs: have fix bit typo README

docs/source/_toctree.yml, docs/source/task_guides/seq2seq-prefix-tuning.mdx
Moves the prefix tuning for seq2seq [notebook](https://github.com/huggingface/peft/blob/main/examples/conditional_generation/peft_prefix_tuning_seq2seq.ipynb) to the docs.
=> [docs] Prefix tuning for Seq2Seq

.github/workflows/build_docker_images.yml, docker/peft-cpu/Dockerfile, docker/peft-gpu/Dockerfile
This PR will add a proper dockerfile and a github action to push to docker image everyday - based on https://github.com/huggingface/accelerate/blob/main/.github/workflows/build_docker_images.yml & https://github.com/huggingface/accelerate/blob/main/docker/accelerate-gpu/Dockerfile
As `peft` is closely tied to the latest versions of `transformers` & `accelerate` the docker image will contain the main branch of these two libraries 
Also we can discuss about whether it is necessary to have a workflow that pushes the fresh docker image everyday, or manually clone accelerate & transformers on the VM and just fetch the latest changes
=> [`test`] Add Dockerfile 

docs/source/_toctree.yml, docs/source/task_guides/ptuning-seq-classification.mdx
Moves the p-tuning for sequence classification [notebook](https://github.com/huggingface/peft/blob/main/examples/sequence_classification/P_Tuning.ipynb) into the docs.
=> [docs] P-tuning for sequence classification

docs/source/_toctree.yml, docs/source/task_guides/int8-asr.mdx
Moves the int8 training for multilingual ASR [notebook](https://github.com/huggingface/peft/blob/main/examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb) to the docs.
=> [docs] int8 training

docs/source/_toctree.yml, docs/source/conceptual_guides/prompting.mdx
Adds a brief conceptual overview of the various soft prompting methods.
=> [docs] Conceptual overview of prompting methods

scripts/log_reports.py, setup.py
This PR adds a better log message + updates the `test` requirements to add `slack_sdk` installed on the docker images
cc @pacman100
=> [`core`] Better log messages

.github/workflows/nightly.yml, Makefile, scripts/log_reports.py, setup.py
This PR fixes all the issues related to nightly tests. 
Now we can generate nice results such as:
cc @pacman100
=> [`CI`] Fix nightly CI issues

docs/source/index.mdx
Fixes misaligned Supported models header:
=> [docs] Fix index

src/peft/import_utils.py, src/peft/tuners/lora.py, tests/test_common_gpu.py
This PR simply protects 4bit Linear imports for users that have a lower version of bnb
Fixes https://github.com/TimDettmers/bitsandbytes/issues/416
cc @pacman100
=> [`core`] Protect 4bit import

src/peft/peft_model.py, tests/test_decoder_models.py, tests/test_encoder_decoder_models.py, tests/testing_common.py
Fixes: https://github.com/huggingface/transformers/issues/23170
Before this PR, users had to manually enable gradients to the input in order to properly use gradient checkpointing. This PR makes it more user friendly, by automatically doing it for users under the hood
Added also CI tests for that
cc @pacman100
=> [`core`] Add gradient checkpointing check

docs/source/task_guides/image_classification_lora.mdx
=> [docs] Fix LoRA image classification docs

docs/source/index.mdx
Adds better navigation to the index from feedback [here](https://huggingface.slack.com/archives/C04L3MWLE6B/p1683253599558609).
=> [docs] Prettify index

src/peft/tuners/adaption_prompt.py, tests/test_adaption_prompt.py
Fixes #455 
The PR also adds nice CI test to make sure this won't happen by future PRs
cc @pacman100 @HamidShojanazeri
=> [`Llama-Adapter`] fix half precision inference + add tests

src/peft/peft_model.py
Fixed problem with duplicate same code.
=> Fixed problem with duplicate same code.

examples/int8_training/Finetune_opt_bnb_peft.ipynb, src/peft/peft_model.py, src/peft/utils/__init__.py, src/peft/utils/other.py
1. Adds library name to model card
Example:
```
model.push_to_hub("smangrul/falcon-40B-int4-peft-lora-sfttrainer-sample")
```
=> add library name to model card

src/peft/utils/config.py
Fixes https://github.com/huggingface/peft/issues/552
Fixes https://github.com/huggingface/peft/issues/560
The fix is to correctly split the keyword arguments between those that are used by the class itself and the arguments used by `hf_hub_download`
cc @pacman100
=> [`core`] Fix config kwargs

tests/test_gpu_examples.py
1. as Whisper model uses Conv layer in encoder, checkpointing disables grad computation. to avoid this, make the inputs trainable.
=> update whisper test

README.md
bibtex was giving me a "too many commas" error, this fixes it
=> Update README.md, citation

setup.py, src/peft/tuners/lora.py, tests/test_stablediffusion.py, tests/testing_utils.py
Hi!
I've discovered that when patching Conv2d layers with PEFT LoRA, those LoRAs are not properly merged into base model, so I've created a fix for this.
Also, I've added a test to cover this functionality for StableDiffusionPipeline.
@pacman100 your review is kindly appreciated.
=> [Bugfix] Fixed LoRA conv2d merge

src/peft/mapping.py, src/peft/peft_model.py
This PR serves as a chore to tentatively introduce type hints into the library
It helps with development and catch bugs 😃
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>
=> style: tentatively add hints for some public function

docs/source/conceptual_guides/lora.mdx, src/peft/tuners/lora.py
Adds example usage for `merge_and_unload` in the API docs.
=> [docs] API example

src/peft/tuners/ia3.py
As discussed internally.
Note: No tests are added but this will be tested in via #683.
=> Fix a small bug in forward method of IA³

src/peft/peft_model.py
1. Reverts the change from a WIP thing that got merged in main
=> revert change

src/peft/tuners/adalora.py, src/peft/tuners/lora.py
The previous example is no longer functional, but I have made slight modifications to ensure its compatibility with the latest version, making it executable once again.
=> Updated Example in Class:LoraModel

src/peft/utils/other.py
Just tried it (it works), confirmed by a cerebras employee on: https://huggingface.co/cerebras/btlm-3b-8k-base/discussions/10#64c000e1087f3237a059b4a3
=> Add btlm to officially supported LoRA

README.md
As discussed, since it is not kept up to date.
=> DOC: Remove backlog section from README.md

.github/workflows/build_docker_images.yml
As per title and as discussed internally. Although all seems to work fine on our end with `v2`, let's upgrade to higher versions to make sure we're on the safe zone https://github.com/huggingface/accelerate/pull/1910
=> Upgrade docker actions to higher versions

docs/source/task_guides/semantic_segmentation_lora.mdx, examples/semantic_segmentation/semantic_segmentation_peft_lora.ipynb
Fixes https://github.com/huggingface/transformers/issues/25801
=> Fix doc for semantic_segmentation_lora

examples/feature_extraction/peft_lora_embedding_semantic_search.py
=> FIX: linting issue in example

src/peft/utils/other.py, tests/test_decoder_models.py
1. Support Prefix Tuning for StarCoder models.
=> support prefix tuning for starcoder models

src/peft/config.py, src/peft/helpers.py, src/peft/import_utils.py, src/peft/mapping.py
This PR aims to add some better type hints.
=> feat: add type hints

.github/workflows/integrations_tests.yml
Attempts to fix the failing integration tests: https://github.com/huggingface/peft/actions/runs/6312091143/job/17137402981
=> Fix integrations_tests.yml

src/peft/peft_model.py
Fix for:
https://github.com/huggingface/transformers/pull/26623
https://github.com/huggingface/peft/issues/996
=> Fix word_embeddings match for deepspeed wrapped model

src/peft/tuners/lora/layer.py
Addresses: https://github.com/huggingface/diffusers/pull/5417/#discussion_r1362089513 and as discussed offline
=> [`LoRA`] Raise error when adapter name not found in `set_scale`

README.md
Handling misspell and path link to StackLLaMa in trl research projects.
=> docs(README): bit misspell current path link StackLLaMa

.github/workflows/nightly.yml
It seems the environment variable was not correctly set .. This PR fixes it
=> Fix slow tests not running

setup.py, src/peft/__init__.py
=> Release version 0.6.0

tests/test_common_gpu.py
1. Fixes the failing CI tests: https://github.com/huggingface/peft/actions/runs/6792850417/job/18466760365 and https://github.com/huggingface/peft/actions/runs/6792850417/job/18466760175
=> fix the failing CI tests

setup.py, src/peft/__init__.py
As per title, as we are going to do a minor release (edit: patch release)
=> Change to 0.6.1.dev0

setup.py, src/peft/__init__.py
=> Release: 0.6.1

setup.py, src/peft/__init__.py
As per title cc @BenjaminBossan @pacman100
=> set dev version

docs/source/task_guides/dreambooth_lora.mdx
fix a typo in DreamBooth fine-tuning with LoRA doc
=> fix doc typo

tests/test_custom_models.py
Previously, the corresponding tests were testing only whether specific parameters had `requires_grad` `True` or `False`. Now, all parameters are being checked. This is more rigorous.
Also, tests for `Embedding`, `Conv1D`, `Conv2d` were added (LoRA and IA³), thus superseding PR #1115.
Finally, tests for LoHa and LoKr were added.
I considered moving the tests to a separate module, as they were getting quite big and this would help with readability. For now, I left them in the same module because it leads to a better diff view and is thus easier to review. LMK if I should move the tests to a separate file.
=> TST: Improve requires grad testing:

tests/test_gpu_examples.py
With the recent changes of making safetensors default saving format, we need to update the slow tests accordingly
=> [`Tests`] Fix daily CI

src/peft/tuners/lora/bnb.py
Fixes https://github.com/huggingface/peft/issues/1138
=> [`core` / `LoRA`] Add `adapter_names` in bnb layers

setup.py
Add a reminder in the release checklist to consult the release note google doc.
=> Update release checklist about release notes

.github/workflows/build_docker_images.yml, docker/peft-gpu/Dockerfile
As discussed offline cc @BenjaminBossan @muellerzr
=> Fix dockerfile build

.github/workflows/nightly.yml
cc @glegendre01 @BenjaminBossan @pacman100
=> [`Tests`] Migrate to AWS runners

setup.py, src/peft/__init__.py, tests/test_config.py
In preparation for the 0.7.0 release. Also remove obsolete TODO comments.
=> Release: 0.7.0

docs/source/_toctree.yml, docs/source/package_reference/oft.md
=> [docs] OFT

docs/source/_toctree.yml, docs/source/package_reference/peft_model.md, docs/source/tutorial/peft_model_config.md, src/peft/config.py
A rough draft that focuses more on setting up configurations for PEFT methods and the `PeftModel` itself. Some of the content probably overlaps with the quicktour, but I wanted to go more in-depth, so please feel free to let me know if I'm missing anything. The goal of this tutorial is to provide a solid foundation for users to apply any PEFT method to any model.
Looking forward to hearing your thoughts @BenjaminBossan @pacman100 @younesbelkada !
=> [docs] PeftConfig and PeftModel

pyproject.toml, tests/test_common_gpu.py, tests/test_gpu_examples.py, tests/testing_utils.py
This is to make running the bitsandbytes integration tests as part of the bitsandbytes release process easier. While we're at it, I fixed a few small things, mainly typos and have the tests working on >2 GPUs.
=> Bnb integration test tweaks

setup.py, src/peft/__init__.py, tests/test_custom_models.py
Do a patch release, mainly for #1252 and #1243.
=> Release: 0.7.1

scripts/log_reports.py
=> FIX Error in log_reports.py

src/peft/tuners/tuners_utils.py
remove duplicated description for _check_target_module_exists in BaseTuner class
=> remove a duplicated description in peft BaseTuner

.github/workflows/nightly-bnb.yml
This PR fixes the bnb dockerfile for single gpu that I forgot to add in a previous PR. Also I fixed a syntax error in the dockerfile. CI is finally [green](https://github.com/huggingface/peft/actions/runs/7339006456) !
=> [BNB] fix dockerfile for single gpu

examples/feature_extraction/peft_lora_embedding_semantic_search.py
The parameter description is wrong and duplicates the parameter description above.
=> fix some args desc

src/peft/tuners/adalora/model.py
https://github.com/huggingface/peft/issues/1327
=> Doc about AdaLoraModel.update_and_allocate

docs/source/developer_guides/lora.md
As discussed internally via Slack:https://huggingface.slack.com/archives/C04L3MWLE6B/p1705057048258809
Working Colab: https://colab.research.google.com/gist/sayakpaul/b00dca6bbbea287c9d43272611915247/scratchpad.ipynb
=> [Docs] make add_weighted_adapter example clear in the docs.

src/peft/utils/constants.py
cc @pacman100 @abhishekkrthakur
=> add mixtral in LoRA mapping

src/peft/utils/save_and_load.py
1. Currently, for non prompt learning approaches, the embedding layers are only saved when present in the `target_models` list. This PR saves the embedding layers if they are resized when compared to the base model.
=> save the embeddings even when they aren't targetted but resized

docs/source/developer_guides/quantization.md
Fixes various typos in the LoftQ docs.
=> Fix various typos in LoftQ docs.

setup.py, src/peft/__init__.py
1. Release: v0.8.0
Fixes: https://github.com/huggingface/peft/issues/1400
=> Release: v0.8.0

examples/conditional_generation/peft_adalora_seq2seq.py, src/peft/tuners/adalora/layer.py
Resolves #1539
Additionally, a small fix to the AdaLoRA training script was added.
=> FIX Allow AdaLoRA rank to be 0

examples/causal_language_modeling/peft_lora_clm_with_additional_tokens.ipynb, examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb, examples/int8_training/Finetune_opt_bnb_peft.ipynb, examples/int8_training/peft_adalora_whisper_large_training.py, examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb, setup.py, src/peft/__init__.py, src/peft/tuners/lora/model.py, src/peft/tuners/lora/tp_layer.py, src/peft/utils/__init__.py, src/peft/utils/other.py, tests/test_adaption_prompt.py, tests/test_gpu_examples.py, tests/test_multitask_prompt_tuning.py, tests/testing_common.py
Besides updating versions, removed 2 deprecations.
=> Release: v0.10.0

docs/source/developer_guides/lora.md
=> FIX / Docs: Fix doc link for layer replication

.github/workflows/nightly-bnb.yml
The channel name has changed
cc @Titus-von-Koeller @BenjaminBossan @pacman100
=> FIX: Send results to correct channel

tests/test_gpu_examples.py
As per title and discussed offline, let's skip the awq tests until: https://github.com/casper-hansen/AutoAWQ/issues/466 gets resolved
=> TST: Skiping AWQ tests for now ..

.github/workflows/build_documentation.yml, .github/workflows/build_pr_documentation.yml
Same as in:
https://github.com/huggingface/transformers/blob/c712d05aa8fc8ba3ebe465079bd377d2dc9c2e07/.github/workflows/build_documentation.yml#L19
=> FIX Use different doc builder docker image

.github/workflows/torch_compile_tests.yml
Also, remove outdated comment.
=> TST Install bitsandbytes for compile tests

src/peft/tuners/tuners_utils.py
This PR fixes a BaseTuner class documentation typo
=> Fix a documentation typo

src/peft/tuners/lora/layer.py
=> DOC FIX Comment about init of LoRA Embedding

.github/workflows/nightly-bnb.yml
Trying to test if this step is causing CI to halt/fail.
=> CI Testing: Remove import check

docs/source/conceptual_guides/prompting.md
This PR fixes multitask prompt tuning paper link.
=> FIX multitask prompt tuning paper link

.github/ISSUE_TEMPLATE/bug-report.yml
=> Workflow: Update bug report template

docs/source/developer_guides/troubleshooting.md, setup.py, src/peft/__init__.py
Release planned for today.
Besides bumping the version, I also fixed an incorrect version indication in the docs.
=> Release v0.12.0

setup.py, src/peft/__init__.py
_Note: failing CI is unrelated and fixed in #1952_
=> Bump version to 0.12.1.dev0

.github/workflows/nightly-bnb.yml
Fix copy-paste error that results in a test being reported as failing when it's not. I think this should finally work :)
=> FIX CI Correctly report outcome of bnb import test

.github/workflows/stale.yml
PR #2061 only gave permission for issues.
=> MAINT: Give stale bot permissions for PRs too

src/peft/tuners/boft/config.py, src/peft/tuners/fourierft/config.py, src/peft/tuners/hra/config.py, src/peft/tuners/loha/config.py, src/peft/tuners/lokr/config.py, src/peft/tuners/lora/config.py, src/peft/tuners/oft/config.py, src/peft/tuners/vblora/config.py, src/peft/tuners/vera/config.py
Addresses part of #2155.
Also fix type annotations where appropriate.
=> DOC: Improve docs for layers_pattern argument

src/peft/tuners/tuners_utils.py
Hi @BenjaminBossan Ive reopened with another PR.
This tries to add some verbose message when users pass layers_to_transform and layers_pattern addressing point 3 in https://github.com/huggingface/peft/issues/2155.
=> Improving error message when users pass layers_to_transform and layers_pattern

docs/source/developer_guides/troubleshooting.md
See #2171
Adding this example may make it easier for users to find the issue if they encounter it.
=> DOC: Extend modules_to_save doc with pooler example

src/peft/import_utils.py
Under some unknown circumstances, it can happen that even though `importlib.util.find_spec("torchao") is not None`, `importlib_metadata.version("torchao")` still fails. This error is now caught, same as in [diffusers](https://github.com/huggingface/diffusers/blob/9f06a0d1a4a998ac6a463c5be728c892f95320a8/src/diffusers/utils/import_utils.py#L351-L357). The error was noticed in the [diffusers CI](https://github.com/huggingface/diffusers/actions/runs/12700836694/job/35404283533#step:7:313).
This is basically a revert of #2226. That PR had to add a check to the EETQ import as EETQ was broken for some time with latest transformers (see https://github.com/NetEase-FuXi/EETQ/issues/34 for context) but that has been fixed.
=> FIX: Package checks for torchao, EETQ

src/peft/config.py, tests/test_config.py
Print required keys to help w/ troubleshooting
=> Improve invalid peft config error message

docs/source/conceptual_guides/oft.md
=> DOC Fix links to boft

src/peft/utils/hotswap.py, tests/test_initialization.py
Users may actually want to call `prepare_model_for_compiled_hotswap` with a compiled model, even though that leads to recompilation. To allow this, we give the option to only warn, or even ignore, this fact when we detect the model to be compiled. By default, we still error.
=> ENH Make hotswap error on compile optional

src/peft/utils/integrations.py, src/peft/utils/loftq_utils.py, tests/bnb/test_bnb_regression.py, tests/test_common_gpu.py, tests/test_gpu_examples.py, tests/test_loraplus.py, tests/test_tuners_utils.py, tests/test_vblora.py
All tests passed expect some tests that also fail on CUDA.
=> [tests] enable BNB tests on XPU

src/peft/config.py, src/peft/utils/save_and_load.py
=> MNT: Update HF Hub download kwargs

setup.py, src/peft/__init__.py, src/peft/peft_model.py, src/peft/utils/other.py, tests/testing_common.py
This change represents the fixing part without tests and their complications to be merged as fix for #2477 and to be released as patch 0.15.2.
=> Breakout fix of #2481 for #2477, patch release prep

tests/bnb/test_bnb_regression.py
Hi @BenjaminBossan . I just found an typo in #2473 . We should skip the test if not cuda available.
=> fix typo for skipping test

.github/workflows/build_docker_images.yml, .github/workflows/nightly-bnb.yml, .github/workflows/test-docker-build.yml, .github/workflows/tests-main.yml, .github/workflows/trufflehog.yml
Solves the [Zizmor errors](https://github.com/huggingface/peft/actions/runs/14705977787/job/41266448023).
=> MNT: Pin GitHub action hashes for security

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, README.md, docs/source/developer_guides/contributing.md
- Use a more up to date example code in the README
- A section on transformers integration
- Update devs to tag
- Simplify issue template (did not seem useful in practice)
- Update contribution guideline
=> DOC Update README, contributing.md, GH templates

setup.py, src/peft/__init__.py, tests/test_custom_models.py, tests/test_gpu_examples.py, tests/test_target_parameters.py
- Bump versions
- Fix a few TODO comments
- A bit of clean up in test_target_paramters.py
=> Release 0.17.0

examples/pissa_finetuning/pissa_finetuning.py, examples/pissa_finetuning/preprocess.py
@BenjaminBossan, pls help review, thx very much
=> validated PISSA on xpu, pass

examples/miss_finetuning/README.md, examples/miss_finetuning/miss_finetuning.py
@BenjaminBossan, pls help review, thx very much
=> validated MISS on xpu, pass

examples/multilayer_perceptron/multilayer_perceptron_lora.ipynb
@BenjaminBossan , pls help review, thx very much.
=> verified mlp on xpu, pass

examples/poly/peft_poly_seq2seq_with_generate.ipynb, src/peft/peft_model.py
@BenjaminBossan, pls help review, thx very much
=> validated POLY on XPU, pass

examples/stable_diffusion/train_dreambooth.py
@BenjaminBossan , pls help review, thx very much.
=> enable sd example on xpu, pass

src/peft/tuners/_buffer_dict.py
@BenjaminBossan , pls help review, thx very much.
=> extend device_str to support other devices other than cuda

method_comparison/text_generation_benchmark/run.py, method_comparison/text_generation_benchmark/run_base.py, method_comparison/text_generation_benchmark/utils.py
@BenjaminBossan, pls help review, thx very much.
=> extend text-generation-benchmark to xpu, pass

src/peft/tuners/lora/layer.py
This PR + the fix of HF tensor parallel at (https://github.com/huggingface/transformers/pull/40162) will enable lora to be used along with TP. Example of scripts: https://github.com/huggingface/gpt-oss-recipes/pull/24
=> enable TP with lora adapter
