- README.md
- setup.py
- src/peft/__init__.py
- src/peft/tuners/lora.py
1. Minor updates/fixes in README.md and setup.py
2. Make `loralib` optional. When using LoRA, if `loralib` isn't installed, following error will be raised:
```bash
ImportError: LoRA requires `loralib` to be installed. Please run `pip install loralib`.
```
> fixes and addressing comments from previous PR

- src/peft/mapping.py
- src/peft/peft_model.py
- src/peft/tuners/lora.py
1. Add `modules_to_save` to LoraConfig
2. Using PeftModel for LoraConfig instead of task-specific classes because LoRA is task agnostic.
3. Fixes: #48
> add `modules_to_save` to LoraConfig and other fixes

- setup.py
- src/peft/tuners/lora.py
1. Makes `bnb` optional as it is currently required only with LoRA PEFT methods and to avoid issues like #79
> making `bnb` optional

- src/peft/utils/other.py
1. make gradient checkpointing optional when using PEFT+INT8. This is useful for RLHF wherein `model.generate` is part of the train loop which requires `use_cache` for faster generations. `use_cache` isn't compatible with gradient_checkpointing and this provides a way to speed up the training loop when sequence lengths are not that long
2. Fixes: #130
> fixes `prepare_for_int8_training`

- src/peft/peft_model.py
Fix for #139, output now shows 
```
trainable params: 3670016 || all params: 6054552800 || trainable%: 0.060615806339982696
```
for GPT-J
> fix: count params when zero init'd

- MANIFEST.in
- Makefile
- pyproject.toml
- setup.cfg
- setup.py
Changes proposed by this PR can be summarized as follows:
* Move LICENSE file inclusion to `setup.py` by adding a `license_files` argument to `setup()`. [Source](https://stackoverflow.com/a/66443941/14081966), thereby eliminating the purpose of `MANIFEST.in`
* Move `isort` and `pytest` configuration to `pyproject.toml`. 
Follow up suggestions, `pyproject.toml` is the new standard for python packaging, would recommend moving all packaging related metadata to `pyproject.toml`. It eliminates the need for updating version's explicitly using the `flit` backend instead of `setuptools` and also allows for placing all metadata within one single file. (for the sad exception of `flake8` which doesn't support `pyproject.toml` as of now)
> chore: update `pyproject.toml`

- src/peft/peft_model.py
- src/peft/utils/config.py
This adds options for seq2seqlm to use only encoder prompts.
current behaviour is having prompts for both encoder and decoder for prompt tuning.
@pacman100
> support option for encoder only prompts

- src/peft/peft_model.py
replace `base_model.prepare_inputs_for_generation` and `base_model._prepare_encoder_decoder_kwargs_for_generation temporarily` as described in #169
> Replace base_model's function temporarily

- README.md
- src/peft/mapping.py
Can be merged after https://github.com/huggingface/transformers/pull/21955
> Support for LLaMA models

- src/peft/tuners/lora.py
This PR fixes `peft` + LoRA multi-gpu issue, to reproduce, run: 
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"
import torch
import torch.nn as nn
import bitsandbytes as bnb
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM
free_in_GB = int(torch.cuda.mem_get_info()[0]/1024**3)
max_memory = f'{free_in_GB-2}GB'
n_gpus = torch.cuda.device_count()
max_memory = {i: max_memory for i in range(n_gpus)}
model = AutoModelForCausalLM.from_pretrained(
"facebook/opt-350m", 
device_map='auto',
max_memory=max_memory
)
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-6.7b")
print(model)
for param in model.parameters():
param.requires_grad = False  # freeze the model - train adapters later
if param.ndim == 1:
param.data = param.data.to(torch.float32) …
```
> [`core`] Fix peft multi-gpu issue

- src/peft/peft_model.py
Hi @pacman100 
Causal LM generation with prefix tuning fails for GPT2 models. This is due to mismatch in size in input_ids and position_ids (which GPT2 model creates on the fly). This, PR fixes it. Please have a look.
Minimal code to reproduce the issue:
```python
import torch
from peft import PrefixTuningConfig, TaskType, get_peft_model
model_name_or_path = "gpt2"
peft_config = PrefixTuningConfig(task_type=TaskType.CAUSAL_LM, num_virtual_tokens=3)
model = AutoModelForCausalLM.from_pretrained(model_name_or_path)
model = get_peft_model(model, peft_config)
inputs = {
'input_ids': torch.tensor([1, 2]).unsqueeze(0),
'attention_mask': torch.tensor([1, 1]).unsqueeze(0),
}
outputs = model.generate(
**inputs, max_new_tokens=20, eos_token_id=3
) …
```
> Causal LM generation fix for prefix tuning: GPT2 model

- Makefile
- src/peft/peft_model.py
- tests/test_peft_model.py
- tests/testing_common.py
This PR adds more tests to extensively test the library
> [`CI`] Add more ci tests

- src/peft/utils/config.py
When a ValueError is raised, `Can't find config.json at '{pretrained_model_name_or_path}'` is shown, but the filename is not always `config.json`, it's defined at the `CONFIG_NAME` variable.
> Show CONFIG_NAME instead of "config.json"

- src/peft/peft_model.py
Fixes https://github.com/huggingface/peft/issues/136
Fixes https://github.com/huggingface/peft/issues/225
Inside `PeftModel`, the kwargs relative to cpu/disk offloading were missing
cc @pacman100
> [`core`] Fix offload issue

- .github/workflows/stale.yml
- scripts/stale.py
This PR adds a stale bot to automatically close issues / PRs that are stale. I believe they are many ways to introduce stale bots (can be also done through actions), but decided to follow the same approach as in transformers. 
This introduces a script, `stale.py`, that will check for issues and PRs that have at least 23 days of inactivity. If that's the case, the bot will first post a message on the corresponding issue / PR and will close it on the next week if no one responds to that issue. 
From my understanding the check will be performed each 15 days from the line `cron 0 15 * * *`. 
cc @pacman100 and @ydshieh @sgugger 💯 for visibility / double checking 🙏
> [`Automation`] Add stale bot

- src/peft/peft_model.py
It should be "offload_folder" instead of "offload_dir".
Fixes https://github.com/huggingface/accelerate/issues/1281
> Fixing a bug where a wrong parameter name is used for the offload_folder

- examples/causal_language_modeling/peft_lora_clm_accelerate_ds_zero3_offload.py
> Fix typo in examples/causal_language_modeling/peft_lora_clm_accelerate_ds_zero3_offload.py

- src/peft/peft_model.py
- src/peft/tuners/adalora.py
- src/peft/tuners/lora.py
> fix trainable params setting

- examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py
Otherwise the assert at L259 breaks. It's also the thing to do to get more accurate metrics.
> Change gather for gather_for_metrics in eval.

- src/peft/tuners/lora.py
- src/peft/utils/__init__.py
1. Fixes `merge_and_unload` when having additional trainable modules as part of `modules_to_save`. For example, the `classifier`\`score` head for `AutoModelForSequenceClassification`
> Fix `merge_and_unload` when having additional trainable modules

- examples/causal_language_modeling/peft_lora_clm_accelerate_ds_zero3_offload.py
Similar to the fix in (#296 ), we utilize gather_for_metrics instead of gather which should fix the assertion error on line 309 when running with multiple processes.
> Fix eval for causal language modeling example

- src/peft/peft_model.py
- tests/testing_common.py
1. Currently, `modules_to_save` aren't working when using LoRA. This PR fixes it. https://github.com/huggingface/peft/issues/341#issuecomment-1516013491
> fix lora modules_to_save issue

- docs/source/_toctree.yml
- docs/source/conceptual_guides/lora.mdx
New doc for PEFT: a brief introduction to LoRA technique (a TLDR) with links to examples.
> [docs] LoRA conceptual guide

- src/peft/__init__.py
- src/peft/mapping.py
- src/peft/peft_model.py
- src/peft/tuners/__init__.py
- src/peft/tuners/adaption_prompt.py
- src/peft/utils/config.py
- src/peft/utils/save_and_load.py
- tests/test_adaption_prompt.py
- tests/test_config.py
Issue #235 
Paper: https://arxiv.org/abs/2303.16199
Official Implementation: https://github.com/ZrrSkywalker/LLaMA-Adapter
This implementation is quite specific to Llama although in principle the same technique can be used for other transformer models. It is implemented by replacing some of the `LlamaAttention` modules with `AdaptedAttention` modules that wrap the original ones, but bypass the original `forward()` so that we can inject trainable tokens and a gate. I can add a notebook example in a subsequent PR when I have the time.
> Implement adaption prompt from Llama-Adapter paper

- .github/workflows/nightly.yml
- Makefile
- scripts/log_reports.py
This PR adds the workflow to run slow tests
> [`tests`] add slow tests to GH workflow

- docs/source/index.mdx
As a suggestion, this PR moves the tables listing supported models to the index page since the supported methods are also listed there. 
In addition, this PR adds links to the quicktour and conceptual guides to help beginners navigate the docs.
> [docs] Supported models tables

- docs/source/_toctree.yml
- docs/source/accelerate/deepspeed-zero3-offload.mdx
- docs/source/accelerate/fsdp.mdx
This PR explores what a separate section for the Accelerate integrations (DeepSpeed + FSDP) could look like. The main parts I wanted to focus on are:
- generalize the DeepSpeed script a bit more so users can configure it with other settings besides ZeRO-3/Offload
- parts of the script users can customize if they want to use a different model, dataset, or PEFT method
- highlight and briefly explain what the Accelerate parts are doing
~If we think this makes sense, I'll also do the FSDP script~ done :)
> [WIP-docs] Accelerate scripts

- docs/source/quicktour.mdx
This PR updates the quicktour a bit to summarize the most important things about the library:
- adds some more context about why 🤗 PEFT is important and what it is since this may be a user's first introduction to it
- reorganizes the sections into `PeftConfig` and `PeftModel` since these are two important components of the library; once users get this pattern down, they should be able to use any PEFT method they want
- removed the 🤗 Accelerate inference section since it just links to another example
- removed the model support matrix, I think we can move this somewhere else (maybe the reference section?)
- also removed the Caveats section about FSDP because this seems like something we can dedicate a separate page to. Maybe in a new section called Accelerate guides?
Let me know if I've …
> [docs] Quicktour update

- src/peft/tuners/lora.py
1. Added nn.Embedding to the Lora Fine-tuning support Layer.
2. Added a gpt-j Fine-tuning example with nn.Embedding Layer and 8-bit quantization using PEFT in lora.py.
This pull request includes the following changes:
1. **Added nn.Embedding to Lora Fine-tuning support Layer**: With this update, the Lora Fine-tuning layer now supports nn.Embedding, allowing for better performance and efficiency during the fine-tuning process.
2. **GPT-J Fine-tuning example with nn.Embedding Layer and 8-bit quantization using PEFT in lora.py**: To demonstrate the usage of GPT-J with Lora, we've added an example in the lora.py file. This example showcases fine-tuning GPT-J using nn.Embedding Layer and 8-bit quantization with the help of PEFT. This provides users with an efficient method for optimizing their …
> Add nn.Embedding Support to Lora

- src/peft/tuners/adalora.py
`transpose() missing 1 required positional argument: 'fan_in_fan_out'`
> Fix missing arg for transpose in AdaLora

- docs/source/task_guides/int8-asr.mdx
- examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb
- examples/int8_training/Finetune_opt_bnb_peft.ipynb
- examples/int8_training/peft_adalora_whisper_large_training.py
- examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb
- src/peft/utils/other.py
- tests/test_gpu_examples.py
1. Fixes following issues with INT8 training:
a. When making modules trainable via `modules_to_save`, it was resulting in loss being `NaN` or `0` because those params are in fp16/bf16 which are unstable for training, in comparison trainable lora params are in FP32.
b. half and float mismatches because certain layernorm were being converted in to FP32 and when making other trainable modules to be in FP32 manually, it was leading to mismatches as frozen layers were in half prescision and few in full precision.
> fix INT8 prepare function

- .github/workflows/tests.yml
- setup.py
This PR pins the `urllib3` version to avoid failing CI tests due to a release of `requests-toolbelt` and `urllib3`
Should resolve all failing CI tests on the PRs
cc @pacman100
> [`CI`] Fix CI - pin urlib

- docs/source/index.mdx
Fixes documentation links from being absolute links to relative links for conceptual guides. Links currently show as 404 on the live site.
> Fix documentation links on index page

- README.md
after testing with new deepspeed pr, Zero 3 init issue had been fixed by https://github.com/microsoft/DeepSpeed/pull/3413
> Zero 3 init ReadME update

- src/peft/__init__.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
With the addition of 4bit quantization support, the method `prepare_model_for_int8_training` should be renamed to `prepare_model_for_kbit_training` as it also prepares the 4bit models. I propose to add a warning whenever a user uses `prepare_model_for_int8_training` suggesting them to use `prepare_model_for_kbit_training` and remove `prepare_model_for_int8_training` in a major version release.
cc @pacman100 @sgugger
> [`core`] Raise warning on using `prepare_model_for_int8_training`

- examples/token_classification/peft_lora_token_cls.ipynb
- src/peft/peft_model.py
- src/peft/tuners/adalora.py
- src/peft/tuners/lora.py
`merge_weights` is not used anywhere since #227, which introduced `merge_and_unload`.
> Remove merge_weights

- src/peft/tuners/lora.py
It's a very tiny change. I changed comment in tuners.lora; lora_alpha type float to int.
> change comment in tuners.lora, lora_alpha float to int

- src/peft/peft_model.py
- src/peft/utils/config.py
- tests/test_config.py
This PR enables the `from_pretrained` of `PeftConfig` and `PeftModel` to load configs/models with a specific `revision` arg. This is useful when storing many adapter weights as branches in a model repo.
```python
from peft import PeftConfig, PeftModel
model_id = "lewtun/tiny-random-OPTForCausalLM-delta"
revision = "v1"
config = PeftConfig.from_pretrained(model_id, revision=revision)
model = AutoModelForCausalLM.from_pretrained(
config.base_model_name_or_path,
)
model = PeftModel.from_pretrained(model, model_id, revision=revision)
assert isinstance(model, PeftModel)
```
> Enable PeftConfig & PeftModel to load from revision

- src/peft/tuners/lora.py
This is a proposed fix for the crash reported in https://github.com/huggingface/peft/issues/436.
This PR makes a minor change to the implementation of `merge_and_unload` so it can handle `nn.Embedding` modules as well.
> fix merge_and_unload when LoRA targets embedding layer

- src/peft/peft_model.py
- src/peft/utils/save_and_load.py
some function need load_result when call load_adapter function to check non-matching keys.
> return load_result when load_adapter

- src/peft/mapping.py
A one-line fix to address a bug where the variable `token_dim` can be used when not assigned.
In particular, performing prompt tuning with a non default `token_dim` causes peft to crash.
To illustrate this change, in [this example notebook](https://github.com/huggingface/peft/blob/main/examples/sequence_classification/Prompt_Tuning.ipynb), changing `PromptTuningConfig(task_type="SEQ_CLS", num_virtual_tokens=10)` to `PromptTuningConfig(task_type="SEQ_CLS", num_virtual_tokens=10, token_dim=x)` raises a `Local Variable Referenced Before Assignment Error`, this PR fixes this issue.
> Fix a minor typo where a non-default token_dim would crash prompt tuning

- src/peft/peft_model.py
The tiniest of suggestions, but to improve readability a thousands separator can be useful. Before:
trainable params: 901120 || all params: 479563456 || trainable%: 0.18790422596337283
After:
trainable params: 901,120 || all params: 479,563,456 || trainable%: 0.18790422596337283
> Add thousands separator in print_trainable_parameters

- src/peft/tuners/lora.py
Thank you for creating this great library!
As I was exploring LoRA implementations and reviewing the code, I noticed that there could be some enhancements made to improve code readability. 
Therefore, I created this pull request which primarily focuses on extracting certain private functions without introduce any functional changes.
> improve readability of LoRA code

- setup.py
- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/hub_utils.py
- src/peft/utils/other.py
- tests/test_common_gpu.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
This PR integrates safetensors into peft
The logic now is as follows:
- When saving locally a model, by default save the pickle file.
- If a user wants to go for a safer serialization (recommended), users should pass `safe_serialization=True` to `save_pretrained` method
- Same logic applies for `push_to_hub` method, by default we push on the Hub pickle file, except if a user calls `safe_serialization=True` to that method. 
- Inside from_pretrained, first look if the safetensors weights are present locally, then check for the pickle file. If none of them are present locally, try to fetch the safetensors weights from remote Hub, if not try to fetch the pickle file for remote.
What do you think? 
An example of safetensors adapter weights on the Hub: …
> [`core`] Add safetensors integration

- src/peft/mapping.py
This small PR add a return type hint on `get_peft_model`. 
This makes it easier for IDE (in my case pycharm) to propose shortcuts and suggestions if it knows the type of return objet.
For instance without the type hint in pycharm I cannot click on `save_pretrained` of peft a model and see the signature. This is because pycharm don't know that the object is a peft model. Return type hint fixed this
> feat: add type hint to `get_peft_model`

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
This PR adds issues template, highly insipred from transformers
added a bug report template and a feature request template
I added @pacman100 myself and @sayakpaul for questions related with the lib, and added @stevhliu & @MKhalusova for documentation related issues. Let me know if that sounds good to everyone
> Add issues template

- src/peft/tuners/lora.py
Instantiating and using a default LoraConfig results in errors due to the fact `lora_alpha` and `lora_dropout` gets initialised to None. 
There are points in the code (see e.g., [here](https://github.com/huggingface/peft/blob/2bb0f98619b567dccef13da3afaa6c3f535ee83c/src/peft/tuners/lora.py#L447), [here](https://github.com/huggingface/peft/blob/2bb0f98619b567dccef13da3afaa6c3f535ee83c/src/peft/tuners/lora.py#L465), [here](https://github.com/huggingface/peft/blob/2bb0f98619b567dccef13da3afaa6c3f535ee83c/src/peft/tuners/lora.py#L457)) where it is assumed they have actual values.
Since all methods already have alpha=1 and dropout=0.0 as defaults I opted to change LoraConfig instead of adding None checks.
> [BugFix] Set alpha and dropout defaults in LoraConfig

- src/peft/peft_model.py
- src/peft/utils/other.py
currently. LORA in peft does not support for mpt model which is https://huggingface.co/mosaicml/mpt-7b.
there's two reasons:
1)mpt is not in TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING. if user does not define the target module explicitly. it will fail in _prepare_lora_config.
2) the forward in https://huggingface.co/mosaicml/mpt-7b/blob/main/modeling_mpt.py#L251 does not contain imputs_embeds. we could skip imputs_embeds if it's None. If it's not None, throw assert to let user know it.
> enable lora for mpt

- .github/ISSUE_TEMPLATE/bug-report.yml
As per title, in fact we don't have Glue/Squad in the examples folder
cc @pacman100
> Fix minor typo in bug-report.yml

- src/peft/peft_model.py
- src/peft/utils/config.py
- tests/test_config.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
Before this PR we were blindly passing the kwargs all over the place, for example the snippet below would fail:
- This PR adds new class methods `_get_peft_type` as the retrieval of the PEFT type is used and call over multiple places
- Adds a `_split_kwargs` methods inside `PeftModel` to filter out kwargs that are used for `hf_hub_download`
```python
import torch
from peft import PeftModel
peft_model_id = "ybelkada/test-st-lora" 
tr_model_id = "facebook/opt-350m"
model = AutoModelForCausalLM.from_pretrained(tr_model_id, torch_dtype=torch.bfloat16)
model = PeftModel.from_pretrained(model, peft_model_id, device_map="auto") # it will fail here
```
This PR fixes that by correctly filtering out the kwargs at different levels
Fixes …
> [`core`] Correctly passing the kwargs all over the place

- src/peft/tuners/lora.py
Fixes https://github.com/huggingface/peft/issues/581
In fact the device placement of the adalora layer needs to take into account the `ranknum` module. To reproduce: 
```python
from peft import get_peft_model, AdaLoraConfig, TaskType
import transformers
model_id = "facebook/opt-350m"
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", load_in_4bit=True)
tokenizer = transformers.AutoTokenizer.from_pretrained(model_id)
adaloraconfig = AdaLoraConfig(
task_type=TaskType.CAUSAL_LM,
init_r=6,
target_r=4,
tinit=50,
tfinal=100,
deltaT=5,
beta1=0.3,
beta2=0.3,
orth_reg_weight=0.2,
lora_alpha=32,
lora_dropout=0.05,
bias="none",
)
model = get_peft_model(model, adaloraconfig) …
```
> Fix adalora device mismatch issue

- src/peft/peft_model.py
Fix typo on description:
- `imputs_embeds` to `inputs_embeds`
> Fix typo at peft_model.py

- src/peft/utils/other.py
- tests/test_decoder_models.py
This PR adds Llama and Starcoder (GPTBigCode) to the set of Ci suite. Currently generate with prefix tuning seems to be not supported for Starcoder model as it is a MQA model and the past key values needs a special care and further investigation. 
I propose to skip the tests for now until we address a proper fix in the future
cc @pacman100
> [`test`] Adds more CI tests

- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
1. Adds `peft` library tag
2. Adds peft version
3. Adds quantization information if it was used
Code:
```
trainer.push_to_hub()
trainer.model.push_to_hub(trainer.repo.local_dir)
```
Sample Output:
model: https://huggingface.co/smangrul/results
```
---
license: apache-2.0
tags:
- generated_from_trainer
model-index:
- name: results
results: []
library_name: peft
---
This model is a fine-tuned version of [tiiuae/falcon-7b](https://huggingface.co/tiiuae/falcon-7b) on an unknown dataset.
More information needed
More information needed
More information needed
The following `bitsandbytes` quantization config was used during training:
- load_in_8bit: False
- load_in_4bit: True
- llm_int8_threshold: 6.0
- llm_int8_skip_modules: None
- llm_int8_enable_fp32_cpu_offload: False
- …
```
> Improve the README when using PEFT

- .github/workflows/build_docker_images.yml
- docker/peft-cpu/Dockerfile
- docker/peft-gpu/Dockerfile
- scripts/log_reports.py
This PR fixes the failing Dockerfile build workflows and . The GPU images were not pushed because of no space left on device issues and circumvents silent bugs that I have encountered when monitoring runs. To mitigate the first issue it is important to clean the disk of the CI runners before creating. For the second issue I display a different message when the logs are empty or if there are no log file.
Currently 2 slow tests are failing, will fix them in a follow up PR
> [`tests`] Fix dockerfile

- src/peft/mapping.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
Fixes https://github.com/huggingface/peft/issues/597
We should add the possibility to users to pass the adapter name when calling `get_peft_model` for a smoother UX
Added also some nice CI tests
cc @pacman100
> [`core`] Add `adapter_name` in `get_peft_model`

- src/peft/import_utils.py
Fixes: https://github.com/huggingface/peft/issues/603 
Instead of checking the version of bnb we should introduce a stronger check to make sure the 4bit layers cannot be imported to avoid corner cases such as the one described on the issue
cc @pacman100
> [`core`] Stronger import of bnb

- examples/lora_dreambooth/convert_kohya_ss_sd_lora_to_peft.py
- examples/lora_dreambooth/convert_peft_sd_lora_to_kohya_ss.py
Hi!
This pull request introduces the following changes:
- Adds the ability to convert [Civitai](https://civitai.com/) LoRAs to be used in PEFT (through kohya_ss conversion script)
- Adds the ability to convert PEFT LoRAs to safetensors format to be used in [webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
> Added Civitai LoRAs conversion to PEFT, PEFT LoRAs conversion to webui

- src/peft/tuners/adaption_prompt.py
- tests/test_common_gpu.py
Fixes: https://github.com/huggingface/peft/issues/600
As per title, this PR adds 8bit + 4bit support for `AdaptionPrompt` models. The fix is to infer the correct dtype by excluding the case where the weights are either an `torch.int8` (used in 8bit layers) or `torch.uint8` (used in 4bit layers) 
Adds also slow tests to test everything works correctly.
cc @pacman100
> [`AdaptionPrompt`] Add 8bit + 4bit support for adaption prompt

- src/peft/peft_model.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>
> feat(model): Allow from_pretrained to accept PeftConfig class

- src/peft/peft_model.py
According to the init method, `self.peft_config` is always a dict. It'll be something like `{"default": PeftConfig Instance}`.
https://github.com/huggingface/peft/blob/f5352f08c593503a442f4438e1c7e648377b6a4b/src/peft/peft_model.py#L97-L113
Therefore, existing `disable_adapter` method is checking the wrong item. It should check `self.peft_config["default"]` instead of `self.peft_config`
https://github.com/huggingface/peft/blob/f5352f08c593503a442f4438e1c7e648377b6a4b/src/peft/peft_model.py#L366-L381
> Fix `PeftModel.disable_adapter`

- src/peft/tuners/adalora.py
Otherwise there is an exception when importing peft with an olds version of bitsandbyte.
Fixes #642
> bitsandbytes version check

- docs/source/task_guides/clm-prompt-tuning.mdx
- docs/source/task_guides/image_classification_lora.mdx
- docs/source/task_guides/semantic_segmentation_lora.mdx
- docs/source/task_guides/seq2seq-prefix-tuning.mdx
- examples/causal_language_modeling/requirements.txt
- examples/conditional_generation/requirements.txt
- examples/image_classification/image_classification_peft_lora.ipynb
- examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb
- examples/int8_training/Finetune_opt_bnb_peft.ipynb
- examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb
- examples/lora_dreambooth/requirements.txt
- examples/semantic_segmentation/semantic_segmentation_peft_lora.ipynb
- examples/sequence_classification/requirements.txt
- examples/token_classification/requirements.txt
- As discussed, `loralib` is no longer required, so the examples from the docs have been updated to no longer require `loralib` as dependencies
- In one example, a missing `torch` import was added
- In another example, a missing line was added (output of that line is shown, but not the line itself)
Note: Some diffs that GH shows look spurious to me, as there was no change there. Not sure what is going on.
> DOC: Remove loralib requirements from examples, a few small fixes

- .github/workflows/tests.yml
- pyproject.toml
- setup.py
As discussed, this adds line coverage to the tests. This will allow us to identify parts of the code that are missing coverage and make it easier to ensure newly added code is well covered.
At the moment, CI is not set up to report if new, uncovered code is being added. We could add codecov to the CI to get this functionality, but having 100% coverage for new code is not always desired, so it's debatable if it is needed.
Right now, there are multiple test commands (normal, single, multi GPU). For each individual command, the coverage report would only include the lines covered by that command, so the total coverage would be underreported. It is possible to [combine multiple coverage reports into a single report](https://coverage.readthedocs.io/en/stable/cmd.html#cmd-combine). However, I'm …
> Add pytest-cov for reporting test coverage

- docs/source/install.mdx
- setup.py
I would suggest to drop support for Python 3.7. It is end-of-life since yesterday and wasn't tested in CI anyway. If you feel like we should not require 3.8+, feel free to close the PR.
Again, the diff view from GH shows spurious changes. Seems to be an issue with mdx?
> Require Python version >= 3.8

- src/peft/tuners/lora.py
- tests/test_stablediffusion.py
Hi!
Currently adding a weighted adapter rewrites base lora alpha value like this:
```python
import torch
from diffusers import StableDiffusionPipeline
from peft import get_peft_model
from peft.tuners.lora import LoraConfig
pipe = StableDiffusionPipeline.from_pretrained(
"runwayml/stable-diffusion-v1-5",
torch_dtype=torch.float16
).to("cuda")
config = LoraConfig(
r=8,
lora_alpha=32,
target_modules=["to_q"]
)
pipe.unet = get_peft_model(pipe.unet, config)
print(pipe.unet.peft_config)
pipe.unet.add_weighted_adapter(["default"], [0.5], "default_05")
print(pipe.unet.peft_config)
```
This PR just fixes this small issue.
@pacman100 your review is kindly appreciated.
> Fixed LoraConfig alpha modification on add_weighted_adapter

- src/peft/utils/config.py
- tests/test_config.py
Resolves #424
The bug was caused by `__dict__` being overwritten to return a copy of the `dataclass` as dict. This can lead to unpredictable behavior, as shown in the issue. This fix removes the `__dict__` property and preservers the original behavior where needed.
All three added tests would fail without the fix.
> FIX: bug resulting in config copies not working

- src/peft/utils/other.py
This pull request aims to enhance the `COMMON_LAYERS_PATTERN` in order to support RoBERTa's `layers_transform` feature. Currently, the key format for RoBERTa layers is as follows: `roberta.encoder.layer.0.attention.self.query`. By adding the term 'layer' to the `COMMON_LAYERS_PATTERN`, we ensure compatibility and enable the transformation of RoBERTa layers.
- Updated the `COMMON_LAYERS_PATTERN` by including the term 'layer' to accommodate RoBERTa's key format.
> Adding support for RoBERTa layers_transform in COMMON_LAYERS_PATTERN

- tests/test_encoder_decoder_models.py
(as discussed internally)
The `generate` tests so far were skipped for non-lora, non-prefix tuning cases. However, those cases are now passing, so it is no longer necessary to skip the tests.
> TST: Remove skipping certain tests

- src/peft/tuners/lora.py
As discussed internally.
When `init_lora_weights=False`, embedding LoRA weights were initialized as all zeros, resulting in LoRA becoming an identity transform. This is inconsistent with other module types, where `init_lora_weights=False` results in random initialization and thus a non-identity operation.
As `init_lora_weights=False` is just for internal testing, users should not be affected by this change. In fact, I updated the doc of this parameter to - hopefully - better reflect this.
There is no direct test for this change. However, there are tests in #676 that will fail without this fix, so it is tested indirectly.
> FIX: Embedding LoRA weights are initialized randomly

- docker/peft-gpu/Dockerfile
The new release of bitsandbytes dropped the support for CUDA 11.2 and 11.6: https://github.com/TimDettmers/bitsandbytes/commit/ae7cd6ad147e67c3d5c4a681ef573c92fc5dd9de 
The nightly runner having cuda 11.6 installed as discussed internally let's use the cuda11.3 image on our docker images 
cc @BenjaminBossan @pacman100 
Can confirm the import of bitsandbytes works at least as expected with this new image
> Fix broken docker images

- src/peft/peft_model.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
When using prefix-tuning and enabling `model.half()` after init like this, the adapter will not be converted to the right type:
```
model = get_peft_model(model, peft_config)
model.half()
```
So, we'd better make `self.base_model_torch_dtype` as a property so the conversion can be done in the right way.
Further fixes on #520 .
> Fix base_model_torch_dtype when using model.half() after init

- src/peft/tuners/ia3.py
_As discussed internally_
Right now, no matter what the value of `init_ia3_weights`, these weights are always initialized to be 1 (i.e. identity transforms). With this fix, when `init_ia3_weights=False`, the weights are initialized randomly. This is a setting mostly used for testing, so this fix has no user impact.
Note: No test being added here, as this will be tested in #683
> Init IA³ weights randomly when so configured

- README.md
Minor updates to the README to include $(IA)^3$. For models supported, I've only included models I've tested for the given task, so this is likely to be conservative! Have also updated the backlog, looks like Adaption prompt and $(IA)^3$ can be safely marked as completed!
cc @pacman100 @younesbelkada
> Update Readme to include IA3

- docs/source/task_guides/int8-asr.mdx
Having `bias="None"` in `LoraConfig` raised a `NotImplementedError`. Replaced it with `bias="none"` as per the [`LoraConfig` reference](https://huggingface.co/docs/peft/main/en/package_reference/tuners#peft.LoraConfig) and now the code works, I can run training.
> Fix code typo in int8-asr.mdx

- src/peft/mapping.py
- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
- tests/test_adaption_prompt.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_feature_extraction_models.py
- tests/testing_common.py
Fixes https://github.com/huggingface/peft/issues/699
This PR enables users to save selected adapters for all supported PEFT models.
The current API is as follows:
```python
peft_model.save_pretrained(dir, selected_adapters=["default", "adapter_1"])
```
Of course, this PR is totally backward compatible, is `selected_adapters` is not passed, it will select all available adapters by default.
> [`Feature`] Save only selected adapters for LoRA

- src/peft/peft_model.py
- src/peft/utils/config.py
Currently the Hub kwargs are not correctly managed if one passes explicit key word arguments to `PeftModel.from_pretrained` the model loading fails. This is because some key word arguments are duplicated across the `hf_hub_download` method and the current kwargs that are passed.
in this PR, I propose to refactor things a bit and make a better kwargs managed of hub-related methods. Note that some arguments such as `use_auth_token` are not in the `hf_hub_download` signature, thus needs a special care for handling them.
Encountered this issue while working on https://github.com/huggingface/transformers/pull/24827
> [`core`] Better hub kwargs management

- src/peft/peft_model.py
- tests/test_hub_features.py
Fixes https://github.com/huggingface/peft/issues/718
in the PR #712 , I forgot to properly deal with `subfolder` argument, in fact they will appear in `hf_hub_download_kwargs` as `subfolder` is in the signature of `hf_hub_download` method
cc @pacman100 @BenjaminBossan 
Added also a nice CI test
> Fix subfolder issue

- src/peft/utils/other.py
as per title
@pacman100 @BenjaminBossan @abhishekkrthakur 
added also `RefinedWebModel` for backward compatiblity for models that use the first versions of Falcon. `falcon` stands for the model id of the falcon port in transformers
Note that 
- falcon 7b has the model_type termed as `RefinedWeb`: https://huggingface.co/tiiuae/falcon-7b/blob/main/config.json#L23
- falcon 40b has the model_type termed as `RefinedWebModel`: https://huggingface.co/tiiuae/falcon-40b/blob/main/config.json#L23
> Add falcon to officially supported LoRA & IA3 modules

- setup.py
This is an oversight on my end, that i forgot peft still relies on setup.py
PEP561 indicates that we need to add package_data to indicate the package is typed
See https://peps.python.org/pep-0561/#packaging-type-information
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>
> fix(pep561): include packaging type information

- src/peft/peft_model.py
Fixes #726 
This PR is on par with https://github.com/huggingface/transformers/pull/24906
Currently the TP paradigm that is supported by transformers, technically is not really a real Tensor Parallelism paradigm but rather a simulation of TP by manually splitting the layers into chunks and concatenating the results.
The motivation of that implementation is to mimic the TP paradigm that was used during pre-training of these models, as slicing weight tensors and input leads to slight numerical differences: https://github.com/pytorch/pytorch/issues/76232 
I would argue that this might be not that important for training as the model will be fine-tuned, thus the weights of the model will be adapted accordingly. 
cc @pacman100 @BenjaminBossan 
I propose to properly support TP in the future once …
> [`Llama2`] Add disabling TP behavior

- src/peft/peft_model.py
- tests/test_common_gpu.py
Currently the total number of parameters displayed by `print_trainable_parameters` is incorrect for 4bit base models. Due to the design of `Params4bit` modules, one needs to multiply the number of parameters of these modules by 2 to get the correct number of params.
Script to reproduce:
```python
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
import torch
from peft import get_peft_model, LoraConfig
model_id = "facebook/opt-125m"
bnb_config = BitsAndBytesConfig(
load_in_4bit=True,
bnb_4bit_quant_type="nf4",
bnb_4bit_compute_dtype=torch.float16,
bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config,
device_map={"":0})
peft_config = LoraConfig(
r=8,
)
model = get_peft_model(model, peft_config) …
```
> [`Patch`] patch trainable params for 4bit layers

- src/peft/tuners/p_tuning.py
- tests/test_config.py
This is low prio, just fixing an annoyance.
Right now, when the user initializes a prompt encoder with `MLP`, they get a warning that a certain argument, `encoder_num_layers`, is ignored, and there is no possible value for the argument that would stop the warning. Usually, warnings are for issues that something is (probably) going wrong, but here, everything is going as expected. Therefore, by default, I would not give this warning, thus avoiding users getting confused.
However, I would still give the warning if the user set the argument for `encoder_num_layers` explicitly to a different value. In that case, they expect the change to make a difference, but since the argument is ignored, their expectation is not met, which warrants a warning.
I didn't find a good place to put the unit …
> FIX: Warning when initializing prompt encoder

- src/peft/tuners/lora.py
- tests/test_custom_models.py
As discussed internally.
For LoRA, given that `bias='all'` or `bias='none'`, when doing inference with a model in the `disable_adapter()` context, the output will not be identical to the output of the base model. This may be surprising to users. Therefore, a warning is given. Furthermore, the docstring has been extended to reflect this fact.
> ENH: Warn when disabling adapters and bias != 'none'

- src/peft/tuners/ia3.py
- src/peft/tuners/lora.py
- src/peft/utils/other.py
- tests/test_custom_models.py
- tests/testing_common.py
Resolves #493
For LoRA and IA³, there was a bug that even even using the `disable_adapter` context, if the module was listed in `modules_to_save`, the updated weights would be used instead of the original weights. This meant that `disable_adapter` would not return the same results as the base model without adaptation. This PR fixes the issue and provides a test.
Note: I tried to adjust AdaLoRA too, since it seemed that the same reasoning should apply there. However, I think that AdaLoRA does not really support disabling adapters at all. E.g. there is no `disable_adapter_layers` method. Therefore, AdaLoRA was not changed.
> FIX: Disabling adapter works with modules_to_save

- src/peft/tuners/adalora.py
Fixes https://github.com/huggingface/peft/issues/571
As stated by @BenjaminBossan the regularization term is only computed in training mode, i.e. when `outputs.loss` is different than None
Can confirm this snippet that is not working on main 
```python
import torch
from peft import AdaLoraConfig, get_peft_model, AutoPeftModelForCausalLM
from transformers import AutoModelForCausalLM 
model_id = "facebook/opt-350m"
peft_config = AdaLoraConfig(
task_type="CAUSAL_LM"
)
model = AutoModelForCausalLM.from_pretrained(model_id)
dummy_input = torch.LongTensor([[1, 2, 3, 4, 5]])
model = get_peft_model(model, peft_config)
model.save_pretrained("test-adalora")
model = AutoPeftModelForCausalLM.from_pretrained("test-adalora")
_ = model(dummy_input)
```
Now works
Also fixes an issue when creating an …
> [`AdaLora`] Fix adalora inference issue

- src/peft/utils/other.py
- tests/test_common_gpu.py
Fixes https://github.com/huggingface/peft/issues/602 and the solution has been found out by @BenjaminBossan 
When loading the base model with accelerate, the old hooks were still attached to the new module, causing the `ModulesToSaveWrapper` module to call the previous forward method, leading to the gradients not being properly backpropagated to the right module.
A reproducible script shared by Benjamin:
```python
import torch
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoTokenizer, AutoModelForSequenceClassification, set_seed
set_seed(123)
PRETRAIN = 'bigscience/bloomz-560m'
tokenizer = AutoTokenizer.from_pretrained(PRETRAIN)
load_in_4bit=True
device_map=None
should_resize_token_embeddings=False …
```
> [`ModulesToSave`] add correct hook management for modules to save

- setup.py
- src/peft/tuners/lora.py
Adds an optional progressbar when merge_and_unloading a model to indicate to users that the code is not "hanging" but actually still doing something. The progress bar is enabled by default but can be disabled.
TQDM has been explicitly added to the requirements, although it is probably already installed as dependency of the other libraries like torch or transformers.
closes #667
> Add progressbar unload/merge

- src/peft/utils/other.py
- This PR introduces Lora and related  adapter methods into npu since Accelerate has already provided support for npu.
- Btw thanks to abhilash1910 for his outstanding contribution, it is more convenient to support third-party accelerators.
> Support Ascend NPU adapter loading

- src/peft/peft_model.py
- src/peft/tuners/adalora.py
- src/peft/tuners/ia3.py
- src/peft/tuners/lora.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
When a user tries to add a 2nd adapter, Lora and AdaLora make some checks to ensure the new adapter is compatible with existing adapters. Currently, that check is performed halfway through the method. This means that if the check fails, the new adapter is partially applied, leaving the model in a bad state. The main purpose of this PR is to ensure that the model state is correct after such a failure is encountered.
Tests were added to catch this potential bug.
While working on this, I also made the following changes:
- Previously, the `peft_config` from the `PeftModel` was passed to the base model. This meant that sometimes, the base model would hold a reference to `PeftModel.peft_config`, but not always, as some base models would create new dicts. This is problematic, because some code …
> Add adapter error handling

- src/peft/peft_model.py
1. Addresses https://github.com/huggingface/peft/issues/430#issuecomment-1666312815
2. Reword docstring to not be LoRA-specific
> DOC: Update docstring of PeftModel.from_pretrained

- src/peft/tuners/tuners_utils.py
Load the Lora model
inference_model = PeftModel.from_pretrained(inference_model, peft_model_id)
inference_model = torch.nn.DataParallel(inference_model)
inference_model.to(device)
inference_model.eval()
just the use the inference mode to inference. and the issue could be reproduce.
calltrace like
Original Traceback (most recent call last):
File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
output = module(*input, **kwargs)
File "/mnt/disk1/wangyi/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/mnt/disk3/wangyi/peft/src/peft/peft_model.py", line 720, in forward
return self.base_model(
File …
> fix crash when using torch.nn.DataParallel for LORA inference

- docker/peft-gpu/Dockerfile
- src/peft/import_utils.py
- src/peft/peft_model.py
- src/peft/tuners/adalora.py
- src/peft/tuners/ia3.py
- src/peft/tuners/lora.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
- tests/test_gpu_examples.py
- tests/testing_utils.py
This PR adds the possibility to train lora + adalora adapters on top of GPTQ quantized model. 
```py
causal_lm_model_id = "marcsun13/opt-350m-gptq-4bit"
tokenizer  = AutoTokenizer.from_pretrained(causal_lm_model_id)
model = AutoModelForCausalLM.from_pretrained(
causal_lm_model_id,
torch_dtype=torch.float16,
device_map="auto"
)
model = prepare_model_for_kbit_training(model)
config = LoraConfig(
r=16,
lora_alpha=32,
target_modules=["q_proj", "v_proj"],
lora_dropout=0.05,
bias="none",
task_type="CAUSAL_LM",
)
model = get_peft_model(model, config)
```
```py
model.cpu().save_pretrained(save_dir)
```
```py
model = AutoModelForCausalLM.from_pretrained(
causal_lm_model_id,
torch_dtype=torch.float16,
device_map="auto"
)
model = PeftModel.from_pretrained(model ,save_dir)# load saved adapters
```
> GPTQ Integration

- src/peft/tuners/lora.py
Lora can only merge parameters when the model is not quantized. However, the error-checking code does not check whether we actually want to merge anything or not.
> Only fail  quantized Lora unload when actually merging

- tests/test_custom_models.py
Prompted by #808, I added a test that shows that loading a trained custom model works as expected.
I only added this to custom models because it involves a few steps of training and I didn't want to slow down tests too much. LMK if this should be added to all tests.
In addition, I renamed some custom model tests which had strange names (probably caused by an overeager query-replace).
> TST: add test about loading custom models

- src/peft/tuners/ia3.py
Fixes an unbound error relating to local variable "result" being referenced prior to being assigned, which arises during fine-tuning using a model loaded in 8-bit, while using Flash Attention (in my case, 2.0.4) and training in BF16 or FP16.
I have no experience nor formal education in computer programming, so apologies if this is redundant or incorrect. Based on the deductive testing the unbound error was caused by loading a model in 8-bit (using Bitsandbytes 41.0) while training in BF16 or FP16 as required by Flash Attention 2. Adding these two lines fixed the unbound error and did not seem to break anything else. The added text is simply a catch-all for where the code does not execute an if-block which assigns a value to result before reaching the current line 551.
> Fix unbound error in ia3.py

- docker/peft-gpu/Dockerfile
Fixes the docker image build that is currently failing on main since the GPTQ PR
The build was failing because auto-gptq was trying to get installed before the cuda install which led to auto-gptq library throwing an error as it is not supported in non-CUDA envs. 
The fix is to simply move the install of auto-gptq after the CUDA related packages install, I have also bumped the cuda version to 11.8 
can confirm the docker build works locally with these changes
> [`Docker`] Fix gptq dockerfile

- tests/test_gpu_examples.py
As per title, in the context of https://github.com/huggingface/peft/pull/833 , I suggested we should make sure 4bit training works as expected to make sure removing `clone()` is safe. This PR adds 4bit training tests that are similar to 8bit training tests, the only difference is that we load the base model in 4bit instead of 8bit.
> [`Tests`] Add 4bit slow training tests

- README.md
- docs/source/_toctree.yml
- docs/source/developer_guides/low_level_api.mdx
- src/peft/mapping.py
- tests/test_low_level_api.py
As discussed internally, this PR adds nice documentation and simple tests about the recent low-level API from #749 
> [`Low-level-API`] Add docs about LLAPI

- docs/source/developer_guides/custom_models.mdx
> Fixed typos in custom_models.mdx

- README.md
- docs/source/_toctree.yml
- docs/source/developer_guides/contributing.mdx
As discussed internally, we would like to add a contribution guide to facilitate contributions from the community and clarify the requirements.
While looking at the README.md, I wondered if we should remove the "backlog" section, as it looks outdated.
> DOC: Add a contribution guide

- src/peft/tuners/adalora.py
- src/peft/tuners/ia3.py
- src/peft/tuners/lora.py
- src/peft/tuners/tuners_utils.py
This is to be consistent with changes in #794
The `forward` methods of several tuner layers were partly unnecessarily nested, which made them harder to read and which can conceal bugs (as in #794). Therefore, these methods have been refactored to (hopefully) be as readable as possible. Moreover, the different methods are now coded as similar as possible between the different implementations.
On top of those changes, I made the following adjustments:
- added some type hints to the methods of the layers
- removed a comment about code being copied which I think is not necessary
- for the lora embedding layer, we sometimes used `F.embedding(...)` and sometimes `nn.Embedding.forward(self, ...)` -- now, we consistently use only `F.embedding(...)`
- for IA³ `Linear8bitLT`, apply dtype conversion …
> MNT: Refactor tuner forward methods for simplicity

- src/peft/tuners/ia3.py
I noticed they led to weird formatting on the HF documentation here: https://huggingface.co/docs/peft/main/en/package_reference/tuners#peft.IA3Config
> Fix typos in ia3.py

- src/peft/peft_model.py
The problem is that for prompt tuning, the decoder attention mask is extended as if the prompt was in the decoder (whereas it is in the encoder). So the decoder attention mask was too long. Feel free to propose better ways to fix the problem if my solution is not ideal (I'm not an expert).
See #439 for a code snippet that reproduces the problem.
> Fix seq2seq prompt tuning (#439)

- src/peft/tuners/lora/bnb.py
This was introduced during the refactoring of the `forward` function. It should now be fixed and be equivalent to the `forward` function before the refactoring:
https://github.com/huggingface/peft/blob/4df9c5a243194b03e703c1dd526d64163f9b4fd2/src/peft/tuners/lora.py#L1207-L1231
Bug reported by @jiqing-feng
> FIX: Error in forward of 4bit linear lora layer

- src/peft/tuners/adalora/bnb.py
- src/peft/tuners/lora/bnb.py
running hf trainer with deepspeed/zero2, to train bf16 + load_in_8bit + lora/peft, the following error is observed:
> RuntimeError: expected scalar type Float but found BFloat16
poking around a debugger, i saw:
```
-> breakpoint()                                                                                                            
(Pdb) l                                                                                                                    
113         def forward(self, input: Tensor) -> Tensor:                                                                    
114             try:                                                                                                       
115                 return F.linear(input, self.weight, self.bias) …
```
> Fix error using deepspeed zero2 + load_in_8bit + lora

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/int8_training/peft_adalora_whisper_large_training.py
> fix_gradient_accumulation_steps_in_examples

- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
See discussion in #872 
This is an attempt at speeding up initialization of LoRA layers. As mentioned in [this comment](https://github.com/huggingface/peft/pull/872#issuecomment-1698899931), it seems that we currently create the weights of the linear layer that is to be adapted with LoRA twice (!), only to override it later by the original weights of the target layer. This PR attempts to remove that redundancy.
Before this can be merged, there should be a thorough study of potential implications, since this could be BC breaking if we miss something, and the impact on initialization speed should be measured.
I think an even cleaner design would be to pass the target module to the LoRA layer, so that the LoRA layer can hold a reference to it. During `forward`, it would call …
> ENH Remove redundant initialization layer calls

- docs/source/task_guides/semantic-similarity-lora.md
Removes the double setup section in the semantic similarity task guide.
> [docs] Remove duplicate section

- docs/source/_toctree.yml
- docs/source/common_issues.mdx
- docs/source/developer_guides/troubleshooting.mdx
So far, this section contains two issues, not using latest package versions and issues with loading PEFT models. This is based on what I feel are issues that are commonly brought up.
If this is helpful, I think in the future, we should sections on common issues with quantization, correcting wrong expectations about memory use and runtime performance, etc., which I feel often come up.
Also, let me know if I should move the section to a different part of the docs.
> DOC: Section on common issues encountered with PEFT

- src/peft/peft_model.py
- src/peft/tuners/adaption_prompt/model.py
Resolves #802
For the problem description, please check the mentioned issue.
I went with solution 2, i.e. making the `base_model.peft_config` the "single source of truth" for the PEFT configuration. That way, we minimize the risk of diverging configurations.
This does not apply for prompt learning, where we don't have a `peft_config` on the base model (which is just the normal model, not a PEFT class).
For adaption prompt, I had to make a small change, renaming `self._configs` to `self.peft_config` to be consistent with the other tuners. It also differs by using the name `configs` in its `__init__` signature, in contrast to `config`, as all others do. I was tempted to rename it, but it would technically be backwards compatibility breaking (but PEFT code wouldn't be affected, as we pass it …
> Make base_model.peft_config single source of truth

- setup.py
Update accelerate version to fix -
```
File "/usr/local/lib/python3.9/dist-packages/peft/utils/other.py", line 24, in <module>                                                                     
from accelerate.utils import is_npu_available, is_xpu_available                                                                                           
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' (/usr/local/lib/python3.9/dist-packages/accelerate/utils/__init__.py)   
```
> Update accelerate dependency version

- src/peft/tuners/lora/layer.py
This PR fixes the [CI](https://github.com/huggingface/peft/actions/runs/6167094166/job/16737542434), and more precisely a test about gptq. The problem was that we were updating the dtype the lora layers with the dtype of the GPTQ layer weights. However, the dtype is uint8 which is not a floating point or complex. Bnb don't have that issue as the weight dtype at initialization is torch.float32. 
PS: Other tests are failing (`StableDiffusionModelTester`) but not related to this PR
> fix lora layer init

- examples/lora_dreambooth/convert_kohya_ss_sd_lora_to_peft.py
diffusers have recently replaced Conv2d and Linear layers with [LoraCompatibleConv](https://github.com/huggingface/diffusers/blob/9800cc5ece794f8e63b61fb21e8f3197a88bc00f/src/diffusers/models/lora.py#L103) and [LoraCompatibleLinear](https://github.com/huggingface/diffusers/blob/9800cc5ece794f8e63b61fb21e8f3197a88bc00f/src/diffusers/models/lora.py#L170).
This pull request fixes wrong conversion of kohya_ss trained LoRAs. It should be better to determine whether module is Linear or Conv2d block based on class inheritance, not based on its name.
@BenjaminBossan @pacman100 your review is kindly appreciated.
> Fixed LoRA conversion for kohya_ss

- src/peft/tuners/lora/layer.py
This PR adds a new small API in LoRA layers to be able to iteratively scale / unscale loRA layers, which is useful in the context of diffusion models.
cc @pacman100 @BenjaminBossan @patrickvonplaten @sayakpaul 
https://github.com/huggingface/diffusers/pull/4780
> [`LoRA`] Add scale_layer / unscale_layer

- docs/source/conceptual_guides/lora.mdx
- examples/lora_dreambooth/convert_kohya_ss_sd_lora_to_peft.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
@pacman100 Hi!
As discussed in #873, here are the modifications I've done to fix the issue I had mentioned.
Also, I would like to add proper support for special type of LoRAs for StableDiffusion - LoRA-C3Lier - this is just a LoRA with different rank and alpha for conv2d layers, so I refactored the conversion script.
The new conversion script works better - it automatically detects whether the provided LoRA contains conv2d (1x1, 3x3) layers or not and provides custom ranks / alphas for these layers if needed.
This script can be easily modified for proper support of SDXL LoRAs, so I was going to add it in separate PR if you are comfortable with it.
> Fixed multirank + multialpha for sequential LoRAs, added correct support of LoRA-C3Lier conversion

- .github/workflows/torch_compile_tests.yml
- tests/__init__.py
The GitHub action works by setting an environment variable `PEFT_DEBUG_WITH_TORCH_COMPILE=1`. This causes the tests to run with torch.compile if `get_peft_model` is being used. The action is triggered manually and requires to indicate the branch to run it on.
Once this PR is merged, the action should be listed [here](https://github.com/huggingface/peft/actions). Unfortunately, I don't think we can really test this before merging into main. I did, however, add a similar action to a [toy repo](https://github.com/BenjaminBossan/mops/blob/main/.github/workflows/manual_trigger.yml) where it works. To instead run tests with `torch.compile` locally, just use the normal test command with the env var set to 1, e.g. `PEFT_DEBUG_WITH_TORCH_COMPILE=1 make test`.
With this action, we should be able to …
> TST: Add GH action to run unit tests with torch.compile

- .github/workflows/torch_compile_tests.yml
There was a small mistake in the previous GH action because pytest was not being installed. This should fix it.
> FIX: torch compile gh action installs pytest

- src/peft/tuners/lora/model.py
I tried creating a LoRA of LLAMA-2 model with the following config. But it fails with the shown error. I took a look into the implementation and thought this might fix it for me and it indeed does. 
```
model = AutoModelForCausalLM.from_pretrained(
'meta-llama/Llama-2-7b-hf',
device_map = 'auto',
torch_dtype = torch.bfloat16
)
peft_config = LoraConfig(
r = 16,
lora_alpha = 64,
lora_dropout = 0.1,
target_modules=['q_proj','v_proj'],
bias = None,
task_type = "CAUSAL_LM"
)
peft_model = get_peft_model(
model,
peft_config
)
```
With default `active_adapter` the bias is None and we're only checking it against "none".
Here's the full error.
```
"name": "NotImplementedError",
"message": "",
"stack": "---------------------------------------------------------------------------
NotImplementedError …
```
> Fix NotImplementedError for no bias.

- src/peft/utils/save_and_load.py
- tests/test_custom_models.py
- tests/testing_common.py
- tests/testing_utils.py
Some tests would currently fail with `torch.compile`, not because there is anything wrong with how PEFT works with compiled models, but simply because of the way the tests are written. This is because when models are compiled, the keys of the state dict change. Tests have now been adapted to unwrap the compiled model first before getting the state dict.
Note that the mentioned issue does not affect saving and loading, because `save_pretrained` is already called on the original module, so there is no issue with mismatched keys.
While working on this, I also fixed the docstring of `get_peft_model_state_dict`.
Running the `torch.compile` tests against this branch failed, probably because it's a fork :-/ https://github.com/huggingface/peft/actions/runs/6238068686/job/16933091996
> TST: Fix some tests that would fail with torch.compile

- .github/workflows/torch_compile_tests.yml
If the action is triggered with `nightly=true`, the nightly PyTorch version will be installed.
Also, added a line that *may* enable the action to run on forks, not sure if it'll work but it shouldn't hurt either.
> ENH Allow compile GH action to run on torch nightly

- .github/workflows/integrations_tests.yml
Adds a workflow to manually run PEFT integration of transformers and diffusers tests to make sure new PRs will not break those integrations
> [`tests`] add transformers & diffusers integration tests

- src/peft/utils/other.py
1. Add the lora target modules for Mistral Models
> add the lora target modules for Mistral Models

- tests/testing_common.py
Resolves #968
As the linked issue mentions, the `test_save_pretrained_selected_adapters` test was broken because the 2nd adapter would load the weight of the default adapter, instead of its own weights. This was a pretty quick fix.
However, this made me wonder why the test was passing beforehand when it is loading the wrong weights, so I dug deeper (warning: rabbit hole!).
The first issue I encountered was that for IA³, we did not set `init_ia3_weights=False`. For this reason, all weights were set to `1.0`. Of course, in that case, it doesn't matter what weights are loaded, they're all the same. Therefore, I changed `init_ia3_weights=False`.
However, this still doesn't explain why this worked for LoRA, which, even without `init_lora_weights=True`, should have some completely random …
> TST: Fix broken save_pretrained tests

- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
1. Add multiple active adapters tests
> [tests] add multiple active adapters tests

- tests/test_gpu_examples.py
This should hopefully fix the error in `test_causal_lm_training_mutli_gpu_4bit` (see e.g. [here](https://github.com/huggingface/peft/actions/runs/6346369912/job/17239765704)). I haven't tested it, as it's multi GPU.
> Fix missing tokenizer attribute in test

- README.md
- examples/lora_dreambooth/convert_kohya_ss_sd_lora_to_peft.py
- examples/stable_diffusion/convert_sd_adapter_to_peft.py
- examples/stable_diffusion/train_dreambooth_loha.py
- src/peft/__init__.py
- src/peft/mapping.py
- src/peft/peft_model.py
- src/peft/tuners/__init__.py
- src/peft/tuners/loha/__init__.py
- src/peft/tuners/loha/config.py
- src/peft/tuners/loha/layer.py
- src/peft/tuners/loha/model.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/tuners_utils.py
- src/peft/utils/peft_types.py
- src/peft/utils/save_and_load.py
- tests/test_custom_models.py
- tests/test_stablediffusion.py
This PR focuses on increasing compatibility of SD&SDXL adapters in peft with other open-source instruments like [LyCORIS](https://github.com/KohakuBlueleaf/LyCORIS). Feel free to learn more about LyCORIS adapters from resources like [this](https://stable-diffusion-art.com/lycoris/).
This specific PR is currently aimed at adding proper compatibility of peft with LoHa adapters. The original paper is called [FedPara](https://arxiv.org/abs/2108.06098). LoHa is just a FedPara under the hood, but without federated learning. LoHa allows to train adapters with increased output quality and with more details compared to basic LoRA. As far as I know, it is probably the second most popular adapter for SD&SDXL on [civitai.com](https://civitai.com/models), so from my perspective ability to use it with …
> Add implementation of LyCORIS LoHa (FedPara-like adapter) for SD&SDXL models

- src/peft/tuners/ia3/layer.py
- src/peft/tuners/lora/bnb.py
- tests/test_custom_models.py
This should resolve the failing slow test `test_4bit_merge_and_disable_lora` (see e.g. [here](https://github.com/huggingface/peft/actions/runs/6346369912/job/17239765575)).
While investigating, I also noticed that merging multiple adapters was not correct for IA³. I added a test that should catch this bug and provided a fix for it too. However, the test does not check IA³ at the moment because the test parameters do not contain IA³. For this, #972 needs to be merged too, which adds IA³ to the test parameters.
Note: I did some small fixes on the tests to avoid exploding/vanishing gradients, as they made it difficult to find the right tolerance for comparing outputs.
> FIX: issues with (un)merging multiple LoRA and IA³ adapters

- src/peft/utils/other.py
i was able to load a model with `get_peft_model` method that takes `LoraConfig` object which has ["q_proj", "v_proj"] for its `target_modules` parameter.
> add lora target modules for stablelm models

- docs/source/developer_guides/custom_models.mdx
- docs/source/developer_guides/low_level_api.mdx
I have made a correction in line 75 to maintain consistency with the subsequent code. The hidden layer should be labeled as 'seq.2' instead of 'seq.1'.
> Fix typo in custom_models.mdx

- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
- tests/test_custom_models.py
- tests/testing_common.py
Resolves #938
This PR adds the base model metadata, if present, to the model card.
On top of this, the code for creating the model card has been refactored to use the huggingface_hub classes instead of doing ad hoc parsing and writing. A consequence of this is that if no model card exists, the default template will now be used, with a lot of placeholder text.
LMK if this is not desired.
ping @davanstrien @osanseviero
> Add base model metadata to model card

- src/peft/config.py
- src/peft/tuners/ia3/config.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/loha/config.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/tuners_utils.py
1. Makes the injecting of LoRA layers faster. The previous way of checking `target_module_found` was the bottleneck. This PR fixes that.
This help the PR https://github.com/huggingface/diffusers/pull/5151 when loading large SD-XL model. The time to load the lora ckpts went down from ~120 seconds to ~2 seconds.
> Fix lora creation

- tests/test_stablediffusion.py
This test is flaky when running on Windows. It is probably related to PyTorch 2.1, as this test used to work. Further investigation is needed.
> TST: Comment out flaky LoHA test

- src/peft/tuners/lora/bnb.py
Fixes: https://github.com/huggingface/peft/issues/1008
Analogous PR to #1001 but for bnb layers as well. Currently `merge_and_unload` fails for quantized models because `merge` does not have any positional argument. 
This PR implements the `safe_merge` option for bnb layers
> [`core` / `LoRA`] Add `safe_merge` to bnb layers

- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/model.py
- tests/test_common_gpu.py
Partly addresses #896
After speeding up normal LoRA layer initialization, this PR improves initialization speed of bnb LoRA layers.
The method to achieve this is different from the one used before, namely this time the base layer is stored as a reference on the LoRA layer. This allows us to avoid calling `__init__` on the bnb layer, which is what is slow.
We cannot use the same method as for the normal LoRA layers, (i.e. calling the super class's `__init__` with meta device) because the bnb layers have extra logic that still creates unnecessary weights (this is something that could potentially be fixed by bnb).
However, the way used here could also be a solution to the normal layers, so if we want to have consistency, the normal layers could be refactored to use the same approach.
Another …
> ENH: Refactor LoRA bnb layers for faster initialization

- src/peft/peft_model.py
> FIX Don't assume model_config contains the key model_type

- scripts/stale.py
At first, I was happy that we didn't have any stale issues anymore because I thought we became better at solving them. In reality, it's just an error with our `stale.py` script:
> can't subtract offset-naive and offset-aware datetimes
https://github.com/huggingface/peft/actions/runs/6497439325/job/17646562512
This is an attempt to fix the issue.
Notes:
1. I haven't tested it. But what is the worst that can happen (all issues and PRs being closed :D)??
2. I'm not sure why this suddenly happens, I suspect that PyGithub changed the return type of their `datetimes` to be timezone-aware.
3. If this works, other repos should also be updated (e.g. accelerate ping @muellerzr).
4. Alternatively, we could use the GH [stale action](https://github.com/actions/stale).
> FIX stale.py uses timezone-aware datetime

- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/testing_common.py
Specifically addresses: https://github.com/huggingface/diffusers/pull/5151#pullrequestreview-1672087496 
Some users might want to perform `merge_and_unload` when the adapter weights being in fp16. 
In diffusers users are able to perform that as the lora weights are always upcasted to fp32: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/lora.py#L257 before merging
Therefore I think we might need to support that usecase to avoid regressions in diffusers. 
I propose to perform the upcasting to fp32 only in the case adapter weights are on cpu and the dtype of the adapter weights are in fp16
Added also nice tests
cc @BenjaminBossan @pacman100 @patrickvonplaten @sayakpaul
> FEAT: Add fp16 + cpu merge support

- src/peft/tuners/lora/layer.py
Partially fixes https://github.com/huggingface/diffusers/issues/5414 - fix proposed by @BenjaminBossan 
A fix is going to be upstreamed on diffusers as well
For unscaling, we can use a new argument to divide back the current scale with the scale argument, if no scale is passed, `self.scale[adapter_name]` will be retrieved back to its original value.
> [`LoRA`] Revert original behavior for scale / unscale

- src/peft/config.py
- tests/test_config.py
Fixes #1045, supersedes #1041
When loading a config from a file, we currently set the loaded attributes on the config directly. However, this sidesteps the `__post_init__` call, which is required to convert the target_modules to a set. This PR fixes this by avoiding to set attributes on the config class directly, instead of going through `__init__`.
While working on this, I did a slight refactor of the config tests.
1. All config classes are included now (some where missing before).
2. Added a unit test for the aforementioned bug.
3. Use `parameterized` instead of looping through the classes. Note that this makes the diff look much bigger than it actually is, the tests are actually unchanged, just unindented by one level because the loop is removed.
This fix is based on my comment here: …
> Fix target_modules type in config.from_pretrained

- examples/stable_diffusion/convert_sd_adapter_to_peft.py
- src/peft/tuners/loha/layer.py
- tests/test_custom_models.py
This PR addresses the issue I found with the current LoHa adapter implementation. Right now there is a bug that does not take into account hada_t2 parameter during delta weights [calculation](https://github.com/huggingface/peft/blob/aaa7e9f44a6405af819e721d7ee7fc6dd190c980/src/peft/tuners/loha/layer.py#L160) both in train and inference.
This bug also exists in the original implementation, so I've created a similar [PR](https://github.com/KohakuBlueleaf/LyCORIS/pull/115) to fix it in LyCORIS repo.
I've included some tests that cover this functionality + fixed several errors in SD adapters conversion script (mentioned in [#978](https://github.com/huggingface/peft/pull/978)).
It would be great if this PR would get merged before the next release, so we won't need to provide some sort of …
> Fixed wrong construction of LoHa weights, updated adapters conversion script

- docs/source/task_guides/ptuning-seq-classification.mdx
This PR includes a very minor change in the P-tuning for sequence classification task guide documentation. Previously, in the inference part, the docs showed that the user should import the `AutoModelForCasualLM` module while the right one should be `AutoModelForSequenceClassification`.
> Fix P-tuning for sequence classification docs

- src/peft/peft_model.py
- src/peft/tuners/lora/model.py
- tests/testing_common.py
Bug was reported [here](https://github.com/huggingface/peft/issues/1045#issuecomment-1777761363).
Currently, when calling `set_adapter`, the active adapter is not updated. Tests have been added to trigger the bug, and the method updated to fix it.
Moreover, I created an `active_adapters` property on the `PeftModel` class so that it behaves consistently with the underlying base model classes like `LoraModel`.
> FIX: Setting active adapter correctly

- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- tests/test_custom_models.py
Fixes the error after merging a Conv1D layer, as described in https://github.com/huggingface/peft/pull/972#issue-1915881305 . Currently, PEFT subclasses nn.Linear and injects trainable parameters. For Conv1D layers, we use `fan_in_fan_out` to make note of the fact that the weights need to be transposed for correct behaviour. Thus, this Linear layer has to be converted back into a Conv1D layer when you merge and convert back into the base model, but this wasn't happening before with IA3. This meant that the base model returned by `merge_and_unload` had all Conv1D layers replaced by Linear layers. I've used the LoRA implementation as a reference to fix this, and added a flag `is_target_conv1d_layer` to IA3's Linear layer. @BenjaminBossan I've simply uncommented all your tests for Conv1D …
> Fix Conv1D merge error for IA3

- src/peft/utils/other.py
Partially fixes: https://github.com/huggingface/trl/issues/835
This PR depends on https://github.com/huggingface/transformers/pull/27020 - with that PR, we introduce a new argument in the `gradient_checkpointing_enable()` API in order for users to pass `gradient_checkpointing_kwargs`. To fix some issues with DDP and gradient_checkpointing, it is recommended to use `use_reentrant=True` which is the fix for  https://github.com/huggingface/trl/issues/835 
Therefore I propose to expose an optional argument `gradient_checkpointing_kwargs` in `prepare_model_for_kbit_training`
> [`core`] Fix `use_reentrant` issues

- .github/workflows/nightly.yml
- docker/peft-gpu/Dockerfile
An attempt to fix the current example tests being skipped - according to the logs:
```bash
./../../../opt/conda/envs/peft/lib/python3.8/site-packages/torch/cuda/__init__.py:138
/opt/conda/envs/peft/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
return torch._C._cuda_getDeviceCount() > 0
../../../../opt/conda/envs/peft/lib/python3.8/site-packages/bitsandbytes/cexte …
```
> [`tests`] Update Dockerfile to use cuda 12.2

- scripts/log_reports.py
As per title, the line `nb_lines = sum(1 for _ in f)` will loop over all the lines in the file and leading the next for loop to be empty 
> Fix Slack bot not displaying error messages

- src/peft/tuners/adaption_prompt/config.py
- tests/test_adaption_prompt.py
- tests/test_config.py
Adaption prompt is failing with transformers v4.35.0. This PR skips the adaption prompt tests so that CI is green again. The PR also adds an error when users try to use adaption prompt with that version, instructing them to use an older transformers version instead.
This should be removed as soon as the issue is fixed in PEFT/transformers.
> FIX: Skip adaption prompt tests with new transformers versions

- src/peft/tuners/adaption_prompt/config.py
- src/peft/tuners/adaption_prompt/utils.py
- tests/test_adaption_prompt.py
- tests/test_config.py
As per title, fixes the current CI for adaption prompt and makes it compatible.
Transformers refactored the way positional embeddings are computed for llama, in the previous versions `cos` and `sin` cache values had a shape of length 4, now it was only a shape of length 2, breaking the assumptions we made in `llama_apply_rotary_pos_emb`.
I propose to keep the previous behaviour in case len(cos.shape) == 4, and fall back to the newest way of computing `q_embed` as depicted here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L222-L226
> FIX: fix adaptation prompt CI and compatibility with latest transformers (4.35.0)

- docker/peft-gpu/Dockerfile
Optimum pins transformers to <4.35.0, leading our docker images to have transformers==4.34.1, which is not intended since we want to test PEFT against transformers and accelerate main
This PR fixes it, there is no need to update the cpu docker file as optimum is not installed there
> [`Docker`] Update Dockerfile to force-use transformers main

- setup.py
As discussed, we wanted to make small amendments to the release process, so that we have a 0.N.0 commit on main. I also adjusted the wording here and there.
There were some open questions, which I have marked with a `FIXME`. Please let me know how to proceed with those.
Note: For me, the GitHub diff view is not correct, so please check the changes carefully.
> Update the release checklist

- src/peft/import_utils.py
- src/peft/utils/other.py
- tests/test_gpu_examples.py
This PR updates the GPTQ training since the latest version of gptq includes breaking changes. We also switch `disable_exllama` to `use_exllama` since it is deprecated in the latest version of transformers. Tests are passing with transformers main.
> fix-gptq-training

- src/peft/utils/other.py
Minor changes to the default IA $^3$ config for Falcon models. IA $^3$ learned vectors are added to the second feedforward layer in the MLP block, and for falcon that would be `dense_4h_to_h` as seen [here](https://github.com/huggingface/transformers/blob/a5e6df82c00cb53ffe863008cbbedd813bcc508b/src/transformers/models/falcon/modeling_falcon.py#L744C21-L744C21).
> Fix IA3 config for Falcon models

- tests/test_common_gpu.py
Same idea as in PR as #1094, but for yet more ill-configured IA³ configs. The tests are now failing because we do stricter checks on incorrect IA³ configs.
These are the failing tests:
https://github.com/huggingface/peft/actions/runs/6806502406/job/18507828825
https://github.com/huggingface/peft/actions/runs/6806502406/job/18507829021
With this fix, they now pass locally.
> FIX: Failing nightly CI tests due to IA3 config

- src/peft/peft_model.py
- tests/test_common_gpu.py
- tests/test_encoder_decoder_models.py
Fixes https://github.com/huggingface/peft/issues/1079
Safetensors do not support tensor aliasing, before saving the model state dict, we need to loop over the state dict and check for aliased tensors and `clone()` them to avoid any error
> [`core`] Fix safetensors serialization for shared tensors

- src/peft/utils/other.py
there is no need to import auto_gptq if we're not going to use it. We're seeing issues downstream with the latest auto-gptq if it happens to be installed but not needed.
> avoid unnecessary import

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/loha/layer.py
- src/peft/tuners/lokr/layer.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_feature_extraction_models.py
- tests/testing_common.py
The job of deleting an adapter is now transferred to the adapter layer,
instead of the adapter model. This makes it easier for users or other
libraries who don't use the adapter model to delete adapters.
The code should now be more generic, relying less on hard-coded
attributes.
As a precaution, I also changed the type of `adapter_layer_names` from
list to tuple, as it should not be mutated.
When deleting the active adapter, the logic for choosing the new active
adapter has been changed slightly to ensure consistency across layers.
In practice, this should rarely make a difference. ~~An error is now
raised if the last remaining adapter is deleted.~~
- Deleting adapters is now also tested for custom models.
- It is also tested for LoHa, LoKr, not only LoRA.
- I added a test for deleting …
> Refactor adapter deletion

- docs/source/task_guides/dreambooth_lora.mdx
- examples/lora_dreambooth/train_dreambooth.py
Running the train_dreambooth.py script on Windows leads to the common issue that the pytorch dataloader crashes or is extremly slow because num_workers > 0 is not well supported ([Pytorch Issue#12831](https://github.com/pytorch/pytorch/issues/12831)).
I have therefore added the parser arg `--num_dataloader_workers` which by default is set to 1 (same default as before but now possible to configure from the outside). I also added a small sentence to the documentation, warning others about this common pitfall.
> Added num_dataloader_workers arg to fix Windows issue

- src/peft/import_utils.py
- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/other.py
Fixes #1114 
Let's just copy-past the method as the method is relatively easy and do not depend on many things
> Fix import issue transformers with `id_tensor_storage`

- src/peft/tuners/tuners_utils.py
- tests/test_low_level_api.py
Currently when using the low-level API of PEFT, the `modules_to_save` gets silently ignored. The PR addressed that.
cc @BenjaminBossan @pacman100 
Will also test the integration tests and add corresponding tests on transformers once we release a PEFT version with it
> Correctly deal with  `ModulesToSaveWrapper` when using Low-level API

- src/peft/peft_model.py
- tests/testing_common.py
Adding two adapters (e.g. LoRA) when using a list for `target_mdules` works but passing a str fails. The issue is that for str, we do a `re.fullmatch`, whereas for list, we just check `endswith`. After adding the first adapter, though, the naming pattern of the modules changes. In the example above, the name for the linear layer changes from `"lin0"` to `"base_model.model.lin0"`, which is why the `fullmatch` fails but the `endswith` still works.
```python
from peft import LoraConfig, get_peft_model
from torch import nn
class MLP(nn.Module):
def __init__(self, bias=True):
super().__init__()
self.lin0 = nn.Linear(10, 20, bias=bias)
def test_target_modules_list():
config = LoraConfig(target_modules=["lin0"])
test_it(config)
print("Adding two adapters with target_module being a list works") …
```
> FIX: Adding 2 adapters when target_modules is a str fails

- examples/lora_dreambooth/train_dreambooth.py
`TorchTracemalloc` ruins the Dreambooth training performance on Windows, so that the training barely even runs. I fixed this issue by providing a parser argument `--trace_memory_allocation` that is set to `True` by default but can be turned off for Windows users. This significantly speeds up the training process.
> Fix: TorchTracemalloc ruins Windows performance

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lycoris_utils.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/testing_common.py
Partially addresses: https://github.com/huggingface/diffusers/issues/5320 
This PR exposes a new argument in `merge` termed as `adapter_names`, if a user passes an explicit `adapter_names` then only adapter names inside that array will be merged. This PR will make things smoother and easier to integrate on diffusers side
Added also a nice CI test
> FEAT: Merging only specified `adapter_names` when calling `merge`

- .github/workflows/nightly.yml
As per title, currently as soon as a job fails it stops the entire nightly workflow
This PR fixes it
> [`Tests`] Do not stop tests if a job failed

- src/peft/tuners/adalora/bnb.py
- src/peft/tuners/adalora/model.py
- tests/test_gpu_examples.py
This PR fixes a handful of issues with AdaLora, should resolve #1113.
1. `lora_A.weight.device` was called but for AdaLora, `lora_A` is an `nn.Paramter`, not an `nn.Module`, so the weight attribute does not exist. `lora_A.device` is sufficient.
2. For 8bit, an inplace operation failed because it was on a view. Now the operation is no longer inplace.
3. The loss term of the model output is not necessarily a torch tensor. In the test, it was a dict and did not contain an actual loss. Therefore, I added a check to make sure the loss is a torch tensor. Is there a better way?
Running `pytest tests/test_gpu_examples.py -k adalora` locally (with GPU) passes. Ideally, someone else can confirm, as normal unit tests won't catch this.
If this is merged before #1115, skipping AdaLora tests in that PR …
> FIX: A few issues with AdaLora, extending GPU tests

- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- tests/testing_common.py
As discussed in https://github.com/huggingface/peft/pull/980 (specifically https://github.com/huggingface/peft/pull/980#issuecomment-1815902304), we are breaking that PR into smaller PRs that can be merged faster. 
In this first PR, we include the ability to delete $(IA)^3$ adapters. 
A new method `delete_adapter` has been added to the `IA3Model` class. This method is based on https://github.com/huggingface/peft/blob/f1ecfa6ae6eba599ae89decbf47b339d8c9d39a3/src/peft/tuners/lora/model.py#L608
- Added `PeftType.IA3` to `testing_common.py#_test_delete_adapter`
- Run the tests and checked that they pass
> Delete IA3 adapter

- src/peft/tuners/lora/model.py
- tests/testing_common.py
1. Fixes https://github.com/huggingface/peft/issues/1155
> fix `add_weighted_adapter` method

- docs/source/accelerate/deepspeed-zero3-offload.md
- docs/source/accelerate/fsdp.md
- docs/source/conceptual_guides/ia3.md
- docs/source/conceptual_guides/lora.md
- docs/source/conceptual_guides/prompting.md
- docs/source/developer_guides/contributing.md
- docs/source/developer_guides/custom_models.md
- docs/source/developer_guides/low_level_api.md
- docs/source/developer_guides/troubleshooting.md
- docs/source/index.md
- docs/source/install.md
- docs/source/package_reference/config.md
- docs/source/package_reference/peft_model.md
- docs/source/package_reference/tuners.md
- docs/source/quicktour.md
- docs/source/task_guides/clm-prompt-tuning.md
- docs/source/task_guides/dreambooth_lora.md
- docs/source/task_guides/image_classification_lora.md
- docs/source/task_guides/int8-asr.md
- docs/source/task_guides/ptuning-seq-classification.md
- docs/source/task_guides/semantic-similarity-lora.md
- docs/source/task_guides/semantic_segmentation_lora.md
- docs/source/task_guides/seq2seq-prefix-tuning.md
- docs/source/task_guides/token-classification-lora.md
Similar to https://github.com/huggingface/huggingface_hub/pull/1522, this PR migrates doc files from `mdx` to `md` because it is pretty hard to read the diffs in `mdx`.
> [docs] Migrate doc files to Markdown

- src/peft/tuners/lycoris_utils.py
This is important if we have nested adapter layers. This was an overlook during the refactoring #1106.
> FIX: Wrong use of base layer

- docs/source/quicktour.md
Hello 👋 
The model in the code snippet in `quicktour.md` has a key in it's `config` file that's likely either deprecated (breaks backwards compatibility?). 
The code is as follows 👇 
```py
from transformers import AutoModelForSeq2SeqLM
from peft import PeftModel, PeftConfig
peft_model_id = "smangrul/twitter_complaints_bigscience_T0_3B_LORA_SEQ_2_SEQ_LM"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
model = model.to(device)
model.eval()
inputs = tokenizer("Tweet text : @HondaCustSvc Your customer service has been horrible during the recall process. I will never purchase a Honda …
```
> Fix code example in quicktour.md

- README.md
Resolves #1151
- fix bits_and_bytes => bitsandbytes
- add a few links
- add mistral to list of supported models
A question: What is the criterion for a model to be considered to be "supported" for a given adapter? E.g. "ChatGLM" is listed as having support for all methods, but we only have an entry for it in `TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING`, not in `TRANSFORMERS_MODELS_TO_IA3_TARGET_MODULES_MAPPING` etc. So should we really put a ✅ in all those columns? For mistral, I only added a ✅ for LoRA, as that's the only entry for mistral that we have, even though I'm pretty sure we can just use the same settings for other adapters.
> DOC Update a few places in the README

- src/peft/peft_model.py
- src/peft/utils/save_and_load.py
Peft checks if a file exists with ```hub_file_exists```, but doesn't pass the kwargs containing the auth token to it, therefore it fails to load if the repo is private even if it exists. This PR fixes that.
> Fix issue where you cannot call PeftModel.from_pretrained with a private adapter

- setup.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- tests/test_initialization.py
This PR adds the possibility to use different initialization methods for LoRA, as is a requirement for a completely backwards compatible adoption of PEFT in diffusers.
The default is still the same as always, namely the one from the reference implementation by Microsoft. On top of that, it is now possible to pass `init_lora_weights='gaussian'` to initialize the LoRA weights in the same way as is default for diffusers, namely with a normal distribution which is scaled by 1/r.
The init method currently applies to LoRA linear and conv layers, but not embedding layers, which are always initialized from a normal distribution (and are probably irrelevant for diffusers).
In the future, similar extensions could be added for other adapter methods.
For testing, a rather simple test is added which …
> ENH: Different initialization methods for LoRA

- README.md
- examples/loftq_finetuning/README.md
- examples/loftq_finetuning/quantize_save_load.py
- examples/loftq_finetuning/train_gsm8k_llama.py
- requirements.txt
- src/peft/__init__.py
- src/peft/tuners/__init__.py
- src/peft/tuners/lora/__init__.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/utils/loftq_utils.py
I have added the LoftQ method to LoRA. I have run the `make style` command.
> LoftQ: Add LoftQ method integrated into LoRA. Add example code for LoftQ usage.

- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lora/tp_layer.py
- tests/test_lora_megatron.py
We implemented the Lora algorithm for megatron's distributed layer ColumnParallelLinear and RowParallelLinear.
Due to the particularity of megatron creating a distributed layer, the required megatron information needs to be injected before executing Lora:
```python
from megatron.arguments import core_transformer_config_from_args
from megatron import get_args
from peft import LoraConfig, get_peft_model
config = core_transformer_config_from_args(get_args())
lora_config = LoraConfig(
r=16,
lora_alpha=32,
target_modules=['query_key_value', 'dense', 'dense_h_to_4h', 'dense_4h_to_h'],
lora_dropout=0.0,
bias="none",
megatron_config=config,
megatron_core="megatron.core",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
```
It has been verified on the megatron and …
> Parallel linear Lora

- src/peft/mixed_model.py
- src/peft/tuners/mixed/model.py
- tests/test_mixed.py
This PR makes it possible to use the newly added OFT adapter in mixed adapter type models, similar to LoRA, LoHa, etc.
Adding the integration was pretty straightforward, which is a good sign.
The difficult part was actually about the tests. This stems from the fact that OFT is (if my understanding is correct) never commutative. What I mean is that even if the adapters are applied to the last layer of a model, it makes a difference whether we apply, say, first LoRA, then OFT vs first OFT, then LoRA.
This is different for the other adapters that were added so far for mixed models, as they basically do:
- `Xa = X + dXa`
- `Xab = Xa + dXb = X + dXa + dXb = X + dXb + dXa = Xb + dXa = Xba`
IIUC, this is not true for OFT, so when OFT is used, I had to ensure that no test was applied that …
> ENH: Enable OFT adapter for mixed adapter models

- docs/source/_toctree.yml
- docs/source/index.md
- docs/source/package_reference/auto_class.md
- docs/source/quicktour.md
Starts implementing some of the things we discussed in our docs plan:
- clarify the difference between using `AutoPeftModel` (inference) and `PeftConfig` + `get_peft_model` (train) and splits the quicktour more generally along these lines
- add API reference for `AutoPeftModel` classes
- cleans up the index with a Space for discovering what models/methods are supported given a task (let me know if you think this is easier and cleaner)
- create separate subsection for LoRA guides
> [docs] Update index and quicktour

- docs/source/_toctree.yml
- docs/source/package_reference/adalora.md
- docs/source/package_reference/adapter_utils.md
- docs/source/package_reference/config.md
- docs/source/package_reference/ia3.md
- docs/source/package_reference/llama_adapter.md
- docs/source/package_reference/loha.md
- docs/source/package_reference/lokr.md
- docs/source/package_reference/lora.md
- docs/source/package_reference/multitask_prompt_tuning.md
- docs/source/package_reference/p_tuning.md
- docs/source/package_reference/peft_model.md
- docs/source/package_reference/peft_types.md
- docs/source/package_reference/prefix_tuning.md
- docs/source/package_reference/prompt_tuning.md
- docs/source/package_reference/tuners.md
Expands and reorganizes the API docs to include other supported adapter methods, the `BaseTuner` class, and `Lycoris` classes.
> [docs] API docs

- docs/source/conceptual_guides/lora.md
Document the initialization options for LoRA. This is especially important for LoftQ, since otherwise, it may not obvious for users how to make use of it.
> DOC: Initialization options for LoRA

- setup.py
- src/peft/__init__.py
Also updated the release instruction for installing from pypi, as the previous command seems to be causing trouble recently (see internal discussion).
> Bump version to 0.7.1.dev0 post release

- src/peft/peft_model.py
- src/peft/tuners/tuners_utils.py
- tests/testing_common.py
Initially, we had the issue that it was sometimes assumed that models had a `config` attribute, as is given for transformers models. This made PEFT fail with custom models, so we made a change to set a dummy config on those.
However, this can lead to issues down the line. For example, when users use the `Trainer` class from transformers, they can stumble upon lines like this:
https://github.com/huggingface/transformers/blob/62ab32b2997846526cdffd629c72c47bc7b4f215/src/transformers/integrations/integration_utils.py#L636-L637
https://github.com/huggingface/transformers/blob/62ab32b2997846526cdffd629c72c47bc7b4f215/src/transformers/integrations/integration_utils.py#L729-L730
Here transformers assumes that if `config` attribute exists on the model, it must have a `to_json_string` method or a …
> Don't set config attribute on custom models

- .github/workflows/nightly.yml
- Makefile
> TST: Run regression test in nightly test runner

- docker/peft-gpu/Dockerfile
Some tests are failing with bitsandbytes 0.41.3:
`python -m pytest -m single_gpu_tests tests/test_common_gpu.py -k test_4bit_merge`
(https://github.com/huggingface/peft/actions/runs/7122876428/job/19394584017)
For the time being, use the next smaller version.
> FIX: Pin bitsandbytes to <0.41.3 temporarily

- docker/peft-gpu/Dockerfile
This reverts commit 86562eec49bede2f4525be343f642af8fb46ddbc.
[`bitsandbytes==0.41.3.post1`](https://pypi.org/project/bitsandbytes/0.41.3.post1/) is now released with the reversal of the contribution that caused the issue with the integration tests. The tests are passing again with this release.
> Revert "FIX Pin bitsandbytes to <0.41.3 temporarily (#1234)"

- docs/source/_toctree.yml
- docs/source/developer_guides/quantization.md
- docs/source/package_reference/peft_model.md
A rough first draft of how quantization and PEFT can be used together. It mainly focuses on the QLoRA method and also references LoftQ.
> [docs] Quantization

- scripts/log_reports.py
Should fix the issue of not receiving slack notifications because the message is too long.
Currently, we get:
> Error: ver responded with: {'ok': False, 'error': 'invalid_blocks', 'errors': ['failed to match all allowed schemas [json-pointer:/blocks/1/text]', 'must be less than 3001 characters [json-pointer:/blocks/1/text/text]'], 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/blocks/1/text]', '[ERROR] must be less than 3001 characters [json-pointer:/blocks/1/text/text]']}}
https://github.com/huggingface/peft/actions/runs/7148379741/job/19469273483
Fixing the error should also lead to a shorter message, but we should ensure that even if the message is too long, we still get it.
Also: Removed some trailing whitespace.
> FIX: Truncate slack message to not exceed 3000 chars

- src/peft/peft_model.py
- src/peft/tuners/adaption_prompt/utils.py
- tests/test_adaption_prompt.py
- tests/test_multitask_prompt_tuning.py
It seems that transformers==4.36 breaks some of our tests. Locally, they pass with 4.35 but fail with 4.36.
One offending line is this:
https://github.com/huggingface/peft/blob/b08e6faf2b23a52e6853b59e9cf9e5663474da7f/src/peft/tuners/adaption_prompt/utils.py#L76
It seems that `past_key_values` used to be a tuple of tensors, now it is a [`DynamicCache`](https://github.com/huggingface/transformers/pull/26681), whose `__getitem__` returns a tuple of tensors. How can we rewrite the PEFT code in a backwards compatible fashion (i.e. it should also work with older transformers versions)?
Another error is [this](https://github.com/huggingface/peft/actions/runs/7168973578/job/19518392410#step:5:387):
```
if causal_4d_mask is not None:
>           expanded_attn_mask = …
```
> Issue with transformers 4.36

- src/peft/utils/other.py
- tests/test_low_level_api.py
https://github.com/huggingface/peft/issues/1225
We are recently using peft=0.4.0+Megatron to run GPTModel. There is a code of the model [`self.language_model.output_layer.weight`](https://github.com/NVIDIA/Megatron-LM/blob/bcce6f54e075e3c3374ea67adefe54f3f2da2b07/megatron/model/gpt_model.py#L94), which directly takes the `weight` of the `output_layer`, but the `output_layer` has already been `modules_to_save`, so it reported "ModulesToSaveWrapper has no 'weight' attribute" error.
So, I returns the weight of the currently active adapter or of the original module of the adapter is deactivated. 
And `__getattr__` will be called only when its own class does not have this attribute, so this should not destroy the original scene.
> Fix ModulesToSaveWrapper __getattr__

- tests/test_gpu_examples.py
This was recently added in #1242 but fails on CI with single GPU.
Refer to internal discussion.
> TST: Revert device_map for AdaLora 4bit GPU test

- docs/source/conceptual_guides/lora.md
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lora/tp_layer.py
- tests/test_initialization.py
Hi, I am proposing to add an option to use the corrected scaling factor for LoRA, based on the recent paper [A Rank Stabilization Scaling Factor for Fine-Tuning with LoRA](https://doi.org/10.48550/arXiv.2312.03732). Try setting `use_rslora = True`  in your `LoraConfig` for ranks greater than 32 and see the increase in fine-tuning performance (same or better performance for ranks lower than 32 as well).
Please feel free to suggest or change the implementation; I tried to go for the minimum code length change that implements this option.
For a LoRA adapter of rank $r$, the factor $\frac{\alpha}{r}$ that scales the adapter is too aggressive as a function of $r$, and slows learning for higher ranks so that no fine-tuning performance is gained over lower ranks. The paper [A Rank Stabilization …
> Added the option to use the corrected scaling factor for LoRA, based on new research.

- tests/test_gpu_examples.py
Tests to complement PR #1256, see [this comment](https://github.com/huggingface/peft/pull/1256#pullrequestreview-1780037331).
> TST: Extend LoftQ tests to check CPU initialization

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/ia3/layer.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/loha/layer.py
- src/peft/tuners/lokr/layer.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/oft/layer.py
- tests/test_common_gpu.py
This started as a simple refactor, but during this, I discovered a few issues too, which should now be fixed. This is probably best reviewed by checking each commit separately.
Here are the descriptions for the individual changes:
For LoRA, so far, we have `update_layer` for `Linear`, `update_layer_embedding` for `Embedding`, and `update_layer_conv2d` for Conv2d, all defined on `LoraLayer`.
We can simplify the code by always using the name `update_layer`, and by moving the layer-specific methods to the subclasses. So e.g. `update_layer_embedding` is moved to the `Embedding` class and renamed to `update_layer`. This way, the caller does not need to differentiate which type of layer it's calling, making it much easier (see the simplification in `LoraModel._create_and_replace`). It also …
> Refactor and a couple of fixes for adapter layer updates

- .github/workflows/build_docker_images.yml
- docker/peft-gpu-bnb-latest/Dockerfile
- docker/peft-gpu-bnb-source/Dockerfile
As per title, this will make life much easier for bnb developpers. I propose to create two separate docker images, both with bnb installed from source and run PEFT + transformers slow tests on daily basis, similarly as what we do currently with PEFT.
I can confirm building these docker images were successful on my local VM
cc @LysandreJik @Titus-von-Koeller @pacman100 @BenjaminBossan 
Will first test if the workflow works fine here on GH
> [`Tests`] Add bitsandbytes installed from source on new docker images

- tests/test_gpu_examples.py
Due to PR #1276, the bug that prevented use of LoftQ with 8bit quantization has now been fixed. Therefore, the tests no longer need to be skipped.
Note
I tested locally with GPU and the tests passed.
> TST: Enable LoftQ 8bit tests

- examples/stable_diffusion/convert_sd_adapter_to_peft.py
Hi!
I noticed and fixed several errors in the Stable Diffusion adapter conversion script:
1. There was an error in LoRA keys which resulted in wrong output checkpoints (no error was raised)
2. Some existing LoRA checkpoints like LCM contain only UNet keys, so the script failed to convert them properly
@BenjaminBossan your review is kindly appreciated.
> Fixed several errors in StableDiffusion adapter conversion script

- src/peft/tuners/ia3/config.py
- src/peft/tuners/lora/config.py
For LoRA and IA³, it is allowed to not specify a target module, in which case the correct layers are derived from the model architecture. This was not documented so far.
> DOC: Improve target modules description

- .github/workflows/nightly-bnb.yml
Address final comments from @ydshieh on. https://github.com/huggingface/peft/pull/1282#pullrequestreview-1791413593 
I left few questions !
cc @ydshieh
> [`bnb-nightly`] Address final comments

- .github/workflows/nightly-bnb.yml
This PR fixes the nightly docker file for the tests on the latest transformers. Right now, we are installing the latest transformers but we are launching the tests that are on the main branch. We need to checkout the corresponding branch (e.g. v4.36.3 if it is the version of transformers that is installed).
> [BNB] Fix bnb dockerfile for latest version 

- src/peft/tuners/tuners_utils.py
- src/peft/utils/other.py
1. Fixes the FSDP Auto Wrap policy for PEFT models to use the default `_no_split_modules` when available.
> fix fsdp auto wrap policy

- src/peft/tuners/lora/bnb.py
This appears to be a small oversight introduced with #1106. I was trying to load some loras onto LLMs using text-generation-webui, and noticed that the lora had no effect if the model was loaded with load_in_4bit. But non-quantized models still worked with the lora.
By adding this single line, it matches what is in the standard Linear lora layer. Now the quantized linear lora layers have the lora active by default.
> Fix bnb lora layers not setting active adapter

- src/peft/utils/save_and_load.py
1. For Adaption prompt, the embedding saving feature is currently broken. This PR fixes that.
2. Automate setting save_embedding_layers when embedding layer is resized during finetuning
> fix the embedding saving for adaption prompt

- src/peft/utils/save_and_load.py
1. fix diffusers tests 
```
FAILED tests/lora/test_lora_layers_peft.py::StableDiffusionXLLoRATests::test_simple_inference_with_text_unet_lora_save_load - ValueError: The checkpoint you are trying to load has model type `clip_text_model` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```
> fix diffusers tests

- src/peft/utils/loftq_utils.py
- tests/test_gpu_examples.py
Resolves #1307 
For PyTorch versions below 2, the usage of torch.int instead of torch.long when indexing inside of `dequantize_block` for LoftQ leads to an error. The fix consists of using torch.long.
I tested the change with my local GPU for both PyTorch 1.13 and 2.1 and the tests passed for both.
Note that initially, it seemed to be an issue with seq2seq models, until it was discovered to be PyTorch-related. This is why I added the seq2seq tests. Even though the tests not really necessary, I kept them in.
> FIX Use torch.long instead of torch.int in LoftQ for PyTorch versions <2.x

- src/peft/tuners/adalora/model.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/loha/model.py
- src/peft/tuners/lokr/model.py
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lora/tp_layer.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/oft/model.py
- src/peft/tuners/tuners_utils.py
This PR's goal is to simplify the logic for deciding which LoRA layer backend is being used when LoRA is applied to a target layer.
Originally, this refactor was done in #1286 which was about adding the "fast" backend for LoRA, but since that PR was closed, I moved the refactor to this dedicated PR.
Right, now, the `LoraModel._create_new_module` method has become quite complex and hard to read, spanning >100 lines:
https://github.com/huggingface/peft/blob/8665e2b5719faa4e4b91749ddec09442927b53e0/src/peft/tuners/lora/model.py#L235-L339
The reason for this is that method contains the logic for deciding which LoRA layer backend to use for all the different types of LoRA layers that we have, i.e. normal `Linear` layer, `Conv2d` layer, bnb layer, gptq, etc.
This PR greatly simplifies this …
> Refactor dispatching logic of LoRA layers

- src/peft/tuners/prompt_tuning/model.py
Prompt tuning did not need tokenizer when inference.
And it may encounter some bug if load tokenizer in some cases when inference.
(For my example, it will cant find the config.json for tokenizer in cache dir, and my development environment cant connect to the hugginface.)
> Fix bug when load the prompt tuning in inference.

- docs/source/developer_guides/troubleshooting.md
- tests/test_gpu_examples.py
Some users ran into the issue of trying to use a model loaded in float16 with mixed precision, e.g. these issues: #341, #1249. This PR documents a workaround to solve the issue.
I also added tests that demonstrate the issue, as well as the workaround.
This is not strictly a PEFT issue, but more a general error when using AMP with float16. Still, since PEFT users encounter this sometimes, it is useful to document it.
When we discussed this issue in the past, I think we concluded that it's not as straightforward as PEFT automatically casting the weights to float32, though I cannot remember anymore what the drawbacks were.
In any case, should we ever add an automatic solution for this in PEFT, the added test should fail, which alerts us to the fact that we need to update the documentation.
> DOC Troubleshooting for unscaling error with fp16

- src/peft/tuners/ia3/config.py
- src/peft/tuners/loha/config.py
- src/peft/tuners/lokr/config.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/oft/config.py
Over time, the docstrings of the numerous config classes have not kept up to date with changes in the code. This PR updates the docstrings to reflect the current state of the code.
On top of that, multiple small updates have been made:
- Correct wrong or imprecise type annotations.
- More neutral wording of the docstring. E.g., say "adapter" instead of "LoRA". This makes it easier to copy&paste the docstrings between classes.
- Use same wording for shared arguments.
- Add missing arguments.
- Uniform formatting: Always a line break after the first line of the docstring (not mixed, as that can be confusing).
- Fix line lengths to be consistently at 120 characters.
> DOC: Update docstring for the config classes

- src/peft/peft_model.py
1. The current logic from PR https://github.com/huggingface/peft/pull/1252 is incorrect as explained in https://github.com/huggingface/peft/pull/1252#issuecomment-1888604086 and https://github.com/huggingface/peft/pull/1252#issuecomment-1888614334.
2. This PR fixes it.
> fix `prepare_inputs_for_generation` logic for Prompt Learning methods

- src/peft/peft_model.py
See #1252 for more context.
The initial idea was for transformers v4.37 to add the new caching to all architectures, but this was postponed to v4.38. The code needs to be adapted for prompt tuning not to break when transformers v4.37 is released.
Big thanks to Joao for the heads up.
> New transformers caching ETA now v4.38

- src/peft/tuners/adalora/bnb.py
- src/peft/tuners/adalora/gptq.py
- src/peft/tuners/ia3/bnb.py
- src/peft/tuners/lora/gptq.py
- tests/test_gpu_examples.py
Resolves #1346
See also #1294 for a similar (but incomplete) fix.
This commit fixes the setting of the adapter name on a couple of quantized layers that was accidentally removed in #1106. This affects users who use a non-default adapter name when they want to train these layers.
Running the tests locally with GPU passes.
> FIX Setting active adapter for quantized layers

- docs/source/developer_guides/troubleshooting.md
Resolves #1300
Sourab added the feature to store the embedding layers alongside the adapter in #1147. This PR adds an entry to the documentation to explain the new feature.
> DOC Extending the vocab and storing embeddings

- docs/source/package_reference/peft_model.md
Adds missing API doc entry for `PeftMixedModel`.
HT @sayakpaul
> DOC Add PeftMixedModel to API docs

- src/peft/mixed_model.py
- src/peft/tuners/mixed/model.py
Hello, PEFT team!
I tried to use the new interface for MixedModel and discovered that the current implementation of PeftMixedModel and MixedModel lacks getattr dunder methods (so we cannot use corresponding underlying implementations for e.g. device).
This PR just adds these missing methods.
> Added missing getattr dunder methods for mixed model

- src/peft/auto.py
- src/peft/utils/constants.py
- tests/test_auto.py
1. In few scenarios the vocab of the model is extended to add special tokens like `<|im_start|>` ... In such scenarios during inference, the user needs to load the base model first and resize it the same way they did before training the model as shown below:
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
peft_model_id = "smangrul/tinyllama_lora_norobots"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, load_in_4bit=True, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(peft_model_id)
model.resize_token_embeddings(len(tokenizer))
model = PeftModel.from_pretrained(model, peft_model_id, adapter_name="norobots")
```
2. This wasn't handled by `AutoPeftModel` classes. This PR …
> Handle resizing of embedding layers for AutoPeftModel

- src/peft/tuners/lora/bnb.py
BNB has CI failures with 2 tests failing due to the following:
In merge method, the following things happens wherein the lora delta weights are added to the dequantized base layer weights. This is followed by setting the weight of the base layer to a new instance of  Params4bit with the new merged weights:
```
w_data = bnb.functional.dequantize_4bit(weight.data, weight.quant_state) + lora_data
self.get_base_layer().weight = bnb.nn.Params4bit(w_data.to("cpu"), requires_grad=False,**kwargs).to(weight.device)            
```
Now, kwargs copies the ones currently there which has bnb_quantized=True and the old quant_state so the new merged weights aren't quantized and the old quant state remains.  After this, during Linear4bit forward call, the old quant state is used while the weights are …
> account for the new merged/unmerged weight to perform the quantization again

- docs/source/developer_guides/lora.md
- docs/source/developer_guides/quantization.md
A small PR to add the new `all-linear` flag  (#1295) to PEFT docs.
> Improve documentation for the `all-linear` flag

- src/peft/utils/constants.py
Microsoft updated the `modeling_phi.py` file 1 day ago: https://huggingface.co/microsoft/phi-2/blob/main/modeling_phi.py. They did this for Phi-1, Phi-1_5 and Phi-2. 
The net effect of this change is that they no longer have the same model architecture from the originally released model -they use GQA now: https://github.com/huggingface/transformers/pull/28163. This means that `Wqkv` and `out_proj` are no longer valid target modules. Because of this, the current default LoRA target modules for Phi are incompatible with the latest versions of these models and the error is silent, leading to poor LoRA fine-tuning performance.
This PR updates the default target modules to match the new model architecture. 
```python
>>> from transformers import AutoModelForCausalLM
>>> model = …
```
> Fix LoRA module mapping for Phi models

- src/peft/config.py
- tests/test_config.py
This PR introduces a new constructor `PeftConfig.from_peft_type`that accepts a set of kwargs. The appropriate config class is determined by the `peft_type` argument. The logic for this was already buried within `from_pretrained`, so I've done a small refactor to pull that out into its own method.
Usage is as follows:
```
>>> from peft import PeftConfig
>>> peft_kwargs = {"peft_type": "LORA", "r": 8, "lora_alpha": 16}
>>> peft_config = PeftConfig.from_peft_type(**peft_kwargs)
>>> print(type(peft_config))
<class 'peft.tuners.lora.config.LoraConfig'>
```
I am new to contributing to this repo, so please let me know which PR steps I am missing (e.g., do I need to version bump in `setup.py`, or add any further documentation?)
> Add generic PeftConfig constructor from kwargs

- src/peft/utils/save_and_load.py
Fix a breaking change in the recent release, I made a new PR as I messed up the commit history on the previous PR
cc @sayakpaul @pacman100
> Fix breaking change 

- src/peft/utils/constants.py
Here's what the model architecture looks like with my proposed target modules:
```
>>> get_peft_model(model, ia3_config)
PeftModelForCausalLM(
(base_model): IA3Model(
(model): PhiForCausalLM(
(model): PhiModel(
(embed_tokens): Embedding(51200, 2560)
(embed_dropout): Dropout(p=0.0, inplace=False)
(layers): ModuleList(
(0-31): 32 x PhiDecoderLayer(
(self_attn): PhiAttention(
(q_proj): Linear(
(base_layer): Linear(in_features=2560, out_features=2560, bias=True)
(ia3_l): ParameterDict(  (default): Parameter containing: [torch.FloatTensor of size 2560x1])
)
(k_proj): Linear(in_features=2560, out_features=2560, bias=True)
(v_proj): Linear(
(base_layer): Linear(in_features=2560, out_features=2560, bias=True)
(ia3_l): ParameterDict(  (default): Parameter containing: [torch.FloatTensor of size …
```
> Add IA3 Modules for Phi

- src/peft/peft_model.py
- tests/test_adaption_prompt.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_multitask_prompt_tuning.py
- tests/test_tuners_utils.py
- tests/testing_common.py
A small PR for adding positional arguments to the generate method for `PeftModelForCausalLM`. The motivation is that `PeftModel` classes like `PeftModelForCausalLM` should feel more like a wrapper for `AutoModel` and shouldn't break existing code which uses positional args. Given that the messy internals of input processing are handled in the `prepare_inputs_for_generation` method, I think this is a safe feature. Also, it looks like `PeftModelForSeq2SeqLM` needs some refactoring for the prompt learning methods (to shift logic from `.generate` to `prepare_inputs_for_generation`), so I'm leaving that refactoring + positional args support to another PR.
> Add positional args to PeftModelForCausalLM.generate

- src/peft/utils/save_and_load.py
Without the fix:
```python
from peft import PeftModel
from diffusers import UNet2DConditionModel
base_unet = UNet2DConditionModel.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="unet")
toy_id = "sayakpaul/toy_peft_model"
model = PeftModel.from_pretrained(base_unet, toy_id, use_safetensors=True, subfolder="toy", adapter_name="toy")
```
won't work.
> [Hub] fix: subfolder existence check

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/ia3/layer.py
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/oft/layer.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
- tests/testing_common.py
Right now, merging of adapters weights such as LoRA and IA³ is not idempotent. This means that if a user calls `merge` multiple times, the resulting weights will be different each time because the delta weights are added again and again.
This fix checks that only those adapters are merged that are not yet merged. Also, gives a more precise warning:
- Say when there is nothing to merge.
- If there are some adapters to merge, only mention those
This bug is more subtle than it may seem at first, since we sometimes merge implicitly without the user necessarily being aware of it (e.g. when calling `merge_and_unload`). Therefore, this bug can occur quite easily, even if the user does not explicitly call `merge` twice in a row.
> FIX: Make merging of adapter weights idempotent

- src/peft/tuners/lora/layer.py
- tests/test_stablediffusion.py
Fixes https://github.com/huggingface/diffusers/issues/6809
Indeeed `copy` does not exist in PyTorch 🤯 one needs to use `clone()` .. that code path was never tested so I added some CI tests for that so that it'll never happen in the future
cc @pacman100 @apolinario
> [`core`] fix critical bug in diffusers

- src/peft/peft_model.py
Hi, PEFT team!
I noticed a small bug when I was trying to save LoRA for SDXL UNet model, loaded with `from_single_file` method. 
Apparently, `from_single_file` does not add `_name_or_path `  to the child model config (at least for `diffusers==0.26.0).`
```python
from diffusers import StableDiffusionXLPipeline
from peft import get_peft_model, LoraConfig
pipe = StableDiffusionXLPipeline.from_single_file(
"/data/checkpoints/civitai/sdxl/realvisxlV30Turbo_v30Bakedvae.safetensors"
)
config = LoraConfig(
target_modules=["conv_in"],
lora_alpha=8,
r=8
)
pipe.unet = get_peft_model(pipe.unet, config, adapter_name="default")
pipe.unet.save_pretrained("./unet")
```
```
...
File /opt/conda/envs/peft/lib/python3.8/site-packages/peft/peft_model.py:782, in PeftModel.create_or_update_model_card(self, …
```
> Fixed saving for models that don't have _name_or_path in config

- docs/source/_toctree.yml
- docs/source/developer_guides/contributing.md
- docs/source/developer_guides/custom_models.md
- docs/source/developer_guides/lora.md
- docs/source/developer_guides/low_level_api.md
- docs/source/developer_guides/mixed_models.md
- docs/source/developer_guides/quantization.md
- docs/source/developer_guides/troubleshooting.md
- docs/source/package_reference/multitask_prompt_tuning.md
- docs/source/package_reference/peft_model.md
- src/peft/mixed_model.py
This PR adds a batch of minor docs improvements that include:
- make `toctree` titles more concise and descriptive
- provide numbered steps to follow in `contributing.md`
- add pro/con table to `low_level_api` doc so its easy to skim at first glance
- add methods/functions discussed in the docs to the API section
> [docs] Doc maintenance

- src/peft/tuners/lora/tp_layer.py
Addresses: https://github.com/huggingface/peft/pull/1435#discussion_r1479110527
Fixes a breaking change introduced by #1435 
since `is_paralle_a` is a public attribute, it is a breaking change to completely remove it as some users might be using it already 
> [`core`/`TPLinear`] Fix breaking change

- tests/test_custom_models.py
- tests/testing_common.py
Many of the common tests are skipped because of lines such as:
```python
if config_cls not in (LoraConfig, IA3Config):
return
```
These lines were often added before we had more PEFT methods like OFT, LoHa, etc. However, these new methods should also pass the common tests. Therefore, I relaxed many of these conditions so that they would not skip the new methods.
Note:
There were a handful of test cases that failed. I added TODO comments for those, as it was unclear to me why they failed. As investigating this could take some time, I chose not to fix those cases in this PR.
> TST: Improve test coverage by skipping fewer tests

- .github/workflows/build_docker_images.yml
- docker/peft-gpu-bnb-latest/Dockerfile
- docker/peft-gpu-bnb-source/Dockerfile
Fixes the correct bnb installation commands after a big refactor on bitsandbytes
> Update Dockerfile to reflect how to compile bnb from source

- src/peft/auto.py
- tests/test_auto.py
Fixes #1430
When Using `AutoPeftModel.from_pretrained`, there is a check to see if a tokenizer can be found. This check will include a search for the tokenizer on HF Hub. However, when the model is stored locally, the path may not be a valid HF Hub repo ID. In that case, an error is raised by `huggingface_hub`.
This PR consists of catching that error, and assuming that if the error occurs, the tokenizer does not exist. This resolves the issue.
Note
We do have tests for `AutoPeftModel.from_pretrained`, so why did they not catch the error? I think there was a mistake in the tests. The tests did something like this:
```python
model_id = "peft-internal-testing/tiny-OPTForCausalLM-lora"
model = AutoPeftModelForCausalLM.from_pretrained(model_id)
with tempfile.TemporaryDirectory() as …
```
> FIX Loading with AutoPeftModel.from_pretrained

- src/peft/utils/other.py
1. When using DeepSpeed ZeRO Stage-3 with ZeRO init enabled, the `deeepcopy` performed in `ModulesToSaveWrapper` class doesn't work as expected and creates a new module with 0 parameters. As such, this results in following error when training:
```
assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
AssertionError    return self.modules_to_save[self.active_adapter](*args, **kwargs)
File "/raid/sourab/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
: {'id': 249, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {451}, 'ds_tensor.shape': torch.Size([0])}
```
2. This PR resolves this issue. To …
> Support `modules_to_save` config option when using DeepSpeed ZeRO-3 with ZeRO init enabled.

- src/peft/auto.py
- src/peft/utils/other.py
- src/peft/utils/save_and_load.py
Resolves #1452
If users enable offline mode, don't perform checks for files on HF Hub, as they would fail.
> FIX Honor HF_HUB_OFFLINE mode if set by user

- README.md
Links to the Space and docs instead because GitHub doesn't support embedding a Space with `iframe`.
> [docs] Remove iframe

- src/peft/tuners/lora/model.py
- src/peft/utils/merge_utils.py
Fixes a typo in the docstring that is causing `build_pr_documentation` test to fail in #1423
> [docs] Docstring typo

- src/peft/utils/other.py
As discussed offline, a follow up PR to: https://github.com/huggingface/peft/pull/1454 
As other errors might be raised such as : https://github.com/huggingface/peft/pull/1414#issuecomment-1925821921 I propose to simply silently ignore the raised exceptions in case users face a different exception than the ones we listed from HF hub
> [`core` / `get_peft_state_dict`] Ignore all exceptions to avoid unexpected errors

- src/peft/tuners/adaption_prompt/utils.py
Currently the adaptation prompt slow tests are failing on transformers main due to a recent refactor to add compatibility with static cache. https://github.com/huggingface/transformers/pull/27931 
That PR broke the adaptation prompt forward pass, as `module.rotary_emb` forward pass now have `position_ids` as a required argument, thus breaking the current impmelementation of llama roatary embedding as we don't pass position_ids in PEFT.
In addition, cos / sin are now directly indexed through that method, therefore we don't need to call our method that also indexes cos / sin with `positon_ids`. As computing the query states given cos / sin is a one-liner, I slighlty modified the logic in `llama_compute_query_states` to make sure the forward pass works fine with transformers main
cc …
> [ `Adaptation Prompt`] Fix llama rotary embedding issue with transformers main

- .github/workflows/tests-main.yml
As per title and as discussed offline, let's run CIs on transformers main, only on push PEFT main branch in order to check bugs such as https://github.com/huggingface/peft/pull/1459 early.
IMO for that workflow, no need to make things complicated, let's just test it on a speciifc python / OS version
> [`CI`] Add CI tests on transformers main to catch early bugs

- pyproject.toml
- tests/regression/test_regression.py
- tests/test_adaption_prompt.py
- tests/test_auto.py
- tests/test_common_gpu.py
- tests/test_config.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/test_gpu_examples.py
- tests/test_hub_features.py
- tests/test_initialization.py
- tests/test_lora_megatron.py
- tests/test_low_level_api.py
- tests/test_mixed.py
- tests/test_multitask_prompt_tuning.py
- tests/test_poly.py
- tests/test_stablediffusion.py
- tests/test_tuners_utils.py
- tests/testing_common.py
Plain assertions are easier to debug than Unittest `self.assert*`s due to Pytest's assertion rewriting.
Similar to https://github.com/huggingface/accelerate/pull/2420, this was done via [codemod-unittest-to-pytest-asserts](https://github.com/akx/codemod-unittest-to-pytest-asserts) and `ast-grep`.
Sibling of https://github.com/huggingface/trl/pull/1301.
> Use plain asserts in tests

- src/peft/tuners/lora/model.py
- src/peft/utils/merge_utils.py
- tests/testing_common.py
1. In my experiments, I found that pruning task tensors based on magnitude followed by weighted sum to perform better in comparison to dare_linear or ties. This PR add a new merging method `magnitude_prune` which first prunes the task tensors to remove small values and retain top_k values based on the param `density`. After this, a weighted sum is computed and returned.
> add `magnitude_prune` merging method

- docs/source/_toctree.yml
- docs/source/developer_guides/model_merging.md
- docs/source/package_reference/merge_utils.md
A guide to new model merging methods introduced in #1364.
todo:
> [docs] Model merging

- src/peft/utils/other.py
- tests/test_adaption_prompt.py
- tests/test_auto.py
- tests/test_decoder_models.py
- tests/testing_common.py
Some tests would not succeed on MPS devices because `bfloat16` is not supported. This makes them get skipped instead.
On a similar note, tests that are not applicable (e.g. generated via a `parametrized` matrix and should have been skipped) no longer seem to quietly pass, but are instead marked `skip`.
It also fixes up the rtype for `infer_device` to always be a string – previously, it would return a string, or in the case of `mps`, a `torch.device()`.
Sibling of #1448, since I got frustrated trying to run tests on my Apple Silicon device and figuring which ones of them are actual failures.
> Make tests succeed more on MPS

- src/peft/tuners/adaption_prompt/utils.py
As per title, this PR makes our new workflow that runs CI on transformers main happy ! - follow up work from #1461 to cover all usecases
> [`CI`] Fix adaptation prompt CI on transformers main

- src/peft/utils/peft_types.py
Docstring shows a missing underscore at TaskType "Causal LM"
> Update docstring at peft_types.py

- .pre-commit-config.yaml
- docs/source/developer_guides/contributing.md
This PR adds a [pre-commit](https://pre-commit.com/) configuration, so developers may opt in to running `ruff` and `ruff-format` as a pre-commit hook.
Should reduce the need for "fix lint" commits and `check_code_quality` CI failures.
Sibling of https://github.com/huggingface/accelerate/pull/2451
> Add pre-commit configuration

- .github/workflows/tests-main.yml
- .github/workflows/tests.yml
Let's run the whole tests CI only when relevant files are changed, for minor PRs such as doc PR, there should be no need to run the testing suite IMO
Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> ENH [`CI`] Run tests only when relevant files are modified

- .github/workflows/nightly-bnb.yml
This PR fixes the current bnb workflow that is broken due to an incompatible pytest version with transformers leading to transformers tests being silently skipped: https://github.com/huggingface/peft/actions/runs/7945902843/job/21693054056
cc @pacman100 @BenjaminBossan @Titus-von-Koeller FYI
> FIX [`CI` / `bnb`] Fix failing bnb workflow

- src/peft/peft_model.py
This PR fixes the current failing CI on transformers main. 
Recent commits on transformers main introduced a new way to compute the position ids of the input embeddings or input ids. Cos / Sin for RoPE do not use `position_ids` anymore but uses `cache_position` which now can be passed in case one uses cache, which is the case for prompt encoder models in PEFT. 
The fix is simply to pop `"cache_position"` from `model_kwargs` as `cache_position` is automatically re-computed on architectures that uses it, such as llama (only llama for now supports `cache_positon`), in the model's forward pass: https://github.com/huggingface/transformers/blob/593230f0a1150ea9c0477b9d859f25daf73c8c33/src/transformers/models/llama/modeling_llama.py#L956 
With this simple fix, I can confirm all failing tests …
> FIX [`PromptTuning`] Simple fix for transformers >= 4.38

- .github/workflows/test-docker-build.yml
- .github/workflows/tests-main.yml
Hi !
I would like to enhance the current way of testing docker build workflow, right now I need to manually change the rules for triggering the build docker image job to test if a PR leads to potential failure on docker build. In this PR I propose to simply trigger a simple workflow that just builds (without pushing) docker images that are modified by a PR
> ENH: [`CI` / `Docker`]: Create a workflow to temporarly build docker images in case dockerfiles are modified

- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/mixed/model.py
- tests/test_custom_models.py
Resolves #1485, but note that some additional solutions are mentioned in thet issue.
This checks that when unloading a PEFT model, if the ModulesToSaveWrapper contains a tuner module, it is correctly unloaded. The unloaded model should not have PEFT layers at the end.
> Fix issue with unloading double wrapped modules

- src/peft/tuners/adaption_prompt/utils.py
https://github.com/huggingface/transformers/pull/29109 changed the output shape of cos / sin generated by the rotary embedding, by considering the case of batched inference. This PR fixes it
> FIX: [`CI` / `Adaptation Prompt`] Fix CI on transformers main

- src/peft/tuners/adalora/layer.py
If the data types are not converted appropriately, the following errors may occur:
```bash
File "/home/user/miniconda3/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 691, in forward
query_states = self.q_proj(hidden_states)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/miniconda3/lib/python3.11/site-packages/peft/tuners/adalora/layer.py", line 175, in forward
result += (dropout(x) @ (lora_A * …
```
> covert SVDLinear dtype

- src/peft/utils/other.py
- tests/test_other.py
Resolves #1492
This PR is for user convenience. When they try to pass the wrong type to `modules_to_save`, they will now get an early error message, instead of getting an obscure error when calling `forward` later.
Note:
The reason why `ModulesToSaveWrapper` cannot support `ModuleDict` et al. is because it tries to call forward on the original or copied module, but these modules don't implement a `forward` method.
> Raise error on wrong type for to modules_to_save

- src/peft/peft_model.py
- tests/testing_common.py
Resolves #1501
There was a big that after using the `disable_adapter` context, the prepare method was not correctly restored, meaning that generations were incorrect once the context was exited. This is now fixed.
> FIX Bug in prompt learning after disabling adapter

- src/peft/tuners/lycoris_utils.py
- tests/test_custom_models.py
- tests/testing_common.py
There was a small bug when merging the LoHa and LoKr tuners with `safe_merge=True` due to a missing `clone` call. This is now fixed.
Furthermore, the test coverage for merging with LoHa and LoKr has been extended, as there were a few tests where these methods were excluded unnecessarily.
> FIX Safe merging with LoHa and LoKr

- .github/workflows/build_docker_images.yml
As discussed offline cc @glegendre01
> ENH: [`Docker`] Notify us when docker build pass or fail

- setup.py
- src/peft/__init__.py
Note that we did not set a dev version for 0.8.2, so this PR goes directly from 0.8.2 to 0.9.0.
No deprecated code or similar to change.
> Bump versions for release 0.9.0

- docs/source/accelerate/deepspeed.md
as discussed offline and fixes https://github.com/huggingface/peft/issues/1418
> FIX [`Docs`/ `bnb` / `DeepSpeed`] Add clarification on bnb + PEFT + DS compatibilities

- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
See #1524
This is similar to how we already expose the weight attribute.
> Expose bias attribute on tuner layers

- src/peft/mixed_model.py
- src/peft/peft_model.py
> docs: highlight difference between num_parameters() and get_nb_trainable_parameters() in PEFT

- src/peft/tuners/prompt_tuning/config.py
- tests/test_initialization.py
When `prompt_tuning_init==TEXT` is set, there are some args needed to be provided. For instance, `tokenizer_name_or_path` should be set to some tokenizer name or path, failing which would result in errors such as
```
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/tokenizer_config.json
```
tokenizer_name_or_path is taken as `None`. Such errors can be handled and reported meaningfully post config initialization and this PR makes that contribution.
> fix: fail when required args not passed when prompt_tuning_init==TEXT

- docs/source/developer_guides/quantization.md
Line 59 - trainning to training
Line 80 - LoraConfig missing a comma after Lora Dropout Line 141 - quantizaion to quantization
> Fixed minor grammatical and code bugs

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/feature_extraction/peft_lora_embedding_semantic_similarity_inference.ipynb
- examples/fp4_finetuning/finetune_fp4_opt_bnb_peft.py
- examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb
- examples/int8_training/Finetune_opt_bnb_peft.ipynb
- examples/int8_training/fine_tune_blip2_int8.py
- examples/int8_training/peft_adalora_whisper_large_training.py
- examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb
- examples/multi_adapter_examples/PEFT_Multi_LoRA_Inference.ipynb
- examples/sft/train.py
- examples/sft/utils.py
- src/peft/tuners/lora/model.py
- tests/regression/test_regression.py
- tests/test_common_gpu.py
- tests/test_gpu_examples.py
- tests/test_tuners_utils.py
Don't pass `load_in_4bit` or `load_in_8bit` to `AutoModel*.from_pretrained`, as it is deprecated. Instead, pass the appropriate `BitsAndBytesConfig` to the `quantization_config` argument of `from_pretrained`.
> MNT: Use BitsAndBytesConfig as load_in_* is deprecated

- docs/source/developer_guides/lora.md
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/tuners_utils.py
- tests/test_decoder_models.py
This PR adds the ability to duplicate layers in a model according to a layer map
and then fine tune separate lora adapters for the layers post duplication. This
allows expanding a model to larger model and then fine tuning that model with
very little extra memory compared to the original smaller model.
> Add support for layer replication in LoRA

- docs/source/developer_guides/lora.md
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- src/peft/utils/integrations.py
- tests/test_common_gpu.py
- tests/test_gpu_examples.py
- tests/test_initialization.py
Adds support for DoRA on 4bit and 8bit quantized models with bitsandbytes. Merging also works, with the usual caveats for quantized weights (results are not 100% identical), but it's not worse than vanialla LoRA.
I did some quick tests and could see the expected memory savings with bnb. Same as with DoRA on non-quantized layers, using DoRA on quantized layers leads to a moderate increase in runtime.
> QDoRA: Support DoRA with BnB quantization

- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
> Feat: add support for Conv2D DoRA

- pyproject.toml
Just a small addition so that we know which tests are the slowest. This can be helpful to identify tests to optimize, or to catch early if a new PR adds a particularly slow test.
> TST Report slowest tests

- docs/source/accelerate/deepspeed.md
- docs/source/accelerate/fsdp.md
- examples/sft/README.md
- examples/sft/configs/deepspeed_config_z3_qlora.yaml
- examples/sft/configs/fsdp_config_qlora.yaml
- examples/sft/run_peft_qlora_deepspeed_stage3.sh
- examples/sft/run_peft_qlora_fsdp.sh
- examples/sft/train.py
- examples/sft/utils.py
- src/peft/peft_model.py
- src/peft/utils/other.py
1. With the latest bitsandbytes version, the storage data type of 4-bit params is no longer fixed to `unit8` as users can now use half or full precision in scenarios like FSDP+QLoRA. As such, this PR fixes the calculation of the number of parameters.
> Changes to support fsdp+qlora and dsz3+qlora

- docs/source/developer_guides/lora.md
- src/peft/peft_model.py
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- tests/test_common_gpu.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_common.py
This PR tries to revive the work by Sourab in #903. The core logic is the same between the two PRs. This one should be more complete.
The main idea is to allow the user to mix different LoRA adapters in the same batch. This is useful when the user wants perform inference with a batch that uses different LoRA adapters. Without this, each batch would have to be restricted to the same LoRA adapter(s).
This PR should encompass:
- all task types
- all LoRA layer types
- bnb layers
Extensive tests were added, as well as documentation.
> FEAT Mixing different LoRA adapters in same batch

- .github/workflows/test-docker-build.yml
- docker/peft-cpu/Dockerfile
This fixes the issue we had with the test-docker-build workflow, as stated by the dependabot [here](https://github.com/huggingface/peft/security/dependabot/1) we should make use of env variables to avoid issues
cc @glegendre01 @sayakpaul @pacman100 @BenjaminBossan
> FIX [`CI`] Fix test docker CI

- docs/source/developer_guides/lora.md
- docs/source/developer_guides/quantization.md
- tests/test_gpu_examples.py
Relates to #1525
_Don't merge this, some GPU tests are failing_
Unfortunately, the docs I wrote about how to use LoftQ were incorrect, based on a misunderstanding I had. In reality, it is quite a bit more involved to get LoftQ working, requiring a complete roundtrip first loading a non-quantized model with LoftQ, saving the LoRA weights and the modified base model, loading the just stored base model again but this time with quantization, and finally loading the LoftQ-initialized adapter on top. The docs now link to the example which demonstrates how to move through these steps.
The unit tests have been adjusted to go through these same steps but now most of them fail, i.e. the quantization error is _greater_ with LoftQ than without. This needs to be investigated.
> Fix LoftQ docs and tests

- docs/source/developer_guides/lora.md
- src/peft/config.py
A few unrelated things I noticed:
- Typos in docs
- Add mention that DoRA now supports Conv2d
- Re-raise a caught exception (to not hide original error)
> FIX Minor issues in docs, re-raising exception

- docs/source/tutorial/peft_integrations.md
Add a short section on the usage of `pipeline` from transformers.
Note that for some reason, the diff looks much bigger on GH than it actually is -- in the last paragraph, only a single word was removed.
> DOC: Short section on using transformers pipeline

- src/peft/import_utils.py
Fixes #1576 
Adding @cache to the functions in `import_utils` results in a constant time for LORA loading, regardless of the length of python path. Have verified this using a python path with 50,000 directories - previously the lora load time was 259 seconds, now it's down to a constant time of 1.3 seconds 👍🏻 
With some flamegraphs to prove! Before:
After:
> [feat] Add `lru_cache` to `import_utils` calls that did not previously have it

- examples/sft/train.py
- examples/sft/utils.py
1. Fixes https://github.com/huggingface/peft/issues/1598
> fix the torch_dtype and quant_storage_dtype

- examples/loftq_finetuning/LoftQ_weight_replacement.ipynb
- tests/regression/test_regression.py
- tests/test_common_gpu.py
Several tests were using `bnb_4bit_compute_type` but the argument should be called `bnb_4bit_compute_dtype`. Now the 
correct name is used.
This change should not affect the tests, because they were passing the default value anyway. Therefore, the fact that this argument was passed incorrectly (and thus, presumably, ignored) should not affect the results.
Also, in some tests `quantization_config=BitsAndBytesConfig(load_in_4bit=True)` was passed as argument to `BitsAndBytesConfig` due to an overeager search and replace in #1552. Fixing those changes the test outcome but locally they still passed for me.
It is a bit unfortunate that this sort of typo passes completely silently.
> FIX: bnb config wrong argument names

- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
- tests/test_gpu_examples.py
Previously, code was not transposing weights when calculating the norm.
In addition, update some DoRA tests to use BitsAndBytesConfig.
> FIX Make DoRA work with Conv1D layers

- src/peft/peft_model.py
- src/peft/utils/save_and_load.py
- tests/test_custom_models.py
Resolves #1605
When users pass `ignore_mismatched_sizes=True` to `PeftModel.from_pretrained`, the mismatched tensors will be ignored instead of raising an error. This is in line with how transformers handles this argument.
> FEAT: Allow ignoring mismatched sizes when loading

- src/peft/peft_model.py
PEFT lists torch version as >= 1.13.0 but `.itemsize` is only torch 2.1+. This is unexpectedly breaking for users on torch 2.0.
https://github.com/huggingface/peft/blob/main/setup.py#L63
> itemsize is torch>=2.1, use element_size()

- src/peft/peft_model.py
- src/peft/tuners/lora/model.py
- src/peft/utils/other.py
- tests/test_custom_models.py
Resolves #1574.
Previously, we had the bug that if we had multiple adapters, some with
`modules_to_save` and others without, when trying to switch to an adapter
without `modules_to_save`, the `ModulesToSaveWrapper` would raise an error
because it cannot find that adapter. Now, when it detects this, it is
just disabled (so it uses the original weight).
Moreover, we had the issue that when we were using classes such as
`PeftModelForSequenceClassification`, we implicitly added the classifier
layers to `model.modules_to_save`. However, this would only add a new
`ModulesToSaveWrapper` instance for the first adapter being initialized.
When initializing a 2nd adapter via `add_adapter`, this information was
ignored. To fix this, I now update the `peft_config.modules_to_save` to
explicitly add the …
> FIX Multiple adapters and modules_to_save

- src/peft/peft_model.py
Should fix the error introduced by #1630.
AFAICT, `element_size` should be called on the parameter, not the `dtype`. Unfortunately, I had issues getting older PyTorch versions to work with bnb, so I haven't tested the initial issue.
To be safe, I also re-added the previous code path using `itemsize`, although it might be unnecessary (we would have to check the PyTorch code to verify when the different attributes/methods were added).
> FIX Correctly call element_size

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/int8_training/peft_adalora_whisper_large_training.py
- examples/loftq_finetuning/train_gsm8k_llama.py
- examples/lora_dreambooth/train_dreambooth.py
- examples/oft_dreambooth/train_dreambooth.py
- examples/stable_diffusion/train_dreambooth.py
`Repository` is a deprecated feature in `huggingface_hub`. It is more robust to use the HTTP-based methods from `HfApi` instead. [Here is a doc page explaining why it's better](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http). Main reasons are 1. don't need to clone a repo to push files 2. faster upload speed 3. don't need git/git+lfs configured locally.
`transformers` switched to use `HfApi` is all their training scripts in Aug 23' (see https://github.com/huggingface/transformers/pull/25095) without breaking. Let's do the same for `peft`!
I also removed the `get_full_repo_name` redefinition, in favor of `create_repo(repo_name, exists_ok=Ture).repo_id` => no need to infer the explicit repo_id before creating_it.
**Disclaimer:** I did not test those changes myself. Should …
> Don't use deprecated `Repository` anymore

- docs/source/tutorial/peft_integrations.md
- Typo: wrong variable name
- Typo: `disable_adapter` -> `disable_adapters`
- Remove link to `PeftModel.disable_adapter`, because it's not the same method
- Mention the `enabble_adapters` method too
> FIX Errors in the transformers integration docs

- docs/source/conceptual_guides/oft.md
#1326 
Update the `img_url` from `github.com` to `raw.githubusercontent.com` to ensure that the figures are displayed correctly in [conceptual_guides/oft](https://huggingface.co/docs/peft/main/en/conceptual_guides/oft)
> update figure assets of BOFT

- src/peft/peft_model.py
This PR replaces `trainable%: 0.5916145025956931` with `trainable%: 0.5916` as it's done already in `src/peft/mixed_model.py`
Probably `.2f` is more than enough, but since the other one uses `.4f` using that.
> print_trainable_parameters - format `%` to be sensible

- src/peft/tuners/adalora/model.py
- src/peft/tuners/boft/model.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/poly/model.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
There was a bug for some models like IA3, LoHa, etc., where calling `set_adapter` would not correctly update the `active_adapter`. This is now fixed.
Note that this is _not_ about the `active_adapter` attribute on `PeftModel` or layers, which are handled separately.
This PR also ensures that `LoraModel`, `IA3Model`, etc. consistently use `self.active_adapters`, not `self.active_adapter`. The latter should be treated more like a private attribute (but this isn't changed for backwards compatibility).
> FIX: Bug with handling of active adapters

- .github/workflows/build_docker_images.yml
- .github/workflows/nightly-bnb.yml
- docker/README.md
- docker/peft-gpu-bnb-multi-source/Dockerfile
bitsandbytes has now a new branch `multi-backend-refactor`: https://github.com/TimDettmers/bitsandbytes/tree/multi-backend-refactor to conduct experiments and push forward the efforts for cross-platform support for bnb
This PR extends the current existing testing suite to make sure we also conduct the same tests on bitsandbytes compiled on that branch 
cc @Titus-von-Koeller @pacman100 @BenjaminBossan
> ENH: Add multi-backend tests for bnb

- .github/workflows/tests.yml
- src/peft/helpers.py
cc @pacman100 @BenjaminBossan 
Freeze the mac-os to `mac-os-12` temporarly, see: https://github.com/actions/setup-python/issues/850
> FIX / Workflow: Fix Mac-OS CI issues

- tests/test_common_gpu.py
- tests/test_decoder_models.py
Using the version from HuggingFaceM4 broke our tests because it was updated. Although the update is reverted, we still better switch to this version, which is explicitly for testing and should be stable.
> FIX Use trl version of tiny random llama

- src/peft/utils/loftq_utils.py
Resolves #1665.
We accidentally added code in `loftq_utils.py` that eagerly imports bnb, which we want to avoid to prevent CUDA from being initialized too early.
> FIX: Don't eagerly import bnb for LoftQ

- .github/workflows/build_docker_images.yml
As per title, we were not posting on slack when the docker image build fails, this PR enables it
> FIX / Workflow: Always notify on slack for docker image workflows

- docker/peft-gpu/Dockerfile
> FIX: upgrade autoawq to latest version

- src/peft/tuners/lora/layer.py
When DoRA weights are initialized in float16 on CPU and when an older PyTorch version is being used (<2.2), there is an error because the the operation is not supported for float16 on CPU. This commit temporarily converts the LoRA weights to float32 beforehand if they're in float16.
Of course, when the user tries to train or predict with this model on CPU, they will still encounter errors. However, in certain situations, only the initialization might be on CPU and later it is moved to GPU. This could be some framework code that the user has no control over, as in #1597. Therefore, it's good to have this safety hatch.
Note that since our CI uses the latest PyTorch version, we cannot run a test for this, as the latest PyTorch runs no matter what.
> FIX: Initialize DoRA weights in float32 if float16 is being used

- docs/source/developer_guides/troubleshooting.md
- docs/source/package_reference/peft_model.md
- src/peft/__init__.py
- src/peft/mixed_model.py
- src/peft/peft_model.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
- tests/test_tuners_utils.py
This PR adds a new feature to PEFT models that allows to better understand the status of adapter(s) on the model. Quoting from the doc entry that I added:
> Sometimes, the PEFT model can end up in a bad state, especially when handling multiple adapters. There can be some confusion around what adapters exist, which one is active, which one is merged, etc. To help investigate this issue, you can call the `peft.PeftModel.get_layer_status` and the `peft.PeftModel.get_model_status` methods. The first one gives you a detailed overview about the adapters for each targeted layer. The latter one gives you a high-level overview about the model status.
**Example PEFT**:
```python
>>> from transformers import AutoModel
>>> from peft import get_peft_model, LoraConfig
>>> model_id = …
```
> FEAT Show adapter layer and model status

- docs/source/task_guides/prompt_based_methods.md
Fixes #1685 
Using correct sequence to determine initial length will allow for proper padding to be applied.
> Fixing the example by providing correct tokenized seq length

- tests/__init__.py
Right now, a lot of tests fail when applying torch.compile to PEFT models. One of the main reasons is that attribute checks (e.g. `if self.foo`) on `nn.Module`s are not correctly considered.
This PR sets an experimental flag that should fix this. However, this is not public PyTorch API (yet) and incurs a performance penalty. Still, it's interesting to see how this affects our tests.
More context:
https://github.com/pytorch/pytorch/issues/124717#issuecomment-2083235776
> Set experimental dynamo config for compile tests

- docs/source/_toctree.yml
- docs/source/package_reference/helpers.md
- src/peft/helpers.py
- tests/test_helpers.py
After internal discussion, we decided to add this convenience function.
```python
>>> from peft.helpers import check_is_peft_model
>>> check_is_peft_model("gpt2")
False
>>> check_is_peft_model("peft-internal-testing/gpt2-lora-random")
True
>>> check_is_peft_model("peft-internal-testing/non-existing-model")
False
>>> check_is_peft_model("path/to/local/model/also/works")
```
> FEAT Helper to check if a model is a PEFT model

- docs/source/developer_guides/troubleshooting.md
This PR fixes the guide that explains saving embedding layers besides adapter parameters. The `save_adapter` method doesn't exist, should be `save_pretrained`.
> Fix docs typo

- examples/sft/run_peft_multigpu.sh
the blank after \ makes HFparser to confuse.
with the blank, the example makes an error that the blank itself remains untreated as a argument.
> revise run_peft_multigpu.sh

- .github/workflows/build_docker_images.yml
Uses the new workflow from `hf-workflows` in order to post nice messages on slack with emojis when the workflow fails !
> Workflow: Add slack messages workflow

- docs/source/_toctree.yml
- docs/source/developer_guides/checkpoint.md
Document the PEFT checkpoint format, with a focus on how to convert to this format.
[Link to rendered docs](https://moon-ci-docs.huggingface.co/docs/peft/pr_1717/en/developer_guides/checkpoint#checkpoint-format).
This is a bit of a brain dump, so let me know if there is more to add or to remove.
> DOC Document the PEFT checkpoint format

- src/peft/tuners/lora/layer.py
- src/peft/utils/integrations.py
- tests/test_gpu_examples.py
Resolves #1674
For some users, it is necessary to initialize the model on CPU, even when using BitsAndBytes, which requires a GPU eventually. Since DoRA requires to dequantize the BNB weights at initialization, we need to temporarily move the model corresponding weights to GPU. After dequantization, the weights are moved back to CPU.
> FIX Allow DoRA init on CPU when using BNB

- setup.py
- src/peft/__init__.py
Preparing for release of PEFT v0.11.0. AFAICT, there are no deprecations for this release.
> Release: v0.11.0

- src/peft/auto.py
- src/peft/config.py
- src/peft/mapping.py
- src/peft/peft_model.py
- tests/test_hub_features.py
- tests/test_other.py
addresses #1567 
changed name of parameter from `revision` to `base_model_revision` for clarity
can add unit tests if someone gives pointers to similar ones to extend
may need to add a model to `hf-internal-testing` with a base model with revision for these unit tests
> save and load base model with revision

- docs/source/developer_guides/model_merging.md
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/model.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_feature_extraction_models.py
- tests/testing_common.py
(Partially) Resolves: https://github.com/huggingface/peft/issues/1688
See https://github.com/huggingface/peft/pull/980 for context.
$(IA)^3$ adapters can't be combined. This option, however, is available for other PEFT adapters such as LoRA.
Implement `add_weighted_adapter` method for $(IA)^3$ models supporting only weighted average of adapters for now.
> Add add_weighted_adapter to IA3 adapters

- docs/source/developer_guides/troubleshooting.md
- src/peft/peft_model.py
- src/peft/tuners/vera/layer.py
- tests/test_tuners_utils.py
For each adapter, show all the devices of this adapter's parameters.
Also, while working on this, found a very minor bug in VeRA as its linear layer didn't implement its own `__repr__`.
> ENH Layer/model status shows devices now

- docs/source/developer_guides/troubleshooting.md
- src/peft/utils/save_and_load.py
- tests/test_vision_models.py
Fixes #1732
After loading a model that was trained with PEFT on a base model with some kind of batch norm layer, the loaded model should produce the same output. Right now, this does not happen.
The reason is that during training, buffers for running mean etc. are updated, but they are not saved when calling `save_pretrained` on the `PeftModel` instance. Normally in PEFT, we assume that during training, the base model parameters are kept constant, which is not the case with batch norm. We only save the PEFT parameters and assume that when the user loads the base model, all parameters are restored exactly. That way, the information in the buffers is lost completely.
This PR fixes this issue by saving the buffers of the batch norm layers. They are identified by checking for the presence of …
> DOC TST Document and test reproducibility with models using batch norm

- src/peft/tuners/lora/model.py
Without this fix, [test_hqq_lora_model_outputs](https://github.com/huggingface/peft/actions/runs/9184294503/job/25256361781) currently fails.
> FIX Use correct attribute name for HQQ in merge

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/boft/layer.py
- src/peft/tuners/ia3/layer.py
- src/peft/tuners/loha/layer.py
- src/peft/tuners/lokr/layer.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/tp_layer.py
- src/peft/tuners/oft/layer.py
- src/peft/tuners/poly/layer.py
- src/peft/tuners/tuners_utils.py
- src/peft/tuners/vera/layer.py
- tests/test_common_gpu.py
Resolves #1639
The issue is that so far, we made the assumption in PEFT that all adapter weights of a specific layer are on the same device. There can be cases where it is useful to have adapters on different devices. E.g. when a user loads a lot of LoRA adapters and wants to offload those not currently in use to CPU, they would not currently be able to do so.
With this PR, we add this possibility. To achieve this, when we update an adapter layer with a new adapter, we only move that specific adapter to the device of the base layer, will not touching the other loaded adapters.
While working on this, I discovered a small bug in VeRA when adding multiple adapters, which is now also fixed.
This PR has the potential to lead to unforeseen issues, so careful review is required. After merging …
> FIX Allow same layer adapters on different devices

- src/peft/tuners/boft/layer.py
Fixes [failing CI](https://github.com/huggingface/peft/actions/runs/9217614705/job/25359847525).
PR #1742 introduced the feature that adapters of the same layer can be on different devices. A new method was introduced that is responsible for moving the parameters related to a specific adapter in a consistent way.
In BOFT, however, one parameter was overlooked, `boft_P`. This parameter is not stored inside a `ParameterDict` or `ModuleDict`, hence it was not moved. The reason is (presumably) that this parameter is shared between all BOFT adapters, as it's always identical. However, this clashes with having different adapters on different devices.
To solve this, the parameter is now moved on the fly to the correct device during the forward pass.
Alternatively, we could store this parameter …
> FIX BOFT device error after PR 1742

- tests/regression/test_regression.py
These new methods were added but the regression tests were not extended yet. This PR adds regression tests for these methods. The regression artifacts have been pushed based on PEFT v0.11.1. The new tests pass locally.
> TST Add regression test for DoRA, VeRA, BOFT, LN Tuning

- docs/source/developer_guides/lora.md
As discussed internally - see: https://huggingface.slack.com/archives/C04L3MWLE6B/p1716846122314679
> Docs / LoRA: Add more information on `merge_and_unload` docs

- .github/workflows/torch_compile_tests.yml
- tests/test_torch_compile.py
Many of these tests require a GPU to run, so use custom runners.
Code was mostly copied from existing workflows, I hope that this works.
> CI Make torch compile tests run on GPU

- tests/test_common_gpu.py
Don't pass `load_in_8bit` to `AutoModel.from_pretrained`, instead use `BitsAndBytesConfig`.
There was already a PR to clean this up (#1552) but a slightly later PR (#1518) re-added this usage.
> MNT Remove deprecated use of load_in_8bit

- .github/workflows/torch_compile_tests.yml
See if this fixes the [error in the workflow](https://github.com/huggingface/peft/actions/runs/9363233367/job/25776705789).
> fatal: detected dubious ownership in repository at '/__w/peft/peft'
> FIX CI: Remove potentially problematic git command

- .github/workflows/tests-main.yml
As per title and discussed offline, this will send the results in our daily CI channel 
> ENH / Workflow: Notify on slack about peft + transformers main test results

- .github/workflows/torch_compile_tests.yml
To fix:
> `UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --report-log compile_tests.log`
> FIX CI: Install pytest-reportlog package

- .github/workflows/build_docker_images.yml
As discussed offline cc @BenjaminBossan
> ENH / Workflow: Use repository variable

- src/peft/peft_model.py
Requires to install transformers from source (so normal CI won't pick this up).
To replicate, run these tests:
```
pytest tests/test_multitask_prompt_tuning.py
pytest tests/test_decoder_models.py -k
"test_trl_internal_testing_tiny_random_LlamaForCausalLM and (prefix or prompt) and (generate or disable)"
```
This should result in 17 failing tests.
The issue is that `past_key_values` can now be an instance of `DynamicCache`. Therefore, just indexing into it won't work anymore. The solution is to check the type and if it's not a tuple, use the methods on the cache object instead.
> FIX Failing Llama tests due to new kv cache

- .github/workflows/nightly-bnb.yml
As per title and to avoid our CI silently passing
cc @Titus-von-Koeller @BenjaminBossan
> Workflow / Bnb: Add a mechanism to inform us if the import fails

- .github/workflows/nightly-bnb.yml
We should use `secrets` instead of `envs` otherwise we get empty strings
> Workflow: Fix broken messages

- .github/workflows/nightly-bnb.yml
All bitsandbytes nightly CI runs are currently [failing](https://github.com/huggingface/peft/actions/runs/9458512932/job/26054124989) with:
> Run python3 -m bitsandbytes
> /opt/conda/bin/python3: No module named bitsandbytes
This fix should hopefully solve this, but it's untested.
> CI Activate env to prevent bnb import error

- src/peft/mixed_model.py
What does this PR Do?
This PR removes the redundant import in the PeftMixedModel example and was confusing as raised here: #1824 Import was not required for the example, so removed it.
Fixes: #1824
> Fixed PeftMixedModel docstring example #1824

- Makefile
- setup.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/poly/router.py
We currently use ruff v0.2.2, which is quite far behind the latest version. This has the disadvantage that new contributors will often install the latest version of ruff and then get CI errors, even though they ran `make style`.
With this update, the discrepancy should go away. But if we merge this, all contributors may have to update their PRs. This is annoying but I think we need to do this sooner or later.
Here is the full list of changes:
- bump ruff version to ~0.4.8
- update the ruff commands in Makefile (ruff foo/ -> ruff check foo/)
- update coding style of two files that changed with the new ruff version
> MNT Upgrade ruff version to ~0.4.8

- src/peft/tuners/adalora/layer.py
- src/peft/tuners/tuners_utils.py
- tests/test_common_gpu.py
Locally, multiple AdaLoRA-related tests are failing. We did not catch this in the nightly run because the tests were missing the necessary pytest marker.
The issue is related to the change in #1742, which made it possible to load different adapters on different devices. Although that PR itself was sound, the problem is that for AdaLoRA, one of its parameters, `ranknum`, was not listed in the `other_param_names` and was thus not moved to the correct device. This oversight is now fixed and the GPU tests are now passing locally for me.
Note that this bug only occurred in the tests when loading a 2nd AdaLoRA adapter. At first I was confused because I thought that this is not supported (there is a check for that), but actually it's supported as long as the additional adapters are not …
> FIX: Adalora ranknum loaded on wrong device

- .github/workflows/nightly-bnb.yml
According to: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context when manipulating steps statuses, one should always use `steps.<step_id>.outputs` to retrieve the status. See also: https://stackoverflow.com/a/58003436 
> Workflow / FIX: Fix red status on our CI

- .github/workflows/nightly-bnb.yml
In #1859, we checked removing the import checks, but the single-GPU BNB multi-backend branch is still
[stuck](https://github.com/huggingface/peft/actions/runs/9540932758/job/26293392525#logs). Therefore, check commenting the next step instead.
Note: I only uncommented one step and commented the next. For some reason, the GitHub diff view is confused about that.
**Edit**: Tests are failing but for unrelated reasons, most likely because of numpy 2.0.
> CI testing BNB: remove single GPU tests

- .github/workflows/tests.yml
As a temporary workaround to numpy 2.0 breaking CI, downgrade it for `macos-12` and `windows-latest`.
> CI Downgrade numpy to <2.0 for Mac and Windows

- docs/source/developer_guides/custom_models.md
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
Resolves #1867
This is an experimental feature with a private API for now. If this feature finds adoption, I will work on adding an official API.
With this PR, we allow users to register their own LoRA layer types. This way, they can add their own support for hitherto unsupported layer types, say `nn.Conv3d` or `nn.LSTM`. Without this PR, they can only do that by creating a PR on PEFT with support for this new type and getting it merged.
The custom dispatch mechanism also allows users to override existing layer type mapping. This way, they can, for instance, provide their own `lora.Linear` layer type, instead of using the one from PEFT, to adapt `nn.Linear` layers.
The implementation required only very few changes because we already have a mechanism for dynamic dispatching for LoRA. It is …
> ENH: LoRA support for dynamically dispatching to custom layers

- src/peft/tuners/adalora/layer.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_feature_extraction_models.py
- tests/test_initialization.py
Resolves #1798 
There was an accidental change in a previous PR that initialized `lora_E` as normal, when it should be zeros. See the linked issue for context.
> FIX Init AdaLoRA to be identity transform

- src/peft/tuners/lora/layer.py
Resolves https://github.com/huggingface/accelerate/issues/2886
Possibly resolves
https://github.com/huggingface/peft/issues/896#issuecomment-2172455458
Some LoRA init methods need to access the base layer weight. Getting this access can fail or stall in distributed settings. For DeepSpeed, the weight is now gathered before trying to access it.
Note: Without DeepSpeed, this is a no-op and should thus not have any disadvantage. We don't have DS in our CI, so this is not tested.
I also made some small changes to OLoRA init to use `self.get_base_layer()` instead of `self.base_layer`.
> FIX Make special LoRA inits DeepSpeed compatible

- examples/sft/train.py
The function call `print_trainable_parameter()` in `examples/sft/train.py` didn't take account of `--use_peft_lora False` and finetune will fail in such case.   This PR bypass this print if this function cannot be found in the model.
> bypass print_trainable_parameter() if model is not peft model

- src/peft/tuners/boft/layer.py
This PR resolves #1877.  
The proposed change simply moves the import  of ``torch.utils.cpp_extension`` into the function ``get_fbd_cuda``.
> Fix early import of torch extension in BOFT

- .github/workflows/tests.yml
Currently, we have fail-fast enabled (the default). Although this is generally reasonable -- if a test fails in one setting, we probably get the same failure in other settings -- it is currently an impediment. This is because we get occasional timeouts when loading models from the Hub. With fail-fast enabled, if a single setting fails because of timeouts, all other runs are cancelled, even if they would have passed. Then we need to retrigger all of them again, creating even more pressure on the Hub. With fail-fast disabled, we give those other runs a chance to pass successfully.
> CI: Don't fail fast in test matrix

- tests/testing_common.py
The test is flaky on CI, so this PR increases the tolerance to hopefully fix the flakines. I cannot reproduce the error locally (neither on GPU nor CPU), so I'm not 100% sure if this tolerance is enough to make the test reliable.
> FIX TEST: Higher tolerance for AdaLoRA in test

- tests/test_common_gpu.py
Addresses test_4bit_lora_mixed_adapter_batches_lora allclose checks which are beyond current tolerance levels on certain configurations.
Fixes #1889.
Note: I would like to verify that this test succeeds on CI checks **prior to this change,** preferably with logs or something. Right now I'm not even sure if this test is executing in CI or not. If it is, I would like to investigate what causes this discrepancy between environments.
> test: bump absolute tolerance level in test

- tests/testing_common.py
See #1897 for more context. The test is still flaky, increasing tolerance further.
Example of a failed run:
https://github.com/huggingface/peft/actions/runs/9745363462/job/26893196728
No matter how often I run this locally, I can't reproduce :-/
> FIX TEST Even higher tolerance for AdaLoRA in test

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- src/peft/mixed_model.py
- src/peft/peft_model.py
- src/peft/tuners/adalora/model.py
- src/peft/tuners/adaption_prompt/model.py
- src/peft/tuners/boft/model.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/ln_tuning/model.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lycoris_utils.py
- src/peft/tuners/mixed/model.py
- src/peft/tuners/poly/model.py
- src/peft/tuners/vera/model.py
- tests/test_initialization.py
Resolves #1349
While using deepspeed, it will try to access attribute before the `__init__` method (which is wrapped by the following wrapper):
https://github.com/microsoft/DeepSpeed/blob/f0e3f01d7c7a3d8748212e61eaf487fab41168a7/deepspeed/runtime/zero/partition_parameters.py#L481-L522
However, at this time there is no `base_model` (or `model`) attribute, which would cause recursion in `__getattr__` method. So I make some modifications to the `__getattr__` method to fix this problem.
> FIX Recursion while accessing attribute before initialization

- tests/test_multitask_prompt_tuning.py
Set the seed for test
`test_generate_text_with_other_init_2_ONLY_SOURCE_SHARED` because otherwise it is flaky and fails with ~5% probability.
I'm not 100% sure where this flakiness comes from but have documented my investigation in a comment in the test.
> FIX: Flaky multitask prompt tuning test fixed by setting the seed

- docs/source/tutorial/peft_model_config.md
This might be an easily overlooked issue of character loss. I'll fix it.
> fix参数encoder_reparameterization_type

- examples/sft/train.py
This PR fixes an incorrect attribute check in the main training script. The original code was checking for the existence of a method call instead of the method itself.
- Changed `if hasattr(trainer.model, "print_trainable_parameters()")` to `if hasattr(trainer.model, "print_trainable_parameters")`
> Fix attribute check for print_trainable_parameters method

- examples/olora_finetuning/README.md
- examples/pissa_finetuning/README.md
- src/peft/peft_model.py
- src/peft/tuners/lora/config.py
- tests/test_gpu_examples.py
- tests/test_initialization.py
See https://github.com/huggingface/peft/issues/1929#issuecomment-2230780802
At the moment, when using PiSSA or OLoRA with weight conversion to restore the original base weights, there is an error when either of `rank_pattern`, `alpha_pattern`, or `rslora` is being used. This PR fixes this.
The issue is that we need to double the rank of the LoRA adapter. Right now, this is done by simply doubling r and alpha. But if `rank_pattern` and `alpha_pattern` are being used, those need to be doubled too.
Furthermore, when using `rslora`, the scaling is again different, namely `alpha / sqrt(r)`. This also needs to be adjusted.
Unfortunately, when using `rslora` together with `rank_pattern` and `alpha_pattern`, this gets way more complicated. Since we don't store the scaling in the `state_dict`, we …
> FIX PiSSA & OLoRA with rank/alpha pattern, rslora

- src/peft/tuners/lora/layer.py
> Decrease memory usage of `merge_and_unload`

- src/peft/peft_model.py
- tests/test_initialization.py
Resolves #1860
As discussed in that issue, it's not user friendly to delete the active adapter of a PiSSA/OLoRA model after calling `save_pretrained` with weight conversion. Instead, it is much more intuitive to delete the initial adapter instead, since it is loaded inside the method and not by the user, so it's really an implementation detail.
Apart from this, I made the following related changes:
- Put everything in a `try ... finally` to ensure that the initial adapter does not hang around if there is an error (thus not hogging memory).
- Renamed `initial_adapter` to `initial_adapter_name`, to make it clear that this is the name and not the adapter itself.
- Fix lines that are too long not fixed automatically by ruff (as they're strings).
For this reason, the diff looks much bigger …
> PiSSA, OLoRA: Delete initial adapter after conversion instead of the active adapter

- tests/testing_common.py
For some BS reason, Windows CI suddenly started throwing permission errors on test_merge_layers. These errors occur when using the `TempDirectory() `context manager, which raises a `PermissionError` on Windows when it tries to clean up after itself. Therefore, this context manager is now avoided in favor of manual clean up.
_More context:_
I investigated this issue first in #1947. My suspicion that this could be caused by a new pytest version was not confirmed. Maybe the reason is that GH rolled out a new Windows worker, not sure.
Also note that this is not the first time that this workaround is required, e.g. also here:
https://github.com/huggingface/peft/blob/e6cd24c907565040ee1766a5735afe3d13a71164/tests/test_custom_models.py#L1448-L1467
> CI Fix Windows permission error on merge test

- src/peft/peft_model.py
- src/peft/utils/constants.py
Bloom had two dimensions of the attention layer transposed (compared to all other transformers models), which was fixed by:
https://github.com/huggingface/transformers/pull/31445
Therefore, for future transformers versions, skip the special handling in PEFT.
There is also an issue that prompt injection did not take place when `past_key_values` was a `Cache` object that is empty. This should now hopefully work as expected.
For the time being, `past_key_values` is still being passed as a tuple of tensors, not sure if eventually this must be a `Cache` object. If yes, this will need fixing in a future PR. Same goes for the usage of `get_seq_length()` on `Cache` objects.
Note: 
I tested this locally with transformers installed form main and bloom tests passed. PEFT CI only tests this nightly, …
> FIX: New bloom changes breaking prompt learning

- src/peft/utils/constants.py
Some pre-configured models like mistral used not to work with VeRA because the weight shapes were not identical. However, since #1817, this is no longer a requirement. Therefore, this commented code can now be uncommented.
I have tested mistral and gemma and they worked. I haven't tested btlm and mixtral but with the update, I'm pretty sure they will work too.
> ENH Update VeRA preconfigured models

- src/peft/optimizers/loraplus.py
Playing with the LoRA+ optimizer, I realized that the underlying optimizer will complain about the required positional `lr` argument if it is not included in the optimizer kwargs.
In [the original implementation](https://github.com/nikhil-ghosh-berkeley/loraplus/blob/a0c44bfec0eff97b9574469366bc6b0ccc28838d/lora_plus.py#L106), this was actually already the case, but somehow this fell out along the way.
> fix: lora+: include lr in optimizer kwargs

- src/peft/peft_model.py
- tests/test_encoder_decoder_models.py
Fixes the error reported here:
https://github.com/huggingface/transformers/pull/30790#issuecomment-2253808249
Unfortunately, transformers models have an active_adapters method but it's 1) not a property and 2) calling it fails because the base model (usually) has no loaded adapter. The base model can be a transformers model for prompt learning, where the base model is not wrapped in a LoraModel or similar. Therefore, this special case needs to be handled separately.
> FIX active_adapters for transformers models

- src/peft/utils/save_and_load.py
- tests/test_initialization.py
`HF_HUB_OFFLINE=1` was not honored when trying to load an adapter. This is now fixed.
Resolves https://github.com/huggingface/transformers/issues/31700.
> FIX Loading adapter honors offline mode

- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/tp_layer.py
- src/peft/tuners/vera/layer.py
Should address https://github.com/huggingface/peft/issues/1977
> Cast to fp32 if using bf16 weights on cpu during `merge_and_unload`

- src/peft/tuners/adalora/config.py
- src/peft/tuners/adalora/model.py
- tests/test_config.py
**Description:**
This PR addresses Issue #1971 by adding a warning in `__post_init__` of `AdaLoraConfig` when `r` is set to any non-default value. The changes aim to clarify the usage of `init_r` instead of `r` in `AdaLoraConfig`, resolving confusion around parameter naming.
Updated the docstring example in AdaLoraModel to reflect the same.
Testing:
- ✅ Verified that the warning is correctly triggered when 'r' is set in AdaLoraConfig
- ✅ Ensured that existing functionality is not affected by these changes
- ✅ Checked that the updated docstring example works as expected
**Related Issues**
✅ Closes #1971
> AdaLora: Trigger warning when user uses 'r' inplace of 'init_r'

- docs/source/_toctree.yml
- docs/source/developer_guides/quantization.md
- docs/source/package_reference/helpers.md
Changed:
- Helper section had placeholder title
- `device` is not a valid argument to `from_pretrained`
- Excess empty lines
Not sure if py vs python makes a difference in code blocks.
> DOC Small fixes for HQQ and section title

- src/peft/utils/constants.py
See #1969
The fix to the bloom architecture was not actually released in transformers 4.43.3, which makes the version check invalid. Instead, now checking an attribute on the `BloomPreTrainedModel`.
> FIX: Adjust transformers version check for bloom

- docs/source/package_reference/helpers.md
- src/peft/helpers.py
- tests/test_helpers.py
Linked: #1940 
CC: @BenjaminBossan
> [Suggestions] Updates suggested for `helper.rescale_adapter_scale`

- src/peft/tuners/multitask_prompt_tuning/model.py
- src/peft/utils/save_and_load.py
The `torch.load` function allows to pass `weights_only=True`, which is more secure but may break some code that is more than just weights. For PEFT, this should not be the case, so the switch should just work.
By making the switch now, we can find out early if there are any problems, as `torch.load` will default to `True` in the future.
> MAINT: Default to loading weights only for torch.load

- tests/test_gpu_examples.py
There was a small last minute change in #1925 that broke the tests. It should be `boft.layer.Linear` and not `boft.Linear`. As these are GPU tests, CI didn't catch this and I did not run this locally to verify.
> FIX Import error in BOFT half precision test

- docs/source/developer_guides/lora.md
Fixed some typos (examle -> example, and some more)
> Update lora.md (typos)

- tests/test_config.py
These two configs were missing in `test_config.py`. Also, reordered the list of all config classes to be sorted, which makes it easier to spot missing configs.
> TST Add LNTuningConfig and LoKrConfig to tests

- src/peft/mapping.py
- tests/test_initialization.py
Resolves #2001
In PEFT, users can provide a custom `base_model_name_or_path` argument to the PEFT config. However, this value is overridden by the model's `name_or_path` attribute. This can be surprising for users. Therefore, there is now a warning about this.
To see why that can be relevant, check the original issue.
It eludes me why this argument can be passed by users only to be overridden by PEFT. This was implemented by Younes before I joined the project.
> ENH: Warn when a user provided model name in the config renamed

- tests/regression/test_regression.py
The 8bit bnb LoRA regression test results are dependent on the underlying compute capability. The logits are slightly different depending on the version (up to 0.5 abs diff). Therefore, we now check the compute capability for this test and skip it if it's too low. This check may require updating if the hardware of the CI worker is updated.
Note that I have already [invalidated the old regression artifacts](https://huggingface.co/peft-internal-testing/regression-tests/commit/42a454d4d58ecb7938c14f5eab37007f4310099f) and created a new one.
> TST: Potentially Skip 8bit bnb regression test if compute capability is too low

- .github/workflows/nightly-bnb.yml
See #1866 for context.
Let's check if this issue has resolved itself by now.
> CI Activate single core multi backend bnb tests

- examples/causal_language_modeling/peft_lora_clm_with_additional_tokens.ipynb
- src/peft/tuners/xlora/model.py
As pointed out by @benjamin-marie in #2002, we were calling `prepare_model_for_int8_training` and passing `use_flash_attention_2`. These are deprecated and this PR fixes any usages.
> Fix usage of deprecated parameters/functions in X-LoRA

- tests/test_vera.py
Hi, this PR enables the BF16 test on XPU. Below is the result after fix: 
```bash
pytest -rA tests/test_vera.py::TestVera::test_vera_dtypes[dtype2]
```
```bash
================================================= short test summary info ==================================================
PASSED tests/test_vera.py::TestVera::test_vera_dtypes[dtype2]
=============================================== 1 passed, 1 warning in 4.63s ===============================================
```
> [tests] enable `test_vera_dtypes` on XPU 

- .github/workflows/nightly-bnb.yml
This is a test to see if the BNB CI for multi-backend single-GPU passes if regression tests are disabled.
> CI Remove regression tests from BNB CI

- tests/regression/test_regression.py
Before fix:
```bash
============================================ short test summary info ============================================
FAILED tests/regression/test_regression.py::TestOpt::test_adalora - RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If y...
FAILED tests/regression/test_regression.py::TestOpt::test_ia3 - RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If y...
FAILED tests/regression/test_regression.py::TestOpt::test_lora - RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If y...
```
After fix:
```bash
============================================ short test summary info …
```
> [tests] enable regression tests on XPU

- src/peft/utils/loftq_utils.py
- tests/test_gpu_examples.py
Resolves #2020
If users want to use a local model, they need to pass the `model_path` argument. The error message now says so.
> ENH: Better error msg for replace_lora_weights_loftq when using a local model.

- tests/test_tuners_utils.py
- tests/testing_utils.py
After the fix, all tests in `TestModelAndLayerStatus` pass on XPU:
```bash
================================================ short test summary info ================================================
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_layer_names_small
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_layer_names_large
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_module_type_small
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_module_type_large
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_enabled_small
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_enabled_large
PASSED tests/test_tuners_utils.py::TestModelAndLayerStatus::test_enabled_irregular
PASSED …
```
> [tests] make cuda-only cases in `TestModelAndLayerStatus` device-agnostic

- src/peft/utils/other.py
- tests/test_custom_models.py
- tests/test_other.py
Relates to #2027
Normally, when selecting the layers for fine-tuning, PEFT already ensures that the same layer is not targeted for both parameter-efficient fine-tuning (e.g. LoRA layer) and full fine-tuning (via `modules_to_save`), as that makes no sense.
However, there is a loophole when the `modules_to_save` is applied ex post. This happens for instance when having a task type like sequence classification, where PEFT will automatically add the classification head to `modules_to_save` for the user. This loophole is now closed by adding a check to `ModulesToSaveWrapper` that validates that the targeted layer is not a tuner layer.
This does not fully resolve #2027 but will raise an early error in the future to avoid confusion. **Edit**: #2028 should fully resolve it, but having this PR …
> ENH Raise error when applying modules_to_save on tuner layer

- src/peft/tuners/tuners_utils.py
- src/peft/utils/constants.py
- tests/test_tuners_utils.py
Fixes #2027
When using a transformers sequence classification model, `target_modules="all-linear"` should not wrap the classification head with LoRA. This is because it is already wrapped with `ModulesToSave`, i.e. it will be fully fine-tuned, which is the generally desired behavior.
Before this bug fix, the classification head would be double-wrapped. With #2028, this now raises an error. With this PR, it is avoided completely. Still, keeping #2028 is good because it helps prevent other situations where double-wrapping might occur due to mis-configuration.
Note that there is no fool-proof method to detect the classification head, we have to rely on transformers convention.
> FIX: Don't target the classification head when using target_modules="all-linear"

- src/peft/tuners/lora/layer.py
- tests/test_common_gpu.py
- tests/testing_utils.py
Below are the UT Results after the fix: 
```bash
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_adalora_bnb_quantization_from_pretrained_safetensors
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_apply_GS_hra_inference
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_dora_ephemeral_gpu_offload
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_dora_ephemeral_gpu_offload_multigpu
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_ia3_bnb_quantization_from_pretrained_safetensors
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_lora_bnb_quantization_from_pretrained_safetensors
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_r_odd_hra_inference
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_serialization_shared_tensors …
```
> [tests] enable cuda-only tests in `test_common_gpu.py` to work on XPU

- tests/test_gpu_examples.py
```bash
==================================================== short test summary info =====================================================
PASSED tests/test_gpu_examples.py::OffloadSaveTests::test_offload_load
PASSED tests/test_gpu_examples.py::OffloadSaveTests::test_offload_merge
PASSED tests/test_gpu_examples.py::MixedPrecisionTests::test_load_adapter_using_float16_autocast_dtype
PASSED tests/test_gpu_examples.py::MixedPrecisionTests::test_load_model_using_float16_autocast_dtype
PASSED tests/test_gpu_examples.py::MixedPrecisionTests::test_load_model_using_float16_with_amp_raises
PASSED tests/test_gpu_examples.py::MixedPrecisionTests::test_model_using_float16_autocast_dtype
PASSED tests/test_gpu_examples.py::MixedPrecisionTests::test_model_using_float16_explicit_cast
PASSED …
```
> [tests] enable `test_gpu_examples.py` on XPU 

- src/peft/mapping.py
- src/peft/mixed_model.py
- src/peft/peft_model.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/tuners_utils.py
- src/peft/tuners/vera/model.py
- src/peft/utils/__init__.py
- src/peft/utils/constants.py
- tests/test_tuners_utils.py
Solving issue #2018.
- Raise a warning if the user is requesting an output `target_module` when the embeddings are tied, because this could lead to errors, for example when merging the adapter.
- Also refactored the code to get the model config
```python
import torch
model = AutoModelForCausalLM.from_pretrained("google/gemma-2-2b-it", tie_word_embeddings=False)
model.lm_head.weight.data = model.model.embed_tokens.weight.data.clone()
assert torch.equal(model.lm_head.weight.data, model.model.embed_tokens.weight.data)
untied_model_dir = "tmp_model"
model.save_pretrained(untied_model_dir)
model.config.save_pretrained(untied_model_dir)
model = AutoModelForCausalLM.from_pretrained(untied_model_dir)
assert torch.equal(model.lm_head.weight.data, …
```
> Warn if using tied target module with `tie_word_embeddings`

- src/peft/tuners/tuners_utils.py
- src/peft/utils/constants.py
- tests/test_tuners_utils.py
This is an optimization to reduce the number of entries in the `target_modules` set. The reason is that in some circumstances, `target_modules` can contain hundreds of entries. Since each target module is checked against each module of the net (which can be thousands), this can become quite expensive when many adapters are being added. Often, the `target_modules` can be condensed in such a case, which speeds up the process.
A context in which this can happen is when diffusers loads non-PEFT LoRAs. As there is no meta info on target_modules in that case, they are just inferred by listing all keys from the state_dict, which can be quite a lot. See: https://github.com/huggingface/diffusers/issues/9297
As there is a small chance for undiscovered bugs, we apply this optimization only if the …
> ENH: Faster adapter loading if there are a lot of target modules

- src/peft/tuners/lora/layer.py
- src/peft/utils/integrations.py
- tests/test_gpu_examples.py
Resolves #1999
- dtype check for bnb quantized weights can be misleading when using `bnb_4bit_quant_storage`
- updated base weights must be re-quantized if original weight is bnb quantized
> FIX: Error with OLoRA init when using bnb

- src/peft/peft_model.py
- tests/test_gpu_examples.py
There is a small numerical discrepancy between the outputs of a p-tuning model before and after loading. Even though it is small, it can still affect generations, so this PR eliminates it.
As an example, without the fix, this is the difference in logits for opt-125m:
```
>       torch.testing.assert_close(output_loaded, output_peft)
E       AssertionError: Tensor-likes are not close!
E
E       Mismatched elements: 30 / 10557120 (0.0%)
E       Greatest absolute difference: 1.1086463928222656e-05 at index (0, 9, 9314) (up to 1e-05 allowed)
E       Greatest relative difference: 0.00021288332936819643 at index (0, 9, 9314) (up to 1.3e-06 allowed)
```
Details about how this comes about are explained here:
https://github.com/huggingface/peft/issues/2043#issuecomment-2321522577
The gist of it is …
> FIX: Small numerical discrepancy for p-tuning after loading the model

- tests/test_stablediffusion.py
Reduce the number of inference steps for stable diffusion tests. These tests are the slowest ones on CI, this should hopefully help.
> TST: Fewer inference steps for stable diffusion tests

- tests/test_vision_models.py
The HRA vision model test is extremely slow on CI (> 600 sec, ~50% of total time). This change speeds up the test by using a smaller ResNet model to run the tests.
It's still not clear why HRA was so slow specifically -- LoRA is 40x faster -- but that can be fixed separately.
HRA author has been [notified](https://github.com/huggingface/peft/pull/1864#issuecomment-2332035181) 5 days ago but no response so far.
> TST Speed up vision model tests

- tests/test_xlora.py
After some recent optimizations, the X-LoRA tests are now among the slowest ones. Part of that is that the lora adapters are re-created for each test. By changing the fixture scope, they're now only created once. I think this should be safe, as these files are not modified in the tests.
I also enabled `test_scalings_logging_methods` with the latest transformers to ensure that this test also passes.
> TST: Make X-LoRA tests faster

- examples/pissa_finetuning/preprocess.py
Fix two bugs:
1. The `ArgumentParser` does not have a `help` argument.
2. The `--output_dir` argument is missing.
> fix arguments for PiSSA preprocess

- docs/source/accelerate/deepspeed.md
- docs/source/accelerate/fsdp.md
- docs/source/quicktour.md
- docs/source/task_guides/lora_based_methods.md
- examples/conditional_generation/peft_prompt_tuning_seq2seq_with_generate.ipynb
- examples/image_classification/image_classification_peft_lora.ipynb
- examples/int8_training/Finetune_flan_t5_large_bnb_peft.ipynb
- examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb
- examples/poly/peft_poly_seq2seq_with_generate.ipynb
- examples/semantic_segmentation/semantic_segmentation_peft_lora.ipynb
- examples/sft/run_peft.sh
- examples/sft/run_peft_deepspeed.sh
- examples/sft/run_peft_fsdp.sh
- examples/sft/run_peft_multigpu.sh
- examples/sft/run_peft_qlora_deepspeed_stage3.sh
- examples/sft/run_peft_qlora_fsdp.sh
- examples/sft/run_unsloth_peft.sh
This PR applies the deprecated `evaluation_strategy` from https://github.com/huggingface/transformers/pull/30190.
TL;DR: `evaluation_strategy` -> `eval_strategy`
(Should go live in v4.41.0, but opening now so it's here when ready!)
> Apply deprecated `evaluation_strategy`

- src/peft/tuners/boft/layer.py
- tests/test_custom_models.py
- tests/testing_common.py
There was a bug in BOFT that made it impossible in some circumstances to load more than one adapter (creating more than one adapter was possible though). This was because a code path that adjusts `boft_n_butterfly_factor` was only visited when creating a fresh adapter, but not when updating with the 2nd adapter. This was fixed by moving this code path from the BOFT layer's `__init__` method to `update_layer`.
A test for loading multiple adapters was added. Since this was a gap in our test suite, this test will be applied to all appropriate PEFT methods, not only BOFT, but the others methods are all passing without needing further changes.
For good measure, I also added BOFT to the test suite that checks multiple active adapters. These tests would have also passed without the fix in this …
> FIX: Bug that prevents BOFT from loading multiple adapters

- src/peft/peft_model.py
- tests/test_initialization.py
Resolves #2075
When saving PiSSA or OLoRA with the option to convert to normal LoRA, the LoRA weight shapes change, which means that some values like `r` and `lora_alpha` need to be adjusted in the saved PEFT config. However, these modifications should be limited to the saved config, while the loaded config should stay the same.
This PR implements this change by creating a copy of the config before modifying it.
> ENH: PiSSA/OLoRA: Preserve original config on save

- src/peft/utils/other.py
- tests/test_low_level_api.py
Similar to https://github.com/huggingface/peft/pull/1238 and https://github.com/huggingface/peft/pull/1530
This PR aims at solving an issue similar to https://github.com/huggingface/peft/issues/1524 and https://github.com/huggingface/peft/issues/1225, where one would like to add `self.dt_proj` module to `modules_to_save` instead of `target_modules` for the following operation
```
contextualized_states = mamba_inner_fn(
projected_states,
self.conv1d.weight,
self.conv1d.bias if self.use_conv_bias else None,
self.x_proj.weight,
self.dt_proj.weight,
self.out_proj.weight,
self.out_proj.bias.float() if self.use_bias else None,
-torch.exp(self.A_log.float()),
None,  # input-dependent B
None,  # input-dependent C
self.D.float(),
delta_bias=self.dt_proj.bias.float(),
delta_softplus=True,
)
```
> Expose bias to to ModulesToSaveWrapper

- src/peft/utils/constants.py
Google's gemma 2 models have a slightly different architecture than gemma 1 and thus a different `model_type` attribute. This PR adds default `target_layer`s for gemma 2 that correspond to the default `target_layer`s of gemma 1.
> ENH: Add default target layers for gemma2 architecture

- src/peft/tuners/tuners_utils.py
- tests/test_tuners_utils.py
See #2045 for context.
This bug was reported by Sayak and would occur in `find_minimal_target_modules` if a required suffix had itself as suffix a string that was already determined to be required, in which case this required suffix would not be added.
The fix consists of prepending a `"."` to the suffix before checking if it is required or not.
On top of this, the algorithm has been changed to be deterministic. Previously, it was not deterministic because a dictionary that was looped over was built from a set, and sets don't guarantee order. This would result in the loop being in arbitrary order.
As long as the algorithm is 100% correct, the order should not matter. But in case we find bugs like this, the order does matter. We don't want bugs to be flaky, therefore it is best to sort the …
> FIX: Bug in find_minimal_target_modules

- src/peft/peft_model.py
Fix docstring of function `load_adapter`.
1. `model_id` type hint
add Pathlike to keep consistency with other functions that call `load_adapter`.
2. add missing `model_id` docstring
3. remove `peft_config` docstring as `peft_config` argument doesn't exist.
> Fix func docstring

- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
This is a bit of an edge case, but I noticed this while working on something else.
PEFT allows [mixed batch adapter inference](https://huggingface.co/docs/peft/developer_guides/lora#inference-with-different-lora-adapters-in-the-same-batch), i.e. when predicting, the same batch can use different adapters by passing the `adapter_names` argument. However, this is not supported for DoRA (yet), so there is a check that raises an error if DoRA is used.
Previously, this check would check all adapters for DoRA, even if those adapters are not being used in `adapter_names`. This was unnecessarily strict and with this PR, we only check the adapters that are actually being used.
> ENH: Better DoRA check in mixed adapter batch inference

- src/peft/peft_model.py
- src/peft/utils/constants.py
- src/peft/utils/save_and_load.py
- tests/testing_common.py
Refer #1932 for more context.
The main logic is we would have a specific prefix of adapter related keys and if such prefix is present in any of the missing keys then raise a warning else the adapter is loaded succesfully.
> Fix Inconsistent Missing Keys Warning for Adapter Weights in PEFT

- src/peft/peft_model.py
- tests/test_xlora.py
After transformers merged this PR:
https://github.com/huggingface/transformers/pull/33703
The bool of `past_key_values` (a `Cache` instance) would change from `False` to `True` in one of our checks:
https://github.com/huggingface/peft/blob/ccc350151f95a9ff95da046bae5671da75eab52f/src/peft/peft_model.py#L1779
Use `get_seq_length()` method instead, which is consistent before and after that commit.
I checked the tests with the new change for both transformers before and after that commit and they passed, so this change should be backwards compatible.
> FIX: Change check if past_key_values is empty

- src/peft/utils/other.py
- tests/test_other.py
Resolves #2099
So far, if a module was wrapped due to `modules_to_save`, we handled access to the `weight` and `bias` attribute (albeit incorrectly in case of disabled adapters!). However, there could be more attributes than those that could be accessed, in which case we got an error so far.
Instead of special properties, we now implement a generic `__getattr__` method that can deal with any attribute. The implementation is a bit complex to take into account the way that `torch.nn.Module` handles `__getattr__`.
> ENH: Improved attribute access for modules_to_save

- src/peft/utils/save_and_load.py
- tests/test_gpu_examples.py
See: https://github.com/huggingface/diffusers/pull/9510#issuecomment-2378316687
Right now, the `low_cpu_mem_usage=True` option does not consolidate the devices. E.g. when the model is on GPU and the `state_dict` on CPU, the adapter weight will be on CPU after loading, when it should be GPU. This fix ensures that the devices are consolidated.
> FIX low_cpu_mem_usage consolidates devices

- src/peft/peft_model.py
- tests/test_initialization.py
- tests/testing_common.py
After merging #2084, we now clean up the `missing_keys` when loading a PEFT adapter to remove all but the relevant keys (the fact that base model keys are missing is expected when loading a PEFT adapter).
Since the presence of `missing_keys` now really means that something might have gone wrong during loading, we can now warn the user if they call `PeftModel.from_pretrained`.
Note that load_adapter still does not warn, as here we return the `load_result` and users can already check, but for `from_pretrained`, they don't have that possibility.
> ENH: Warn when from_pretrained misses PEFT keys

- src/peft/tuners/boft/layer.py
Fixing the bug that boft_s cannot be loaded with older version checkpoints.
> fix merging bug / update boft conv2d scaling variable

- src/peft/tuners/lora/layer.py
- tests/test_gpu_examples.py
Previously, the weight matrix was converted to float32 without considering the need for transposition. This update ensures that the weight matrix is transposed when the fan_in_fan_out condition is met, resolving dimension mismatch issues during GPT-2 training.
> FIX: Transpose weight matrix based on fan_in_fan_out condition in PiSSA initialization (#2103)

- src/peft/tuners/vera/bnb.py
The file was missing the `from __future__ import annotations` part. As this code is only running nightly with GPU, the normal CI missed this omission. With this PR, nightly CI should be green again.
When I tested it locally with GPU, I didn't check with Python 3.8, so this error did not occur. Once we stop supporting Python 3.8 very soon, this will also no longer be necessary, but we still need to fix it until then.
> FIX Type annoations in vera/bnb.py

- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
PEFT allows [mixed batch adapter inference](https://huggingface.co/docs/peft/developer_guides/lora#inference-with-different-lora-adapters-in-the-same-batch), i.e. when predicting, the same batch can use different adapters by passing the `adapter_names` argument. However, when users pass an adapter name that does not correspond to any of the existing adapters, these samples are currently being ignored (i.e. just the base model output is used). This is unexpected and can easily lead to errors, e.g. when users mistype the name of an adapter.
This PR fixes this issue by checking all the existing adapter names first and comparing them to the `adapter_names` that the user passed. If there are unexpected entries, an error is raised.
Due to this fix, an error in the test …
> FIX Raise an error when performing mixed adapter inference and passing non-existing adapter names

- src/peft/peft_model.py
The error in PEFT is occurring after this transformers change:
https://github.com/huggingface/transformers/pull/33870
Now, in our tests, some model_kwargs no longer necessarily contain past_key_values, resulting in a KeyError. We now account for this possibility. Affected models were opt and gpt2.
Example of failing CI: https://github.com/huggingface/peft/actions/runs/11256453704/job/31298371856
Note that CI won't detect this issue as it requires the latest transformers install. I ran this locally using `pytest tests/test_decoder_models.py -k "(prefix or prompt) and (opt or gpt2)" -v`.
> FIX Prompt learning with latest transformers error

- examples/token_classification/peft_lora_ner.ipynb
Hi @BenjaminBossan , 
Ive added a lora example for NER, which is mainly a clone of the huggingface NER notebook by Sylvain here https://huggingface.co/learn/nlp-course/chapter7/2#data-collation with couple changes here and there.
lmk what you think
> adding peft lora example notebook for ner

- tests/test_gpu_examples.py
This test calculates the correlation coefficient of HQQ model outputs. Although the model outputs are finite, the resulting matrix contains NaNs. Casting the outputs from 16 to 32 bit precision resolves the issue.
Since this test only runs on GPU, the normal CI won't catch it. I could locally verify that the fix works using:
`pytest tests/test_gpu_examples.py -k test_hqq_lora_model_outputs`
> FIX TST: NaN issue with HQQ GPU test

- src/peft/tuners/tuners_utils.py
- tests/test_tuners_utils.py
Solves the following bug:
https://github.com/huggingface/diffusers/pull/9622#issuecomment-2404789721
The cause for the bug is as follows: When we have, say, a module called `"bar.0.query"` that we want to target and another module called `"foo_bar.0.query"` that we don't want to target, there was potential for an error. 
This is not caused by `_find_minimal_target_modules` directly, but rather the bug was inside of `BaseTuner.inject_adapter` and how the `names_no_target` were chosen. Those used to be chosen based on suffix. In our example, however, `"bar.0.query"` is a suffix of `"foo_bar.0.query"`, therefore `"foo_bar.0.query"` was *not* added to `names_no_target` when it should have. As a consequence, during the optimization, it looks like `"query"` is safe to use as `target_modules` …
> FIX: Bug in target module optimization if child module name is suffix of parent module name

- setup.py
- src/peft/__init__.py
After the patch release of [PEFT v0.13.2](https://github.com/huggingface/peft/releases/tag/v0.13.2), let's bump the dev version of PEFT to `v0.13.3.dev0` so that it stays ahead (the bugfix from the patch release is already contained in the main branch).
> Bump version to 0.13.2.dev0

- src/peft/peft_model.py
Don't assume that `past_key_values` is part of the `model_kwargs`.
This fix is similar to #2140 but for encoder-decoder models. It became necessary after https://github.com/huggingface/transformers/pull/34048 was merged into transformers.
Fixes the [currently failing CI](https://github.com/huggingface/peft/actions/runs/11319951259/job/31476746284).
> FIX Don't assume past_key_valus for encoder models

- docs/source/accelerate/deepspeed.md
- docs/source/accelerate/fsdp.md
- examples/olora_finetuning/README.md
- examples/pissa_finetuning/README.md
- examples/pissa_finetuning/pissa_finetuning.py
- examples/sft/train.py
`SFTTrainer`'s keyword args like  `packing`, `dataset_kwargs`, `dataset_text_field`, `max_seq_length` has been deprecated and will be soon removed. Instead, we use `SFTConfig` (subclass of `TrainingArguments`)
This PR updates the code related to `SFTTrainer`.
> Use `SFTConfig` instead of `SFTTrainer` keyword args

- src/peft/peft_model.py
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/test_feature_extraction_models.py
The newly introduced `low_cpu_mem_usage` argument was not propagated to the `add_adapter` method of all `PeftModel` task types. This is now fixed and tests were added.
Tests were only added for LoRA to avoid running many relatively slow and redundant tests and because `low_cpu_mem_usage` is not implemented for prompt learning models.
> FIX Missing low_cpu_mem_usage argument

- setup.py
The `diffusers<0.21.0` pin was added way back in #936 and then we forget to ever remove it.
This is now causing trouble, as the old diffusers version still uses `cached_download`, which was removed from `huggingface_hub`:
> ImportError: cannot import name 'cached_download' from 'huggingface_hub'
> MNT: Remove version pin of diffusers

- src/peft/utils/other.py
- tests/test_gpu_examples.py
fix the issue that fsdp_auto_wrap_policy is not working when FSDP_TRANSFORMER_CLS_TO_WRAP and the model's _no_split_modules are None
@BenjaminBossan @sayakpaul 
Fixes #2166
> fix fsdp_auto_wrap_policy

- .github/workflows/stale.yml
- .github/workflows/test-docker-build.yml
- .github/workflows/tests.yml
- docker/README.md
- docker/peft-cpu/Dockerfile
- docker/peft-gpu-bnb-latest/Dockerfile
- docker/peft-gpu-bnb-multi-source/Dockerfile
- docker/peft-gpu-bnb-source/Dockerfile
- docker/peft-gpu/Dockerfile
- docs/source/install.md
- setup.py
- tests/test_gpu_examples.py
The end of life of Python 3.8 has arrived:
https://devguide.python.org/versions/
Therefore, Python 3.8 is removed from CI. Many tests are already failing as a transformers import raises an error that looks like it's caused by missing Python 3.8 support:
> E   RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
E   'type' object is not subscriptable
([example 1](https://github.com/huggingface/peft/actions/runs/11207561120/job/31149919883), [example 2](https://github.com/huggingface/peft/actions/runs/11207542441/job/31149871178))
By default, Python 3.11 is now used.
Python 3.12 should be added to the CI matrix now, but that's for a separate PR.
> MNT Remove Python 3.8 since it's end of life

- .github/workflows/tests.yml
- setup.py
Python 3.8 was removed recently, adding 3.12 now.
> MNT: Enable Python 3.12 on CI

- docker/peft-gpu-bnb-latest/Dockerfile
- docker/peft-gpu-bnb-multi-source/Dockerfile
- docker/peft-gpu-bnb-source/Dockerfile
- docker/peft-gpu/Dockerfile
12.1.0 is failing currently, e.g. in [this run](https://github.com/huggingface/peft/actions/runs/11491483001/job/31983929595).
> MNT: Update docker nvidia base image to 12.4.1

- src/peft/tuners/vera/bnb.py
- src/peft/tuners/vera/layer.py
The shared buffers `vera_A` and `vera_B` could be on the wrong device when using multiple GPUs, resulting in an error. This PR moves the them to the correct device to fix the error.
Example of a failing run: https://github.com/huggingface/peft/actions/runs/11396317278/job/31709933958
Since these buffers are shared, I chose *not* to move the whole buffer to the device. Instead, when we create the slices from those buffers during `forward`, I move the devices only there. This could be inefficient in terms of runtime, but IIUC, the alternative would be to create new copies of these buffers per device, using more memory.
The failing tests were introduced in #2076 but the error was already there beforehand.
I did not discover these failing tests earlier because we had a concurrent error caused …
> FIX VeRA failure on multiple GPUs

- setup.py
- src/peft/utils/loftq_utils.py
- src/peft/utils/other.py
- src/peft/utils/save_and_load.py
Resolves #2097
This fix should make the import of the `huggingface_hub` error work with older versions of that package.
> FIX: Import location of HF hub errors

- examples/loftq_finetuning/README.md
The README file in loftq contains broken link, which might confuse the reader.
Simply update the link name to the correct section.
> DOC: fix broken link in the README of loftq

- src/peft/tuners/adalora/config.py
- src/peft/tuners/boft/config.py
- src/peft/tuners/fourierft/config.py
- src/peft/tuners/hra/config.py
- src/peft/tuners/loha/config.py
- src/peft/tuners/lokr/config.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/oft/config.py
- src/peft/tuners/tuners_utils.py
- src/peft/tuners/vblora/config.py
- src/peft/tuners/vera/config.py
- tests/test_config.py
- tests/test_tuners_utils.py
This PR is aimed to address point 3 in #2155 to adjust the error message when layers transforms and layer patterns are specified.
Tbh, I dont quite understand the functionality of layern_patterns but assuming that we need layers_pattern when layers_transform is applied, ive added this simple check.
> added checks for layers to transforms and layer pattern in lora

- docs/source/developer_guides/lora.md
- src/peft/mixed_model.py
- src/peft/peft_model.py
- tests/test_initialization.py
Resolves #2184
Since PiSSA/OLoRA modifies the base weights, it should not be combined with other adapters. We now warn users about that and tell them how to mitigate this.
> ENH: Warn when loading PiSSA/OLoRA together with other adapters

- tests/test_gpu_examples.py
See: https://github.com/Vahe1994/AQLM/pull/139
It is unclear if/when AQLM will fix this and if there might not be other issues with torch 2.5.
Currently, the test [raises](https://github.com/huggingface/peft/actions/runs/11585832425/job/32255394229#step:6:171):
> E       AttributeError: module 'torch' has no attribute 'Any'
> TST: Skip AQLM test that is incompatible with torch 2.5

- src/peft/peft_model.py
- src/peft/utils/__init__.py
- src/peft/utils/integrations.py
- tests/test_gpu_examples.py
See #2134
After introducing the usage of `DynamicCache` for prefix tuning, a bug could now occur if the model is dispatched to different devices. This is because we need to move the key and value cache for each layer to that layer's respective device.
The new code mostly consists of code copied from transformers to be consistent with how transformers solves this.
Note that this only works if the `hf_device_map` attribute is set on the model.
> FIX: Prefix tuning with model on multiple devices

- src/peft/tuners/lora/model.py
- src/peft/utils/other.py
- tests/test_initialization.py
This is a bugfix for issue [2194](https://github.com/huggingface/peft/issues/2194)
Since the line matching module name to a substring pattern is called twice, I created a function and moved it to `peft.utils.other`. I think its a utility function that could be useful multiple times.
Also added a test case closely resembling the example in issue 2194 which passes now.
> [BUG] Issue with using `rank_pattern` and `alpha_pattern` together in `LoraConfig`

- src/peft/tuners/lokr/config.py
- src/peft/tuners/lokr/layer.py
- src/peft/tuners/lokr/model.py
- src/peft/tuners/lycoris_utils.py
- tests/test_custom_models.py
- tests/test_initialization.py
This PR adds a new parameter `rank_dropout_scale` and fixes scale related bugs in the LoKr. Please refer to the following function in Lycoris:
https://github.com/KohakuBlueleaf/LyCORIS/blob/258387f586beabfca71646a9671027f75ed34597/lycoris/modules/lokr.py#L347
> BUG🐛: Fixed scale related bugs in LoKr | Added rank_dropout_scale parameter

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/feature_extraction/peft_lora_embedding_semantic_similarity_inference.ipynb
I fixed the error below.
```python
from datasets import load_dataset
load_dataset("smangrul/amazon_esci")
```
-> Error
```
datasets.exceptions.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', num_bytes=154877734, num_examples=839306, shard_lengths=None, dataset_name=None), 'recorded': SplitInfo(name='train', num_bytes=77438867, num_examples=419653, shard_lengths=None, dataset_name='amazon_esci')}, {'expected': SplitInfo(name='validation', num_bytes=66412102, num_examples=363402, shard_lengths=None, dataset_name=None), 'recorded': SplitInfo(name='validation', num_bytes=33206051, num_examples=181701, shard_lengths=None, dataset_name='amazon_esci')}]
```
```python
from datasets import load_dataset
load_dataset("smangrul/amazon_esci", revision="main")
```
-> OK
> update load_dataset for examples/feature_extraction

- docs/source/developer_guides/lora.md
- examples/eva_finetuning/README.md
- examples/eva_finetuning/eva_finetuning_multi_gpu.py
- src/peft/mapping.py
- src/peft/tuners/lora/eva.py
This PR contains 
- an important bugfix for a faulty device check in [eva.py](https://github.com/huggingface/peft/blob/main/src/peft/tuners/lora/eva.py). 
- torch `all_gather` operations for all SVD Hooks to be able to leverage a higher batch size for EVA in multi-gpu setups.
- An example in the docs for using EVA with multiple GPUs
> [FIX] EVA `meta` device check bug + add multi-gpu functionality

- tests/test_gpu_examples.py
- tests/test_initialization.py
These tests use `torch.compile` on semi-realistic models and are thus slow to execute. In sum, they take ~3 min to finish, with an overall CI runtime of ~15 min, so it's significant.
As these tests are very unlikely to be affected by most code changes, it should be fine to move them to nightly CI instead of running them on each PR. Also, presence of GPUs might speed the tests up.
Note that apart from moving the tests around, they are completely unchanged. They pass locally.
> TST: Move slow compile tests to nightly CI

- docker/peft-gpu/Dockerfile
Currently, the [CI fails](https://github.com/huggingface/peft/actions/runs/11905036144/job/33174835723#step:5:62) because awq tries to import a non-existing function from transformers (presumably it was there at one point but no longer is):
>     from transformers.modeling_utils import shard_checkpoint
> E   ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (/opt/conda/envs/peft/lib/python3.11/site-packages/transformers/modeling_utils.py)
This has been [fixed](https://github.com/casper-hansen/AutoAWQ/commit/a28c747903bd917aaf43700e9ca8db65e74de19b) in awq v0.2.7. Therefore, this newer version is now used in CI.
> CI Update AutoAWQ version to fix CI

- tests/test_common_gpu.py
Fixes a failing CI bitsandbytes CI tests [here](https://github.com/huggingface/peft/actions/runs/11925572071/job/33237877071#step:9:267) and [here](https://github.com/huggingface/peft/actions/runs/11925572071/job/33237876848#step:10:548).
The input data was on CPU but the model is on GPU, resulting in an error. Note that this mismatch was not an issue previously because accelerate added an `AlignDevicesHook` that took care of this. With the latest accelerate, this is no longer the case, whereas the hook is present for v1.1.1.
In any case, it's better that we set the device of the data explicitly, so I think this is a safe change. But it would be good to know what happened that caused this change.
Note: CI won't catch these errors, as the tests require GPU. However, I reproduced and …
> FIX Correctly set device of input data in bnb test

- src/peft/import_utils.py
EETQ tries to import the `shard_checkpoint` function from transformers but it has been removed in the latest version. Therefore, trying to use EETQ currently results in an import error that crashes all the tests. This fix results in EETQ tests being skipped if there is an import error.
The issue has been reported to EETQ: https://github.com/NetEase-FuXi/EETQ/issues/34
> CI: Skip EETQ tests while broken

- src/peft/config.py
- src/peft/mapping.py
- src/peft/peft_model.py
- src/peft/tuners/adalora/config.py
- src/peft/tuners/adaption_prompt/config.py
- src/peft/tuners/boft/config.py
- src/peft/tuners/bone/config.py
- src/peft/tuners/fourierft/config.py
- src/peft/tuners/hra/config.py
- src/peft/tuners/ia3/config.py
- src/peft/tuners/ln_tuning/config.py
- src/peft/tuners/loha/config.py
- src/peft/tuners/lokr/config.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/multitask_prompt_tuning/config.py
- src/peft/tuners/oft/config.py
- src/peft/tuners/p_tuning/config.py
- src/peft/tuners/poly/config.py
- src/peft/tuners/prefix_tuning/config.py
- src/peft/tuners/prompt_tuning/config.py
- src/peft/tuners/vblora/config.py
- src/peft/tuners/vera/config.py
- src/peft/tuners/xlora/config.py
- tests/test_config.py
- tests/test_initialization.py
Fixes #2203 
This PR adds validation for the `task_type` parameter across all PEFT types (e.g., LoRA, Prefix Tuning, etc.) to ensure that only valid task types, as defined in the `TaskType` enum, are used. This resolves the issue where invalid or non-sense task types (e.g., `"BLABLA"`) or typos (e.g., `"CUASAL_LM"` instead of `"CAUSAL_LM"`) could be passed without raising an error, potentially causing unexpected behavior.
- **Prevents Silent Failures**: Without this validation, users could pass incorrect or unsupported task types without receiving any feedback. This could lead to silent failures or unexpected behavior during training or inference.
- **Consistency**: Ensures that all PEFT types adhere to the same validation rules for `task_type`, maintaining consistency across different …
> Add Validation for Invalid `task_type` in PEFT Configurations

- examples/eva_finetuning/eva_finetuning_multi_gpu.py
- src/peft/tuners/lora/eva.py
- src/peft/utils/incremental_pca.py
- tests/test_incremental_pca.py
Deterministic behavior of SVD computations on layer inputs is important on multi gpu setups to ensure resulting EVA state dicts are identical. Currently deterministic behaviour of SVD is ensured by just setting torch.manual_seed() inside `_get_eva_state_dict` which is not ideal because it can interfere with the seed set by the user. I therefore moved this functionality inside the `IncrementalPCA` class.
I also added a new argument for `get_eva_state_dict`: `gather_distributed_inputs` which is `False` by default and defines if inputs should be concatenated for the SVD computation for distributed runs.
> [FEAT] EVA: ensure deterministic behavior of SVD on multi gpu setups

- src/peft/tuners/lora/eva.py
- tests/test_initialization.py
The EVA consistency tests are currently among the slowest tests overall, taking roughly 4x 50 sec with an overall test runtime of 15-20 min, so they make up a significant fraction of that runtime.
With this PR, the number of iterations until convergence is reduced by passing a lower tau value. ~~Testing locally, the similarity threshold is still crossed for the tests to pass, so this change should be good.~~ On CI, the similarity threshold had to be reduced a bit for the tests still to pass.
Overall, this cuts the runtime ~20 sec or less. Thus they're still slow but it's a noticeable difference.
Besides this change, I made some smaller adjustments to EVA:
- break long lines
- use keyword arguments for initializing `SVDHook`
- hide progress bar in tests
> TST: Eva: Speed up consistency tests

- tests/test_gpu_examples.py
The test failure is caused by a dangling accelerate environment variable indirectly set by previous tests through `TrainingArguments`, which results in torchao using fp16, which breaks.
The current fix is to delete the env var for torchao. In the future, we may use an accelerate function to clean up these env vars (https://github.com/huggingface/accelerate/pull/3252).
> CI: Fix failing torchao test

- tests/test_vision_models.py
Currently PEFT tests are [failing](https://github.com/huggingface/peft/actions/runs/12015138902/job/33529040221?pr=2234#step:6:1762) because 2 trl internal models that we relied on for testing were moved (one has also been changed). The new models have now been copied to `peft-internal-testing` to avoid this in the future.
I have updated `peft-internal-testing/tiny_T5ForSeq2SeqLM-lora` to use the new copied model in `peft-internal-testing` as the base model (no change in PEFT code necessary). This model also required the LoRA adapter to be updated, as the shapes of the base model were changed.
This PR updates the used Llava model id to now use the copy of that model that is inside of `peft-internal-testing`.
> TST: Update Llava model id in test

- .github/workflows/tests.yml
Version 12 will be deprecated in the coming month and there are already some problems with it so we might just as well upgrade.
This might fix errors where the runner does not run anything at all as seen [here](https://github.com/huggingface/peft/actions/runs/12015138902/job/33492659879?pr=2234).
> Bump version of MacOS runners from 12 to 13

- src/peft/tuners/lora/aqlm.py
- src/peft/tuners/lora/awq.py
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/eetq.py
- src/peft/tuners/lora/eva.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/hqq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lora/torchao.py
- src/peft/tuners/lora/tp_layer.py
- tests/test_common_gpu.py
- tests/test_custom_models.py
- tests/test_initialization.py
This PR adds the argument `lora_bias` which, if set to `True` (default: `False`), adds a bias term to the LoRA B module.
Typically, this should be disabled. The main use case is when the LoRA weights were extracted from fully fine-tuned parameters, so the bias of those parameters can be taken into account.
Merging is supported for this argument when using vanilla LoRA layers or bitsandbytes LoRA layers. Other types of LoRA layers don't support merging.
This option is also disabled for non-standard LoRA weight initialization like LoftQ, as well as for embedding layers (since they use `nn.Parameter`, i.e. there is no bias term).
Notes:
1. While working on this, I noticed that some of the quantized LoRA layers do not correctly check for DoRA. This is now added.
2. If this PR is merged, we …
> ENH Argument to enable bias for LoRA B

- src/peft/tuners/lora/bnb.py
Our regression tests reveal that the 8bit LoRA BNB regression test is [failing](https://github.com/huggingface/peft/actions/runs/12042604161/job/33576548074#step:8:254). To reproduce, run:
`pytest tests/regression/test_regression.py -s --regression -k test_lora_8bit`
The regression was introduced in #2122. We didn't notice this earlier because of other failing tests in the nightly CI.
The cause of the error is subtle. In the original code, we would calculate the LoRA output, convert the `dtype` if necessary, then add it to the base output. After the mentioned PR, we calculate the LoRA output, add it to the base output, then convert the `dtype` if necessary ([code](https://github.com/huggingface/peft/pull/2122/files#diff-d6321d6b9970ada644811f3992899f3ef7df4581fced2a7584e0a51b03cc3355)). …
> FIX: Small regression in BNB LoRA output

- src/peft/mapping.py
- tests/test_initialization.py
There was a bug that when creating a PEFT model with the `task_type` argument, the `low_cpu_mem_usage` argument was not passed along. This is now fixed and unit tests for this were added.
This is a very niche bug because there is typically no need to pass `low_cpu_mem_usage=True` when calling `get_peft_model`. Moreover, as the option for this was only added recently (#2142) and is unreleased, few if any users should be affected by the bug.
https://github.com/huggingface/peft/pull/2142/files#diff-b3b90f453dea37bf90203fd395e9dedc21b21c9a38464c6b1572368c049ef8b2
> FIX: Correctly pass low_cpu_mem_usage argument when initializing a PEFT model with task_type

- src/peft/peft_model.py
After a [recent change in transformers](https://github.com/huggingface/transformers/pull/22105), PEFT could no longer determine the word embeddings from Deberta. This PR provides a very minimal fix that correctly determines the word embeddings again.
[Failing CI](https://github.com/huggingface/peft/actions/runs/12143543131/job/33860665168)
To reproduce, run: `pytest tests/test_feature_extraction_models.py -k "prompt_tuning and deberta" -v`
Previously, the word embeddings were determined in the following manner:
1. Find the `transformers_backbone` by checking the base model's children for `PreTrainedModel` instances
2. If not found, the model itself is considered the transformers backbone.
3. On the backbone, check for modules whose weight has the same size as the vocab size. This module …
> FIX Correctly determine word embeddings on Deberta

- src/peft/tuners/lora/awq.py
Importing from AWQ triggers CUDA context initialization, which can be problematic in some circumstances (see #1877). This PR moves the import so that it's local, preventing this issue.
To test this, run this script:
```python
import multiprocessing
from torch import nn
import peft  # noqa F401
def func():
nn.Linear(2, 3).cuda(0)
if __name__ == "__main__":
proc = multiprocessing.Process(target=func)
proc.start()
proc.join()
```
Ideally, we can add this to our nightly GPU tests, but running this from the pytest runner does not work (IIRC) so some extra steps are required.
> FIX: Prevent CUDA context initialization due to AWQ

- src/peft/tuners/adalora/model.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/bnb.py
- src/peft/tuners/vera/model.py
- src/peft/utils/integrations.py
- tests/test_common_gpu.py
This PR contains changes to PEFT that relate to an upcoming 0.45.0 release that we are planning for bitsandbytes. Primarily the changes are related to [bitsandbytes#1401](https://github.com/bitsandbytes-foundation/bitsandbytes/pull/1401).
1. Bitsandbytes will introduce a public API function for LLM.int8() weight dequantization. We use this API when available, and otherwise use a functionally equivalent implementation. Apart from its relative simplicity, this will also resolve issues such as #2065.
2. The `memory_efficient_backward` kwarg for `Linear8bitLt` will be removed in the upcoming release, as per a longstanding [deprecation notice](https://github.com/bitsandbytes-foundation/bitsandbytes/blob/7dca70049566b5b1c55cbd67e1cb191729a98152/bitsandbytes/nn/modules.py#L908). This PR removes …
> ENH: Updates for upcoming BNB Int8 release

- examples/pissa_finetuning/README.md
- examples/pissa_finetuning/pissa_finetuning.py
- setup.py
- src/peft/__init__.py
- src/peft/peft_model.py
- tests/test_custom_models.py
- tests/test_initialization.py
- tests/test_xlora.py
This PR can be reviewed but should NOT BE MERGED yet. We'll do this close to the release, once we know that no further commits will make it into the release.
- Bump versions
- Remove deprecated convert_pissa_to_lora argument
- Remove a pytest skip for older transformers versions
- Adjust some comments, docstrings
> Prepare for PEFT release of v0.14.0

- src/peft/mapping.py
- src/peft/peft_model.py
- tests/test_initialization.py
This pull request addresses an [issue ](https://github.com/huggingface/peft/issues/2252) where adapter weights are incorrectly initialized when the adapter_name conflicts with the tuner_prefix during model loading. Specifically, it introduces a warning message to notify users when this conflict occurs, as this could lead to confusion or unintentional weight reinitialization.
**Changes:**
- Added a warning message when adapter_name matches the tuner_prefix, indicating a potential issue with missing adapter keys during model loading.
- The warning clarifies that this conflict is likely caused by the adapter_name being contained in the tuner_prefix, helping users identify and resolve the issue more easily.
**Impact:**
- Improves user experience by providing clearer feedback when model …
> Fix: Add warning for adapter_name conflict with tuner 

- src/peft/tuners/lora/config.py
- src/peft/tuners/tuners_utils.py
- tests/test_tuners_utils.py
When the option to specify `target_modules="all-linear"` was introduced in PEFT (#1295), the restriction was added to only allow it for instances of `PreTrainedModel`. This was because we want to exclude the output layer from being targeted, even if it is a linear layer, and we can't determine this layer well except by convention.
This PR lifts the restriction to `PreTrainedModel`s. Thus, users can now target other models like diffusers models or custom models. The caveat is to use this "at your own risk", since all linear layers will be targeted, whether they be output layers or not.
While working on this, I found a potential bug. The logic for updating target_modules was that only the last part of the linear module's name was used. So e.g. if the module was named `"foo.bar.baz"`, then …
> ENH FIX: Allow "all-linear" to target custom models

- src/peft/tuners/adaption_prompt/utils.py
This PR resolves the [failing adoption prompt tests](https://github.com/huggingface/peft/actions/runs/12278356833/job/34259845086#step:5:1003) in the CI using transformers installed from source.
In this transformers PR:
https://github.com/huggingface/transformers/pull/34858/
the `module.rotary_emb` attribute has been removed, which adoption prompt so far assumed was present. Instead, the `position_embeddings` are now already computed and can be taken directly from the `kwargs`.
> FIX Adoption prompt: New way to obtain position embeddings

- src/peft/tuners/lora/torchao.py
At one point, we need to perform a check for the quantization dtype. This used to rely on the `layout_tensor` attribute, which was renamed to `tensor_impl`. The code now checks both attributes.
This renaming was confirmed by a torchao dev. I tested the change locally on GPU and it fixes the [failing CI test](https://github.com/huggingface/peft/actions/runs/12344769407/job/34447793214#step:6:348).
> FIX Int8 check for torchao v0.7.0

- src/peft/utils/other.py
Related issue #2299
This PR updates the docstring of the prepare_model_for_kbit_training function to include the following improvements:
1. Added a step specifying that the base model layers are frozen during training preparation. #2299
> Addeed information regarding freezing the base model in prepare_model_for_kbit_training docstring

- docs/source/developer_guides/model_merging.md
This may not be the best modification, but the previous code couldn't run directly. The following code needs to be added for it to work, otherwise, the following error would occur:
`
Traceback (most recent call last):
File "/workspace/wubing/titan/scripts/leaderboard/lora/merge_loras_peft_example.py", line 13, in <module>
model = PeftModel.from_pretrained(model, "smangrul/tinyllama_lora_norobots", adapter_name="norobots")
File "/workspace/wubing/anaconda3/envs/titan/lib/python3.10/site-packages/peft/peft_model.py", line 581, in from_pretrained
load_result = model.load_adapter(
File "/workspace/wubing/anaconda3/envs/titan/lib/python3.10/site-packages/peft/peft_model.py", line 1239, in load_adapter
load_result = set_peft_model_state_dict(
File …
> add resize_token_embeddings

- src/peft/mapping.py
- tests/test_mapping.py
This is a fix for https://github.com/huggingface/peft/issues/2295.
When modifying a model with `get_peft_model` that was already modified in the same way, even specifying a different config may not change the trainable parameter count, e.g. when specifying target modules that are only a subset of the previous target modules.
With this patch a warning will be issued with a hint to `.unload()` when calling `get_peft_model` on an already modified model.
> FIX #2295: Warn when user reloads modified model

- examples/olora_finetuning/README.md
- examples/olora_finetuning/olora_finetuning.py
- src/peft/utils/integrations.py
I compared a lot of lora finetune script and found this script is the best, it's so clear and easy to understand. So I want to extend the usage for this script to support more platforms and also DDP with minimum changes.
I currently test the script on cuda and cpu with 4 DDP on opt and llama-3. It shows reasonable results. 
It would be great if this PR can be merged so we can apply it on more models and devices.
> Extend usage for olora finetune script

- docs/source/tutorial/peft_model_config.md
- src/peft/mapping.py
closes #2295 along with FIX #2306 
Updates documentation for `get_peft_model()` that the base model will be modified in-place:
- tutorial/peft_model_config
- `get_peft_model()` docstring
> [DOC] Updated documentation for `get_peft_model()` for in-place base model modification

- tests/test_gpu_examples.py
See https://github.com/huggingface/transformers/pull/35235#issuecomment-2575500996 for context.
There has been a [refactor in transformers](https://github.com/huggingface/transformers/pull/35235) that resulted in the rotary embedding of Mistral (and probably others) moving to the model level. This led to a device map used in one of the tests to being incorrect and thus a [failing nightly CI](https://github.com/huggingface/peft/actions/runs/12644013486/job/35230888688). This PR fixes the device map.
Notes:
- This fix doesn't really have anything to do with prefix tuning, the error occurred even before prefix tuning is used.
- The error won't be caught by the PR CI, as it requires 2 GPUs to run and thus is only tested in the nightly CI.
> FIX Prefix tuning test w/ rotary emb on multi GPU

- src/peft/tuners/adaption_prompt/layer.py
- src/peft/tuners/adaption_prompt/utils.py
The changes in https://github.com/huggingface/transformers/pull/35235 resulted in a couple of adaption prompt tests to fail. This PR fixes these failures while maintaining compatibility with older transformers versions.
Required changes:
- `hidden_size` attribute removed from model, now `config.hidden_size`
- `num_heads` attribute removed from model, now `config.num_attention_heads`
- `forward` now returns 2 outputs instead of 3, rewritten to be agnostic towards the number of outputs
> FIX: Adaption prompt errors after changes from transformers #35235

- src/peft/tuners/lora/model.py
- tests/test_gpu_examples.py
There was a bug in PEFT that occurred when trying to use the `low_cpu_mem_usage=True` option with 8bit bitsandbytes quantized models. This bug is fixed now.
See https://github.com/huggingface/diffusers/issues/10550 for the bug report.
> FIX low_cpu_mem_usage=True with 8bit bitsandbytes

- src/peft/peft_model.py
- tests/test_initialization.py
This is for backwards compatibility: In #2282, `PEFT_TYPE_TO_MODEL_MAPPING` was removed as it was redundant with `PEFT_TYPE_TO_TUNER_MAPPING`. However, third party code could still use this mapping, e.g.:
https://github.com/AutoGPTQ/AutoGPTQ/blob/6689349625de973b9ee3016c28c11f32acf7f02c/auto_gptq/utils/peft_utils.py#L8
Therefore, it is reinstated here, but a `DeprecationWarning` will be given if it's used.
> FIX: Reinstate PEFT_TYPE_TO_MODEL_MAPPING variable with deprecation

- examples/corda_finetuning/README.md
- examples/corda_finetuning/preprocess.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/corda.py
- src/peft/tuners/lora/layer.py
- tests/test_initialization.py
- Added documentation about selection of `run_model` sample size
- Added documentation about memory consumption of preprocessing
- Pruned temporary fields after preprocessing and building LoRA adapter, so that CorDA does not consume more memory during training compared to other LoRA methods
> FIX: reduce CorDA memory consumption + docs

- .github/workflows/zizmor.yaml
- .github/zizmor.yml
Zizmor detected a potential cache poisoning attack via `setup-docker-buildx`. There is an argument to this (an attacker with a valid github token could modify the cache, change the buildx binary and tamper with Docker build releases) but there is also an argument against it: the buildx cache would prevent general information leaks when a new buildx release is tampered with. Since there is no obvious benefit from either side, we ignore this hint and deem it uncritical.
We also change the trigger of zizmor runs to pushes on main, regardless of whether workflow files are changed or not to catch new audits from more recent zizmor versions.
> React on new zizmor version findings

- src/peft/import_utils.py
- tests/test_common_gpu.py
- tests/test_gpu_examples.py
This PR enables current cuda-only tests to work on non-cuda accelerators. Below are some of the results on XPU after this fix:
```bash
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_r_odd_hra_inference
PASSED tests/test_common_gpu.py::PeftGPUCommonTests::test_modules_to_save_grad
PASSED tests/test_gpu_examples.py::TestBOFT::test_boft_half_conv
PASSED tests/test_gpu_examples.py::TestBOFT::test_boft_half_linear
PASSED tests/test_gpu_examples.py::TestEvaInitializationGPU::test_eva_initialization_consistency[model]
```
> [tests] make cuda-only tests device-agnostic

- src/peft/tuners/lora/layer.py
- tests/test_initialization.py
See initial report here:
https://github.com/huggingface/peft/issues/761#issuecomment-2600936330.
For MHA to work in all circumstances, for instance in `eval` model, it requires us to expose a couple of more attributes that we have missed so far. Those were added now.
> FIX: Add missing attributes to MultiheadAttention

- .github/workflows/build_docker_images.yml
- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
- .github/workflows/integrations_tests.yml
- .github/workflows/nightly-bnb.yml
- .github/workflows/nightly.yml
- .github/workflows/stale.yml
- .github/workflows/test-docker-build.yml
- .github/workflows/tests-main.yml
- .github/workflows/tests.yml
- .github/workflows/torch_compile_tests.yml
- .github/workflows/trufflehog.yml
- .github/workflows/upload_pr_documentation.yml
- .github/workflows/zizmor.yaml
- .github/zizmor.yml
Zizmor now supports auditing token permissions for each workflow run and reports that we almost never remove the default permissions (which seem relatively permissive). As a precaution it does not hurt to revoke all token permissions by default and see what breaks on the way.
Because it is not clear what the final solution will look like this is a draft PR until more is known.
> Fix for zizmor permission warnings

- .github/workflows/tests.yml
- scripts/ci_clean_cache.py
This PR introduces CI caching for datasets and hub artifacts across runner operating systems with the intended goal to minimize the number of failed test runs because of network faults. As  an additional bonus it might make the CI a bit faster.
The following artifacts are cached: `${HF_HOME}/hub/**`
Note that we're avoiding `.lock` files as well as `*.pyc` files. We're not simply caching `$HF_HOME` since there is also the  datasets and `modules` where the former was acting up when testing (no details, just dropped, we may explore this later but we're not using that many datasets) and the latter is just code which is probably not a good idea to cache anyway.
There is a post process for the cache action which uploads new data to the cache - only one runner can access the cache for …
> Attempt at adding a cache for models

- src/peft/mixed_model.py
- src/peft/peft_model.py
- src/peft/utils/other.py
- tests/test_custom_models.py
Resolves #2206
~~NOT READY TO MERGE YET. Let's wait for the 0.14.0 release.~~
~~Tentative solution to that issue.~~
The problem is that we keep a "global" `modules_to_save` on the `model` which contains all possible `modules_to_save` for each adapter. When the first adapter targets layer "foo" with `modules_to_save` and the second adapter targets "bar", then "foo" will create a copy of the original module for the second adapter, even though it's not needed.
This does not change the result but is unnecessary and takes up memory. Thus it should be avoided.
> FIX: Avoid needless copy from modules_to_save

- .pre-commit-config.yaml
- examples/causal_language_modeling/peft_lora_clm_accelerate_ds_zero3_offload.py
- examples/conditional_generation/peft_lora_seq2seq_accelerate_ds_zero3_offload.py
- examples/corda_finetuning/datautils.py
- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/fp4_finetuning/finetune_fp4_opt_bnb_peft.py
- examples/int8_training/peft_adalora_whisper_large_training.py
- examples/lora_dreambooth/convert_peft_sd_lora_to_kohya_ss.py
- scripts/log_reports.py
- setup.py
- src/peft/auto.py
- src/peft/tuners/_buffer_dict.py
- src/peft/tuners/adaption_prompt/model.py
- src/peft/tuners/boft/layer.py
- src/peft/tuners/bone/model.py
- src/peft/tuners/fourierft/model.py
- src/peft/tuners/ia3/model.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/vblora/model.py
- src/peft/tuners/vera/model.py
- src/peft/utils/loftq_utils.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/test_incremental_pca.py
We use ruff for linting. The version is fixed because otherwise, we formatting changes would creep into random PRs. Thus far, the version was ~0.6.1 but that's already quite old by now, thus moving to ~v0.9.2.
The ruff changes themselves are all about:
1. Other line breaking logic for asserts with messages
2. More aggressive string normalizaton
Making these changes is always a bit annoying since existing PRs might need to be updated, but there is never a really good time to do it.
> MNT Update ruff to v0.9.2

- src/peft/tuners/lora/config.py
Resolves #2212
The documentation for the `LoraConfig` option `init_lora_weights=False` is ambiguous. This PR updates the docstring and help to make it clearer what this option does.
I also changed the order of the options (True -> False -> Gaussian -> rest, instead of True -> Gaussian -> False -> rest), as that made more sense to me.
The remaining parts of the docstring were left untouched (not obvious when checking the GH diff), except for changing line breaks (to better adhere to the 120 chars limit) and adding missing spaces at the end of a few lines. I attached the screenshots below as they better show what was actually changed:
> DOC Better document init_lora_weights=False option

- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
Resolves #2241
My comment shows that the shapes match in Enformer model: https://github.com/huggingface/peft/issues/2241#issuecomment-2596949160
Unsure how to test further it other than to run it in some training loop
> Adding Lora implementation for nn.Conv1d

- tests/test_gpu_examples.py
PR #2341 added more rigorous checks for AdaLoRA and adjusted the tests to take that into account. However, one GPU test was missed. This test is now updated too, fixing the [failing nightly CI](https://github.com/huggingface/peft/actions/runs/12980863670/job/36198447706#step:6:397) (I ran it locally on GPU to verify).
On top of that, I adjusted some numbers on the tests so that each AdaLoRA phase runs for 2 steps, leading to 6 steps total. This means that tests run a little bit longer but I think it's acceptable for better test coverage.
> FIX: Failing AdaLoRA GPU test

- tests/test_helpers.py
- tests/test_stablediffusion.py
- tests/test_tuners_utils.py
So far, tests are using `hf-internal-testing/tiny-stable-diffusion-torch` for testing diffusion models. However, this model has some issues:
- still uses pickle (.bin) instead of safetensors
- there is a `FutureWarning` because of the config
Now, using `hf-internal-testing/tiny-sd-pipe` (thanks Sayak for suggesting) instead which doesn't have those issues.
On top of that, there is often a Hub error when loading the diffusion model, although it's unclear why this particular model is so prone to that. Maybe the new model eschews this error, but even if it doesn't, it is better to make the switch.
> TST Use different diffusion model for testing

- .github/workflows/zizmor.yaml
To be on the safe side when installing zizmor and it's dependencies we're using a locked installation, meaning that the dependencies and their versions are taken from the Cargo.lock file.
This will hopefully reduce the chances of having the pipeline randomly fail due to updated dependencies down the line.
> Use locked install for zizmor

- docs/source/index.md
fix links to PEFT guides: 
- How to guides
- Conceptual guides
> [docs] fix links to PEFT guides

- docs/source/index.md
The "Get started" link currently points to the "Quicktour" article,
while "Get started" is also the first title in the TOC, causing
confusion.
Rename the "Get started" link to "Quicktour" to match the article and
ensure consistency.
> [docs] rename link to PEFT Quicktour

- docs/source/developer_guides/troubleshooting.md
Users sometimes get confused by the warning from transformers that some weights are uninitialized and need to be trained when they use models for classification. A recent example is #2367.
Even though the warning does not come from PEFT, let's add a section to the docs to explain this warning, as the situation is a bit different here.
> DOC: Explain uninitialized weights warning

- src/peft/import_utils.py
- src/peft/utils/hotswap.py
- tests/test_gpu_examples.py
- tests/test_initialization.py
A couple of smaller issues that surfaced when working on the diffusers integration are not fixed.
- Better detection if model is compiled in `prepare_model_for_compiled_hotswap`
- Fix handling of models that are compiled but where compilation is not detected (from "inside" the model, discussed internally)
- Handle device of swapped in adapter weights.
- Wrong adapter name in compiled diffusion model test
- Add hotswap test for different alphas and ranks but model not being compiled (linear and conv2d)
- Make diffusers import local in test file to avoid bnb nightly tests from failing owing to the missing import
> FIX: Small fixes to hotswapping

- src/peft/utils/hotswap.py
- tests/test_initialization.py
When erroneously calling `prepare_model_for_compiled_hotswap` before loading any LoRA adapter, right now, nothing happens. Later, users will run into an error because the model was not prepared. Therefore, we now raise an error when the function did not detect any adapter layers and give an appropriate error message.
> ENH prepare_model_for_compiled_hotswap raises when no adapter was found

- src/peft/utils/save_and_load.py
- tests/test_initialization.py
This PR solves the issue that:
When loading a PEFT model locally, the provided arguments for hf_hub_download (e.g., local_dir and cache_dir) are not being passed correctly. As a result, custom paths specified by the user are ignored, leading to potential issues with file loading.
> Fix: Ensure hf_hub_download arguments are used when loading locally

- src/peft/tuners/xlora/model.py
- tests/test_xlora.py
Supersedes #2383.
X-LoRA tests started failing after this transformers PR (see e.g. [here](https://github.com/huggingface/peft/actions/runs/13374222006/job/37349744808?pr=2382)):
https://github.com/huggingface/transformers/pull/35724
The solution appears to be to disable caching completely when calling generate on the X-LoRA model. This also makes some previously xfail-ing tests pass.
I tested this locally with transformers checked out before and after the mentioned PR and the tests pass in both circumstances. I also tested changing the base model from "facebook/opt-125m" to "trl-internal-testing/tiny-random-LlamaForCausalLM" and the tests passed with both.
> FIX: Avoid caching in X-LoRA generate

- examples/boft_controlnet/requirements.txt
- examples/boft_dreambooth/requirements.txt
- examples/hra_dreambooth/requirements.txt
There were approximately 322 [dependabot security advisories](https://github.com/huggingface/peft/security/dependabot/15) for this, so let's bump the transformers version used in the requirements.txt of a couple of examples. Note that this is not a real security issue, as that issue is with another model that's not being used in the examples.
> SEC Bump transformers version used in examples

- tests/test_gpu_examples.py
After unblocking single GPU tests with #2380, a couple of tests related to hotswapping failed. This PR should (hopefully) address this.
1. Wrong error type caught with `xfail`
I set the wrong error type for the `xfail`ing compiled hotswap diffusers tests. This was because I hadn't checked out diffusers main when I was checking locally.
2. Loosen tolerance
Some tests fail because an `allclose` does not match even though the numbers in the logs look pretty much identical:
https://github.com/huggingface/peft/actions/runs/13404117333/job/37440752790#step:6:1929
This is most likely a problem with tolerances being too strict. Unfortunately, I can't reproduce the error locally, so I have to guess that moving from `1e-5` to `1e-4` will the issue.
Note: Since this only affects GPU tests, the …
> FIX: Failing single GPU tests related to hotswapping

- src/peft/import_utils.py
- src/peft/tuners/lora/__init__.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/tuners_utils.py
- src/peft/utils/other.py
- tests/test_gptqmodel.py
PR Changes:
* FIX GPTQ linear layers from GPTQModel is not compatible with PEFT Lora wrapper
* Skip `Scaling`  multiply ops if `Scaling == 1` (Unsure gpu is smart enough to no-op this micro optimizaton so doing this manually). The loras we are testing for GPTQ does not use Scale so `scale = r / lora_alpha` where `r == lora_alpha`
Notes:
* `GPTQLoraLinear` copies most of the code and structure from `AwqLoraLinear`. 
TODO:
> FIX GPTQModel Lora Compat

- src/peft/tuners/tuners_utils.py
- tests/test_tuners_utils.py
Resolves #2390
There was a bug in PEFT when adding a LoRA adapter with `target_modules='all-linear'` (e.g. via `add_adapter`) to a model that already had LoRA adapters applied. The resolution of `'all-linear'` would result in, for instance, `lora_A` and `lora_B` being targeted, leading to nested LoRA adapters. With this fix, this is prevented and the correct layers will be targeted.
> FIX Model with nested all-linear target modules

- .github/workflows/nightly-bnb.yml
- .github/workflows/nightly.yml
The old name is deprecated and now revoked.
> Use new slack secret token name

- tests/test_gpu_examples.py
Fixes [currently failing](https://github.com/huggingface/peft/actions/runs/13689803593/job/38280830007#step:6:1768) hotswap+compile tests that fail because outputs are not close enough before vs after compilation.
In `test_gpu_examples.py`, some tests run torchao, which sets the float32 matmul precision to "high". This in turn results in some models producing different outputs when compiled (but only for some seeds). Therefore, we need to ensure that the precision is reset to "highest", which is the default.
> FIX: Reset the FP32 matmul precision in tests

- src/peft/tuners/lora/layer.py
The PR #2404 introduced an optimization for LoRA in case that scaling == 1 (see
https://github.com/huggingface/peft/pull/2404#discussion_r1975145200). This unfortunately leads to recompilation when the model is compiled, as witnessed by the failing CI here:
https://github.com/huggingface/peft/actions/runs/13755365121/job/38461837691#step:6:157
For now, let's revert the optimization. If we have concrete numbers that show that the optimization makes a significant difference, we can start thinking about how to optimize this code path in a compile-friendly way.
Here is a minimal reproducer:
```python
import pytest
import torch
from peft import LoraConfig, get_peft_model
from peft.utils.hotswap import prepare_model_for_compiled_hotswap
class …
```
> FIX Revert optimization for LoRA scaling == 1

- setup.py
- src/peft/__init__.py
- src/peft/utils/save_and_load.py
- bump versions
- remove piece of code required for torch <= 1.12
- Small adjustments to release instructions regarding versions
> Release 0.15.0

- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
As discussed in [#2153](https://github.com/huggingface/peft/pull/2153).
Code [example](https://gist.github.com/gslama12/0a853f43418b1c104286b4bb4dd745f3)
> FIX for ConvNd layers using the groups argument.

- docs/source/accelerate/deepspeed.md
The broken link can be found [here](https://huggingface.co/docs/peft/accelerate/deepspeed#use-peft-qlora-and-deepspeed-with-zero3-for-finetuning-large-models-on-multiple-gpus) in the docs.
> Fix incorrect link in docs

- scripts/launch_notebook_mp.py
- tests/test_common_gpu.py
- tests/test_gpu_examples.py
tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_causal_lm_training_multi_gpu   **pass** tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_seq2seq_lm_training_multi_gpu   **fail, CUDA fails with same error log, may fix in another PR**
tests/test_gpu_examples.py::PeftBnbGPUExampleTests::test_8bit_adalora_causalLM **pass**
tests/test_common_gpu.py::PeftGPUCommonTests::test_8bit_dora_merging  **pass**
tests/test_gpu_examples.py::MultiprocessTester::test_notebook_launcher **pass**
> enable 5 test cases on XPU

- tests/test_custom_models.py
This specific test used a learning rate that is too high, resulting in nan weights. Then, when weights are compared to assert that they're different, the test passes trivially because nan != nan. The lr is now reduced and there is a sanity check that none of the weights contain non-finite values.
See discussion in
https://github.com/huggingface/peft/pull/2433#issuecomment-2747800312 ff.
> FIX: Faulty test that results in nan weights

- examples/sft/train.py
- examples/sft/utils.py
There were 2 minor issues:
1. Using DeepSpeed, an env var is not set, leading to an error.
2. TRL renamed the `tokenizer` argument and to `processing_class` in v0.12.0.
> Fix sft example script trl and env var

- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/tp_layer.py
- src/peft/tuners/lora/variants.py
- tests/test_common_gpu.py
The `kwargs` might be required for some LoRA variants for proper initialization.
> LoRA variant init now also receives kwargs

- src/peft/utils/other.py
- src/peft/utils/save_and_load.py
`AuxiliaryTrainingWrapper.adapter_state_dict` now utilizes an external state dict for the computation of the module state dict to avoid problems with DeepSpeed (or FSDP) when dealing with distributed parameters.
It is not possible to simply wrap everything in `GatheredParameters` context managers since doing that leads to a deadlock when running on more than one process (reasons unclear). Since transformers, or more specifically, accelerate already handles state dict fetching for the whole model, it is more economical to use that state dict and rewrite the methods that before depended on `state_dict()` calls.
> Fix #2450: Revamp adapter_state_dict_* methods

- setup.py
- src/peft/__init__.py
- src/peft/utils/other.py
- src/peft/utils/save_and_load.py
This release is a patch release to release a fix for #2450 which might result in loss of `modules_to_save` when trained with deepspeed ZeRO stage 3.
Only the squashed commit from #2456 and the version bump are included in this PR.
> Prepare 0.15.1 patch

- .github/workflows/tests-main.yml
- tests/test_decoder_models.py
- tests/test_encoder_decoder_models.py
- tests/testing_utils.py
Follow up to #2462 using the same approach as there.
Test coverage before vs after the refactor is 100% identical.
> TST Refactor (continued) of encoder tests

- src/peft/tuners/lora/layer.py
- tests/test_custom_models.py
Resolves #2486
When merging with LoRA bias (i.e. setting lora_bias=True), the scaling was not considered, leading to incorrect results when scaling is not 1. This is now fixed.
Note: This was missed by the unit tests since the default values of `r` and `lora_alpha` are both 8, resulting in a scale of 1. The tests have now been altered to use a scale != 1 for `lora_bias=True`.
> FIX: Error when merging LoRA bias with scale != 1

- tests/testing_common.py
Employ offline mode when the model was already accessed once from the hub in order to speed up the CI and make the process less prone to rate limiting.
The idea here is that we can mark contexts that, once they were visited once for a specific model id, we can assume that they are cached locally and can set `HF_HUB_OFFLINE=1` for this context. This PR tests this concept for `testing_common` which is already a big chunk of the tests and probably has the biggest gain given the amount of change.
We already saw that the assumption does not always hold true: for the prompt tuning tests (`_test_prepare_input_for_generation`) there is a case where one time the tokenizer is not used for model X and after that time the tokenizer is used - since we're setting the hub to offline for the second time …
> Testing common uses situational HF_HUB_OFFLINE

- tests/test_common_gpu.py
- tests/test_initialization.py
- tests/testing_utils.py
**command**
`pytest -rA tests/test_initialization.py::TestLoraInitialization::test_lora_use_dora_linear`
**symptom**
This test is flaky on XPU, `torch.use_deterministic_algorithms()` can make it always pass by enabling deterministic algorithms.
**proposed fix**
I added a `require_deterministic` decorator for such cases: while entering this decorator, it will save current deterministic state and enable deterministic algorithm for target test case; while exiting from this decorator, it will restore before deterministic state.
**impact**
XPU: before this PR **fail**, after this PR **pass**
A100: before this PR **pass**, after this PR **pass**
Also the new decorator can fix below 2 fails mentioned in https://github.com/huggingface/peft/pull/2471, @jiqing-feng, so I remove them from skip …
> make test_lora_use_dora_linear pass on XPU

- tests/test_gpu_examples.py
There has been an [AQLM release](https://pypi.org/project/aqlm/#history) with the fix to the issue that originally broke the test.
> TST: AQLM test no longer x-fails

- tests/test_gpu_examples.py
- tests/test_initialization.py
PASSED tests/test_initialization.py::TestAdaLoraInitialization::test_adalora_default_init_identity
PASSED tests/test_initialization.py::TestLokrInitialization::test_lokr_linear_init_default
PASSED tests/test_gpu_examples.py::TestPTuningReproducibility::test_p_tuning_exactly_reproducible_after_loading
> TST make 3 flaky test cases always pass on XPU

- src/peft/tuners/cpt/config.py
- tests/test_cpt.py
- tests/test_seq_classifier.py
PR #2481 added sequence classification tests to PEFT. The test matrix included CPT. However, CPT only supports the task type `CAUSAL_LM`. These tests still passed but now [started failing](https://github.com/huggingface/peft/actions/runs/14592717272/job/40931414213) with:
> AttributeError: object has no attribute 'prepare_inputs_for_generation'
This is probably a change in transformers but since causal LM was never meant to work, the actual fix is to remove CPT from the seq cls test matrix.
Since CPT automatically changes the task type to `CAUSAL_LM`, this mistake can be hard to spot. Therefore, this PR also adds a warning if users pass the wrong task type.
> FIX: CPT should not be tested with sequence classification

- src/peft/tuners/lora/model.py
- tests/test_custom_models.py
Otherwise it's possible that the new merged adapter won't allocate enough space when a patterned rank is larger than config.r.
For example, the `cat` method uses `sum(adapters_ranks)` for the empty tensor alloc, so if `cat(loras)` for a given layer is ever > the sum of `config.r` the assignment will overflow.
Local test fails but it's all entirely the TestEvaInitialization module which appears completely unrelated.
> LORA/MODEL: Use max rank of pattern for `add_weighted_adapter`

- docs/source/developer_guides/quantization.md
- examples/stable_diffusion/inc_flux_lora_hpu.py
- src/peft/import_utils.py
- src/peft/tuners/lora/inc.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
Adds Intel Neural Compressor (INC) dispatcher to support loading LoRA into INC quantized model.  
Intel Neural Compressor modifies layer names or introduces new layers during quantization. Names can be seen [here](https://github.com/intel/neural-compressor/blob/main/neural_compressor/torch/algorithms/fp8_quant/_quant_common/helper_modules.py) (INC adds prefix “Patched“).  HuggingFace PEFT does not have a proper dispatcher to deal with the new names.
**Before this PR** we get the following error when trying to load LoRA weights into INC quantized model:
```bash
Traceback (most recent call last):
File "/root/./test.py", line 124, in <module>
pipeline.load_lora_weights("lora_model", adapter_name="user_lora")
File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/lora_pipeline.py", …
```
> Add INC dispatcher

- src/peft/tuners/lora/layer.py
- tests/test_initialization.py
For the LoRA methods
- `set_scale`
- `scale_layer`
- `unscale_layer`
unit tests, docstrings, and type annotations were added.
> ENH: Add tests, docs, types for scaling methods

- src/peft/tuners/lora/layer.py
The arguments of the `forward` method of `MultiheadAttention` are called `query` etc. PEFT used `x`. Therefore, if a caller uses keywords only, the argument is not assigned, resulting in an error.
This was initially reported here:
https://github.com/huggingface/peft/issues/761#issuecomment-2818029500
Note: Other layers' `forward` method (like `Linear`) also uses incorrect names, like `x` instead of `input`, but so far no issues were reported, so I'll leave it as is for now.
> FIX: Use correct argument name in MultiheadAttention forward

- src/peft/tuners/tuners_utils.py
- tests/test_other.py
`inject_adapter` currently does not check whether the targeted layer belongs to an already existing adapter or not. This can lead to the situation that wildcard patterns (e.g., `o_proj.*`) will attempt to add adapters to existing adapter layers which naturally falls apart.
This fix attempts to check which keys are already assumed to belong to adapters by checking for `BaseTunerLayer` instances and doing a prefix check.
Note that the removal of
```diff
-_check_for_modules_to_save = getattr(peft_config, "modules_to_save", None) is not None
```
is a separate cleanup - it is a leftover from the refactor in #2481 when `inject_adapter` was handling `modules_to_save` code which was moved to `check_target_module_exists`.
> Fix #2535: Prevent adapters targeting themselves

- tests/conftest.py
Changes in transformers introduced ~~2 errors~~ an error in the MacOS CI, which are handled in this PR.
**Edit**: The second was fixed in https://github.com/huggingface/transformers/pull/38496. It's still unreleased, hence the `DTensor` import errors in the Mac tests, but I think we can ignore those.
For context on why we use torch 2.2 for MacOS, check #2431. Unfortunately, as of today, the [available GH workers](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) for MacOS still haven't improved.
The ~~1st~~ error was introduced by
https://github.com/huggingface/transformers/pull/37785, which results in `torch.load` failing when using torch < 2.6.
~~The 2nd error was introduced by …
> CI: Handle errors with MacOS and transformers

- .github/zizmor.yml
These images are OK to be unpinned as they are supposed to run tests on the latest versions and are not used for doing pipeline work such as releasing or building user artifacts.
> Fix zizmor warnings about unpinned docker images

- tests/test_custom_models.py
- tests/testing_common.py
This is a follow up to #2462, #2478, and #2491.
Finish the refactor from unittest-style tests to pytest-style tests to now also include the last big file to still use the old style, `test_custom_models.py`. This file was already mostly written with pytest in mind, so the changes were rather minimal.
With this class refactored, we can finally remove `ClassInstantier`, which made understanding test parametrization much more difficult.
There are still a few `unittest.TestCase` classes found throughout, but they are pretty isolated, so no big need to refactor them right now.
Note that the test coverage is the same except for one difference. For some reason, I found that module level `__getattr__` is no longer called when moving from unittest to pytest, such as here: …
> TST: Refactor unittest to pytest style custom tests

- tests/test_lora_variants.py
This change adds a place for future lora variant tests to linger and also adds a basic test that checks whether the variant was correctly applied to the lora layer if so requested. This does not cover quantized layers yet but it should be similar to add thanks to the mapping.
Since we're expecting a lot more variants to be added in the future it is probably sensible to start early in establishing a place for testing.
> Simple variant application test

- method_comparison/app.py
- method_comparison/sanitizer.py
- method_comparison/test_sanitizer.py
Since `DataFrame.query` is potentially vulnerable we limit the possible filter input to a fixed grammar that is roughly like this:
```
expr = left op right
left = ( expr ) | literal
right = ( expr ) | literal
op = in | >= | < | <= | == | and | or
```
this will give us boolean operations and basic comparisons. Note that `literal` can be arbitrary python literals (strings, tuples, ...).
> Input sanitizer for benchmark result renderer

- method_comparison/MetaMathQA/run.py
- method_comparison/MetaMathQA/utils.py
This PR adds tracking for the number of (trainable) parameters for each experiment
Tracking the number of parameters, trainable and total, will make the results
much more transparent regarding model capacity. If a method was accidentally
trained with a lot more or less trainable parameters it would make for unfair
results. Having these numbers will also make benchmarking parameter efficiency
easier.
This is a draft based on https://github.com/huggingface/peft/pull/2593.
> Track number of (trainable) parameters for MetaMathQA

- method_comparison/MetaMathQA/experiments/full-finetuning/llama-3.2-3B-lr_0.00001/training_params.json
- method_comparison/MetaMathQA/run.py
- method_comparison/MetaMathQA/utils.py
- method_comparison/app.py
- method_comparison/processing.py
Enable full fine-tuning on MetaMathQA for the method comparison suite.
I ran the full fine-tuning experiment, here are some key results:
```json
...
"cuda_memory_reserved_avg": 33098872284,
"cuda_memory_max": 37241225216,
"cuda_memory_reserved_99th": 33573390254,
"train_time": 3249.7733414780005,
...
"test accuracy": 0.5064442759666414,
"train loss": 0.5987803322076798,
"train samples": 20000,
"train total tokens": 4198051
```
Furthermore, I found a duplicate key in the logs, which I removed, and noticed an incorrect column name in the app, which is renamed now.
~~After checking in a proper training run result, we should consider adjusting `app.py` to remove the full fine-tuning results from the plot (but still keep it in the df) as its values are often outliers and would skew the plot.~~ …
> ENH: Method comparison allow full finetuning

- examples/qalora_finetuning/README.md
- examples/qalora_finetuning/qalora_gptq_finetuning.py
- src/peft/tuners/lora/config.py
- src/peft/tuners/lora/gptq.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/lora/variants.py
- tests/test_custom_models.py
- tests/test_gpu_examples.py
This pull request introduces QALoRA (Quantization-Aware Low-Rank Adaptation), a new fine-tuning technique for quantized large language models, along with its implementation in the PEFT library. The changes include updates to documentation, configuration, and core logic to support QALoRA's memory-efficient and performance-preserving features.
* [`examples/qalora_finetuning/README.md`](diffhunk://#diff-6e8694feed4e98d9caf8f6a187aeb945e989bf6e00392be4b7674bb0b6be96d7R1-R178): Added detailed documentation for QALoRA, including its introduction, implementation details, usage examples, command-line instructions, and comparison with other techniques like LoRA and DoRA.
* [`src/peft/tuners/lora/config.py`](diffhunk://#diff-13380145401d203d5935c5189dd09879f990b81aa63e8e3aaff8ce9110333f0eR497-R519): …
> Add support for Quantization-Aware Low-Rank Adaptation (QALoRA)

- method_comparison/MetaMathQA/run.py
- method_comparison/MetaMathQA/utils.py
In #2593, the timestamp was removed from the file name of result files. This makes sense for the proper results, as those should have unique file names and are tracked in git. However, for temporary and cancelled results, this is not true. Therefore, the timestamp is added back in.
Moreover, I applied ruff to the `MetaMathQA/` directory (it's not applied automatically) and fixed some imports. Ruff seems to get confused about local modules, thus the `data` and `utils` import are treated differently, but IMO no big deal.
> ENH Method comparison: temporary and cancelled result files include timestamp

- src/peft/peft_model.py
- src/peft/utils/other.py
- tests/test_decoder_models.py
See also #2580
Resolves CI errors such as this one:
https://github.com/huggingface/peft/actions/runs/15481482956/job/43588020111#step:5:53182
This PR resolves 2 issues:
After the transformers change in https://github.com/huggingface/transformers/pull/37866, it can happen that:
> Models using different types of attention in different layers (i.e. gemma3) will now have a dict returned by prepare_inputd_for_generation (one dict entry per attention type)
As PEFT operates on the attention mask for prompt learning methods, we need to adjust the code for the possibility of `attention_mask` being a dict. Right now, I simply extract the single value if the dict is just one element. For other sizes, I just raise an error, as I don't know how to deal with that. For our tests, this is enough but we …
> FIX Account for attention mask being a dict, fix generate issues with gemma

- src/peft/tuners/lora/bnb.py
The function signature was missing `**kwargs`, which results in a [failure](https://github.com/huggingface/peft/actions/runs/15916801267/job/44895818094) after merging #2571.
> FIX Update signature for resolve_lora_variant

- tests/test_gpu_examples.py
Also see #2484 for a similar issue.
As discussed internally, since https://github.com/huggingface/transformers/pull/37982, some multi-GPU tests started failing because all parameters are loaded onto a single GPU. This should now be fixed by providing an explicit `device_map` instead of relying on `"auto"`.
_Note_: I only fixed the tests that were actually failing, the other ones are left untouched (i.e. still use `device_map="auto"`), though who knows how long until they also start failing.
Furthermore, for an unknown reason, the HQQ test started failing as the correlation dipped below 0.97 -- to 0.9696 actually. I think this is close enough to not warrant further investigation. Therefore, I only decreased the threshold.
-----
For reference, I wrote a small function to create the …
> FIX CI Multi-GPU tests require device_map

- setup.py
- src/peft/__init__.py
- tests/test_gpu_examples.py
- tests/testing_common.py
- Bump versions
- Update a comment to poin to new PR
- Remove a test skip that is obsolete after #2579
> Release 0.16.0

- src/peft/config.py
- tests/test_seq_classifier.py
This PR relates to #2642 but is probably not the cause of the reported issue there.
When using prompt learning methods, `modules_to_save` is not correctly set automatically. This is really bad when using, for instance, sequence classification tasks, which require the classifier layer to be added to `modules_to_save`.
The issue was introduced in #2220 where it is wrongly assumed that the PEFT config always has a `modules_to_save` attribute, which is not true for prompt learning. In #2481, this was partly fixed by using `getattr` to avoid an error. However, this did not resolve the fundamental issue that for prompt learning, there is no such attribute, resulting in `module_to_save` not being applied.
This PR proposes to fix this by adding `modules_to_save` to the prompt learning configs.
> FIX: Prompt learning methods modules_to_save issue

- src/peft/peft_model.py
- src/peft/utils/constants.py
Due to https://github.com/huggingface/transformers/pull/38635, [several tests involving prefix tuning broke](https://github.com/huggingface/peft/actions/runs/16417140904/job/46385751329).
This PR fixes this by resolving two issues:
1. The `_supports_cache_class` attribute was removed, we can now assume that it is True if the attribute does not exist.
2. We had special handling of `past_key_values` for `GPTBigCodeForCausalLM` which is no longer required (nor valid) after that PR, so it is removed depending on the transformers version.
> FIX Prefix tuning after transformers PR 38635

- docs/source/accelerate/deepspeed.md
- docs/source/accelerate/fsdp.md
- docs/source/conceptual_guides/oft.md
- docs/source/quicktour.md
- docs/source/task_guides/lora_based_methods.md
- examples/bone_finetuning/README.md
- examples/bone_finetuning/bone_finetuning.py
- examples/conditional_generation/peft_prompt_tuning_seq2seq_with_generate.ipynb
- examples/corda_finetuning/README.md
- examples/corda_finetuning/corda_finetuning.py
- examples/image_classification/image_classification_peft_lora.ipynb
- examples/int8_training/peft_bnb_whisper_large_v2_training.ipynb
- examples/lorafa_finetune/README.md
- examples/olora_finetuning/README.md
- examples/pissa_finetuning/README.md
- examples/pissa_finetuning/pissa_finetuning.py
- examples/poly/peft_poly_seq2seq_with_generate.ipynb
- examples/randlora_finetuning/README.md
- examples/shira_finetuning/README.md
- examples/token_classification/peft_lora_ner.ipynb
Update tokenizer parameter in sfttrainer across multiple examples
https://github.com/huggingface/peft/issues/2663
> Update tokenizer parameter in sfttrainer across multiple examples

- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- tests/test_initialization.py
- tests/test_target_parameters.py
When the `target_parameters` feature for LoRA was introduced in #2638, there was one gap, namely the possibility to target multiple `nn.Parameter`s on the same module (there was only a workaround involving multiple adapters, but that is not user friendly). With this PR, it is now possible to achieve this.
The mechanism to enable this is a bit crude, namely allowing to nest multiple `ParamWrapper`s. This should generally be fine as long as there are only a couple of `nn.Parameter`s being targeted on the same module. When there are dozens or hundreds, this approach could load to slow downs or other issues.
A side effect of this implementation is that the `ParamWrapper`, when it removes the parametrization, now only removes its own parametrization. When using …
> ENH: Targeting multiple parameters on the same module

- .github/workflows/tests.yml
- tests/test_target_parameters.py
- tests/testing_common.py
For testing `target_parameters`, we use a tiny Llama4 model. This model was refactored in
https://github.com/huggingface/transformers/pull/39501, resulting in one parameter being accessed an additional time:
https://github.com/huggingface/transformers/pull/39501/files#diff-e668ec07f78afdb2cb805d939e47453757f0b9437436cb860fcb7cb2431c9cf5R69
(to doublle-check: bad commit: `300d42a43eb3804002b841a389637ceb99a081bb`, good commit: `abaa043d60edfd0eae78b7a0474aad8e5e433bda`)
Therefore, a unit test that relied on how often this parameter was accessed started failing. This PR updates the count to the correct number.
Additionally changes:
- debug print statements that were accidentally left over are now removed
- had to loosen some tolerances for …
> FIX Failing target_parameters param usage count

- src/peft/tuners/lora/config.py
- src/peft/utils/save_and_load.py
When using FSDP with trainable tokens, there was an error when retrieving the `state_dict` of the `TrainableTokensWrapper`. The reason is that for the `state_dict` that is passed to `get_peft_model_state_dict`, the FSDP wrapper was already unwrapped, which means the keys don't have the FSDP-specific prefix. However, in the PEFT code, when looking up keys from said `state_dict`, the prefix was not removed. Now it is removed, making the lookup succeed. The same logic applies to `set_peft_model_state_dict`.
I could successfully start training with FSDP and trainable tokens locally by adjusting the `examples/sft` script to include trainable tokens. Checkpoints could be successfully created and resumed from. The only change I needed to make was to configure `use_orig_params=True` for FSDP.
I …
> Fix trainable tokens with fsdp

- tests/test_incremental_pca.py
- tests/test_tuners_utils.py
A bunch of tests in `test_tuners_utils.py` didn't use the decorator so far, which is now fixed. This should hopefully help reduce timeouts.
Moreover, the iris dataset loading is now moved to a module-scoped fixture (before, it was just loaded on module level). This doesn't help with caching, but it prevents loading of this dataset when the corresponding tests are not even run.
> TST: Add more HF Hub model caching

- examples/lorafa_finetune/README.md
- examples/lorafa_finetune/lorafa_finetuning.py
@BenjaminBossan , pls help review, thx very much.
> validated lorafa on xpu, passed

- examples/feature_extraction/peft_lora_embedding_semantic_search.py
- examples/feature_extraction/requirements.txt
Here we need to pin datasets to an old version to load the datasets in example. Otherwise it will crash in [L267](https://github.com/huggingface/peft/blob/main/examples/feature_extraction/peft_lora_embedding_semantic_search.py#L267)
> fix bug for feature_extraction example

- src/peft/tuners/c3a/config.py
- src/peft/tuners/c3a/layer.py
- src/peft/tuners/fourierft/config.py
- tests/test_custom_models.py
- tests/test_decoder_models.py
- tests/testing_common.py
- tests/testing_utils.py
Resolves #2695
For some PEFT methods, there was a bit of a mess when it comes to how the `init_weights` argument was set in `test_custom_models.py`. The default `kwargs` for the tests should be that the PEFT method is initialized as an identity transform, and for specific tests we want to disable that. Note that most PEFT methods are initialized by default to be identity transforms, which is why the argument does not need to be set explicitly, but it's not true for all PEFT methods.
With this PR, SHiRA, C3A, and FourierFT are now initialized to be consistent with this. This made it possible to remove some extra handling of those methods which was intermingled with certain tests.
Moreover, in the appropriate places, I did the following:
- use the `set_init_weights_false` helper function
- …
> CHORE: Clean up config kwargs in custom model tests

- docs/source/developer_guides/lora.md
- setup.py
- src/peft/__init__.py
- src/peft/tuners/lora/layer.py
- src/peft/tuners/lora/model.py
- src/peft/tuners/tuners_utils.py
- tests/test_custom_models.py
- tests/test_initialization.py
- tests/test_target_parameters.py
- tests/testing_common.py
This PR contains the changes require for the 0.17.1 patch release:
- The commit with the fixes to `target_parameters` (#2710)
- Version bumps
Note: Windows tests are failing because #2724 is not included, but since this is only affecting tests, I see no reason to cherry-pick that commit into the release.
> Release: 0.17.1 changes

- docs/source/developer_guides/lora.md
There was a minor typo which a suggestion of PR #2609 which broke code formatting for one code sample.
This is a simple fix for that.
> Fix missing code start in docs

- src/peft/peft_model.py
Issue #2757 is about replacing the `from_legacy_cache` method of `transformers` `Cache` classes in `peft` due to their removal from transformers in v4.58.0. The `from_legacy_cache` method is used to convert data in the form of iterables to Cache objects. 
The issue is addressed by replacing the method with the corresponding constructors of the Cache classes since they also deal with the data in a similar way.
> Replace from_legacy_cache method with constructors 

- src/peft/mapping_func.py
- src/peft/peft_model.py
- tests/test_initialization.py
- The warning message was missing spaces between sentences.
- Added `'` around strings for clarity
- For one warning, which extended another warning, put it at the start instead of the end, because the other warning can be quite long, leading to users missing the addition
For more context on this warning, see #2254
> FIX: Small fixes to warning like missing spaces

- src/peft/mixed_model.py
- src/peft/peft_model.py
Either re-introduced or overlooked `<Tip>`s converted to new syntax.
> Some more TIP migration

- src/peft/mixed_model.py
- src/peft/peft_model.py
- src/peft/utils/hotswap.py
- tests/regression/test_regression.py
- tests/test_initialization.py
The `reset_sessions` function is removed but it's also no longer necessary to call it for the purpose we used it.
Moreover, the deprecated `use_auth_token` argument is fully removed now, so everywhere we used to pass it, it is now removed, unless a user passes it explicitly.
> CHORE: Ensure PEFT works with huggingface_hub 1.0.0

- examples/pissa_finetuning/README.md
There is a trivial typo in pissa finetune readme, I just fix it
Before
```python
import torch
from peft import LoraConfig, get_peft_model
from transformers import AutoTokenizer, AutoModelForCausalLMfrom trl import SFTConfig, SFTTrainer
from datasets import load_dataset
```
After I fix
```python
import torch
from peft import LoraConfig, get_peft_model
from transformers import AutoTokenizer, AutoModelForCausalLM
from trl import SFTConfig, SFTTrainer
from datasets import load_dataset
```
> Fix typo in pissa finetune readme

- docs/source/_toctree.yml
I missed the failed doc build in the original PR.
> FIX DOC Add missing TOC entry for WaveFT
